### ISSUE TITLE
Invalid download directory for MockTestRunner (EPERM)

### ISSUE THREAD

**Issue by fkpama** [microsoft/azure-pipelines-task-lib#1005]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version:  4.4.0

### Issue Description

When using the lib on a Windows machine and creating an instance of MockTestRunner, the test fail because of access permission when the test is launched from a drive that is not the same as the HOMEDRIVE (i.e: User home at `C:\User\foo` and test/code launched from `F:\Source\Code`) if the user doesn't have the necessary permissions on the drive from.

This is because the MockTestRunner instance tries to download the node.exe in the `**F:\\**Users\foo` since [the download directory is inferred from the HOMEPATH](https://github.com/microsoft/azure-pipelines-task-lib/blob/5ab4ebe0c1c1472e62e08fd10001983ed5d01e40/node/mock-test.ts#L13C14-L13C14) environment variable.

The problem is that the HOMEPATH environment variable is defined on Windows to [the path of the user home directory *without* the drive](https://wiki.tcl-lang.org/page/HOMEPATH#:~:text=On%20a%20Microsoft%20Windows%20system,to%20the%20user%27s%20home%20directory.&text=That%20is%2C%20%25HOMEDRIVE%25%20is,JRandom%E2%80%9D%20(or%20whatever).) (e.g.: To obtain the complete path you need %HOMEDRIVE%\%HOMEPATH%). so the download directory is computed as `\User\foo\azure-pipelines-task-lib\...\_downloads`, which, when used, is expanded to `>>F:\<<User\foo\azure-pipelines-task-lib\...\_downloads` and not` >>C:\<<User\foo\azure-pipelines-task-lib\...\_downloads`

To fix this, I [submitted the PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/1006) #1006 which replace the order of the checks to test for the USERPROFILE environment variable before HOMEPATH.  #On windows machines, the former is defined to the necessary path (C:\Users\foo)

Let me know what I need to provide

### Steps to reproduce
1.  Create a Mocha test according to any [tutorial ](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#2-unit-test-your-task-scripts). The code of the test **MUST** be on another drive than the user home drive (%HOMEDRIVE% environment var)
2. Instanciate MockTestRunner in your test
3. launch the test from VSCode (confirmed) from the source code directory (not on the same drive as the user home)

### Expected behaviour
The MockTestRunner [downloads a version of node.exe in the User's home directory](https://github.com/microsoft/azure-pipelines-task-lib/blob/5ab4ebe0c1c1472e62e08fd10001983ed5d01e40/node/mock-test.ts#L187C21-L187C21)

### Actual behaviour
The test fails before the users don't have the rights

![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/37318755/be1e0451-23da-438b-863d-45bf2d1a158b)

**Comment by kirill-ivlev** [comment]
Hi @fkpama,
Thank you for providing a fix, we will test/review and merge it.

**Comment by fkpama** [comment]
Hi @kirill-ivlev,

Thanks

Closing
