### ISSUE TITLE
Add runner for Node 20 LTS

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/azure-pipelines-task-lib#1043]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 4.3.1

### Issue Description

Please provide a node20 task runner

### Expected behaviour

I'd like a node20 task runner to run node 20 code.

### Actual behaviour

There are runners node, node10, and node16, representing LTS releases of NodeJS.

### Logs

Don't get me wrong, my code works fine. I may be misunderstanding, but I'd just like to see a node runner for each nodelts release.

**Comment by gitnubster** [comment]
I would like to see this also. As far the tasks.schema.json concerns, the execution handler Node20_1 does not exist. (While it does at agent side.)
In a task I have:
```
"$schema": "https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json",
"execution": {
    "Node20_1": {
      "target": "$(currentDirectory)/taskfile.js",
      "argumentFormat": "",
      "workingDirectory": "$(currentDirectory)"
    }
  }
```
And VSCode shows:
``Property Node20_1 is not allowed.``

**Comment by Herve-M** [comment]
For the curious one: 
Runner updates for Node20: 
- https://github.com/microsoft/azure-pipelines-agent/pull/4346
- https://github.com/microsoft/azure-pipelines-agent/pull/4518

task-lib update for Node20:
- #1039
- #962 

It seems that `Node20_1` is usable as this task use it already: https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/NotationV0/task.json

**Comment by Herve-M** [comment]
According to this [Azure DevOps changelog](https://learn.microsoft.com/en-us/azure/devops/release-notes/2024/sprint-243-update#azure-pipelines-tasks-use-node-20) it has been released even if the diff. PR are still open.. 

See [how-to notes](https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#q-how-can-i-upgrade-my-custom-task-to-the-latest-node).

**Comment by ncook-hxgn** [comment]
Docs look good, can't wait to use the node20 runner :)
