### ISSUE TITLE
unused variable `stdbuffer`

### ISSUE THREAD

**Issue by gusega** [microsoft/azure-pipelines-task-lib#1054]
what is the purpose of `stdbuffer` variable on https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/toolrunner.ts#L1101  I cannot see any code that updates it.

**Comment by ismayilov-ismayil** [comment]
Hi @gusega, Thanks for reporting. I will check it and revert back soon.

**Comment by KonstantinTyukalov** [comment]
Fixed here: https://github.com/microsoft/azure-pipelines-task-lib/pull/1055
Thanks!
