### ISSUE TITLE
Localization tl.loc does not have access to field names

### ISSUE THREAD

**Issue by jquince** [microsoft/azure-pipelines-task-lib#133]
Given this field def
{
            "name": "uploadProxyUser",
            "type": "string",
            "label": "Proxy Username",
            "defaultValue": "",
            "required": false,
            "helpMarkDown": "" ,
            "groupName":"scan"
        }

I see that "loc.input.label.uploadProxyUser": "Proxy Username", is in the resource file.

but tl.loc("loc.input.label.uploadProxyUser") gets "Can't find loc string for key: loc.input.label.uploadProxyUser"

What's the proper way to handle localization of field name and be able to refer back to it for validation error messages.

**Comment by ericsciple** [comment]
it's not in the lib today. i think a function like `locLabel(inputName: string)` would make sense and would need to fallback to the value in the task.json, then inputName.
