### ISSUE TITLE
Add "setVariable(name: string, value: string, isSecret?: boolean)" method to mock-run.ts

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/azure-pipelines-task-lib#148]
In [mock-run.ts class](https://github.com/Microsoft/vsts-task-lib/blob/master/node/mock-run.ts) there is a method to setInput() method. It would be great to have a setVariable method for mocking variables during test. The method should take:
- **name**: name of the variable to add
- **value**: value of the variable
- **isSecret**: optional boolean that sets the variable as a secret if set to true (not secret if false or not supplied)

**Comment by damccorm** [comment]
Just added a PR for this
