### ISSUE TITLE
Debugging Task Tests

### ISSUE THREAD

**Issue by cwoolumtechnossus** [Microsoft/azure-pipelines-task-lib#153]
I'm trying to debug my unit tests for a task I'm writing. I'm working with VS Code and I can get the test to run but never hit any debug points. Is there a recommended configuration for doing this?

**Comment by bryanmacfarlane** [comment]
I had success setting breakpoints in the javascript (instead of the typescript) but that was with running the task interactively.  Haven't tried with tests ... maybe different since it's running another mocha tool in between?  I'll try it out later.  Tracing / logging is always an option.

**Comment by cwoolumtechnossus** [comment]
I think the testing framework is eating the errors I’m hitting because tracing/logging doesn’t seem to work. What configuration are you using to run the debugger?

**Comment by damccorm** [comment]
The Node recommended way to do this is to use the [--inspect flag](https://nodejs.org/en/docs/guides/debugging-getting-started/). It should have built in support for VSCode as well.

The downside here is that I don't think it likes shelljs/our way of starting tests, so I think you'd need to create your own launch.json config file - personally, I've found it much easier to just use logging and it usually gets the job done for me.

Is the debugger still swallowing  your logging? I've never had that issue so I'm curious as to why that might be happening.

**Comment by damccorm** [comment]
I'm going to close here, please reopen if this is still an issue.
