### ISSUE TITLE
Tasks should be able to provide an "upgrade.ps/ts/js"

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-task-lib#195]
I have a few tasks that are now a year old. I have a much better idea now of what I want these to do than before. I'd like to do a bit of refactoring, but there are a few issues:

* Some of my tasks have long names, this causes long name issues on windows. I'd like to change the Task Name and remove "jessehouwing-" from them. But have the tasks stay in working state.
* Some tasks in the same extension were contributed by different people and use slightly different names for fields that do the same thing. I'd like to rename these fields, but have the value carry over.
* I have some fields that have a new default value, but since default values are saved in the BuildDefinition.json, there's no good way to fix these. Same for fields that are currently not visible "due to visible rule", but still have values that may no longer be valid.
* I have a few fields that went from one type to another (string to filepath for example).
* Some tasks used "hidden variables" (not mine, I inherited this one), I'd like to move the usage of those to a normal input without breaking, so I'd like to request the presence of such variable and its value, as part of the mapping.

None of these are terrible big changes, yet the current usage is preventing me from either notifying my users or providing a "auto-update" script.

It would be nice if we could provide a update-map.ts or something that would run when switching between major versions. It could warn people of breaking changes, auto-fix certain fields by moving the old value to a new one and clear all fields that have their default value stored.

**Comment by ericsciple** [comment]
Major version locking is supported now on VSTS and shipping with TFS 2017 Update 1. So if you bump the major version, there is a notification in the build definition UI and you can provide a small markdown description.

Keep in mind, moving across major version is an explicit choice for the end-user, so they need to stop and read the description and understand what they would gain by moving to new major version (e.g. internal refactoring not motivational to end user).

Does that help?

**Comment by jessehouwing** [comment]
Not really... We did a major version upgrade with one of the Ranger tasks
that's used in most Ranger pipelines. Manually adjusting 35 builds and
release pipelines is a big chore.

When a task remains functionally the same, an upgrade script can take care
of such upgrades automatically. Or at least offer that.

If the upgrade encounters issues it could point them out to the user.

**Comment by jessehouwing** [comment]
Another reason I'd like this is because I want to deprecated one of my extensions in favor of another one. I'd like to offer my users an option to switch over with the least amount of effort on their end.
