### ISSUE TITLE
Provide a working sample of setting Invoke-VstsTaskScript environment variables

### ISSUE THREAD

**Issue by rvf148** [Microsoft/azure-pipelines-task-lib#197]
Hi,

How do i use Invoke-VstsTaskScript?
I allways get 
`PS C:\Users\Administrator\Documents\Tasks\PSTask> C:\Users\Administrator\Documents\Tasks\PSTask\TestDummyTask.ps1
##vso[task.setvariable variable=System.Culture;issecret=False]nl-be
##vso[task.debug]VstsTaskSdk 0.8.0 commit 
##vso[task.debug]Caught exception from task script.
##vso[task.logissue type=error]Cannot convert the "Microsoft.TeamFoundation.Client.TfsClientCredentials" value of type "System.String" to type "System.T
ype".
##vso[task.complete result=Failed]`

`Import-Module .\ps_modules\VstsTaskSdk
Set-VstsTaskVariable -Name 'System.Culture' -Value 'nl-be'

$ENV:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI = 'http://tfs.myserver.be:8080/tfs/myproject'

$env:INPUT_MYENDPOINT = 'SystemVssConnection'
$env:ENDPOINT_URL_SystemVssConnection = 'http://tfs.myserver.com:8080/tfs/myproject'
$env:ENDPOINT_AUTH_SystemVssConnection = '{ "Parameters": { "UserName": "SomeUser", "Password": "nicepwd" }, "Scheme": "UsernamePassword" }'
$env:ENDPOINT_DATA_SystemVssConnection = '{ "Key1": "Value1", "Key2": "Value2" }'

Invoke-VstsTaskScript -ScriptBlock { . .\DummyTask.ps1 } -Verbose`

Documentation is not really clear on how the get the data for the endpoint
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/TestingAndDebugging.md

The DummyTask contains:

$versionControlServer = Get-VstsTfsService -TypeName Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer
if ($versionControlServer)
{
    Write-Host "OK"
}
regards,

**Comment by ericsciple** [comment]
Here is a sample task: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/VSBuild

one min, i'll find one that uses endpoints...

**Comment by ericsciple** [comment]
Here is an example of how to get the selected endpoint input: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricDeploy/deploy.ps1#L26

And then working with it, you will need to know what properties you need from the endpoint. Either .Auth.Scheme or .Auth.Parameters (dictionary) or .Auth.Data (dictionary)

**Comment by aumanjoa** [comment]
any updates on this? I have the same issue
Is it possible to add a working example to this thread how to connect to the TFS

**Comment by aumanjoa** [comment]
@ericsciple  any suggestions? I dont get this working :( I am simply trying to get this line working

`  $versionControlServer = Get-VstsTfsService -TypeName 'Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer'`


but always get this error:

> cannot convert the "[Microsoft.TeamFoundation.VersionControl.Client.VersionControlServer]" value of type "System.String" to type "System.Type". 

even when I try it on the agent

**Comment by rvf148** [comment]
Hi,

Put the assembly needed for the class in the root of your task. (Don't
forget dependencies)
Get it from nuget team foundation extended client, extract needed assemblies

Regards,
Raf

**Comment by aumanjoa** [comment]
Hi @rvf148 

thanks for the replay. 
The Assemblies are already part of the agent. Can I not reuse thouse? I thought this is the benefit using this lib function.

**Comment by rvf148** [comment]
No, that would create a dependency on the agent. Microsoft includes the
dependecies with each Task.

Regards,
Raf

Op 15 feb. 2017 10:05 p.m. schreef "aumanjoa" <notifications@github.com>:

**Comment by ericsciple** [comment]
that's correct, it's best to bundle the sdk with your task for reasons [listed here](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/UsingOM.md#bundle-the-sdk-with-your-task)

**Comment by aumanjoa** [comment]
thanks so much that helped.

But needed to open a other issue. https://github.com/Microsoft/vsts-task-lib/issues/209 it seems the dlls not wirking with TFS2017 and TFS2015 in the same way

**Comment by damccorm** [comment]
It looks like this has been resolved so I'm going to close. Please reopen if appropriate.
