### ISSUE TITLE
npm powershell package out of date

### ISSUE THREAD

**Issue by jabbera** [Microsoft/azure-pipelines-task-lib#203]
The current published version is 0.6.4. Please update.

https://www.npmjs.com/package/vsts-task-sdk

**Comment by ericsciple** [comment]
it's on the powershellgallery now. [this doc](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Consuming.md#where-to-get-it) details where to get it.

the description on npmjs should be updated
