### ISSUE TITLE
Uploading test results using PowerShell API

### ISSUE THREAD

**Issue by viertaxa** [Microsoft/azure-pipelines-task-lib#219]
What is the process to publish a test result using the Powershell API?

I see that using a Node task I can use 
`let tp: tl.TestPublisher = new tl.TestPublisher(testRunner);`

Looking through the Powershell API documentation, I don't see an equivalent.

Thanks!

**Comment by damccorm** [comment]
You can do this using the ```artifact.upload``` command. Full documentation [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md)

**Comment by aktzbn** [comment]
Unclear how to specify format of test report.
