### ISSUE TITLE
Tasks with gyp built dependencies

### ISSUE THREAD

**Issue by aloisdeniel** [Microsoft/azure-pipelines-task-lib#241]
I'm currently trying to write my own VSTS extension with its custom task. This task depends on [sharp](https://www.npmjs.com/package/sharp) that has to be build at `npm install` time through **gyp**. But the `node_modules` seem to have to be included into the `.vsix` before upload of the extension so I didn't find any solution for this (*maybe pre-compiling the module for all agent architectures and requiring the module thanks to the current agent executing architecture*) ...

**Comment by ericsciple** [comment]
@aloisdeniel yes tasks are generally self contained so they work in internet-restricted or internet-disconnected scenarios.

I wonder if there is a potential workaround to bundle the module with your task in raw form, and then the first time your task runs, you npm install from the raw folder.

**Comment by damccorm** [comment]
@aloisdeniel did this solve your problem/were you able to get it to work?

**Comment by damccorm** [comment]
I'm going to close, please reopen if this is still an issue.
