### ISSUE TITLE
Get-VstsVssHttpClient assembly load fails for Microsoft.TeamFoundation.Build.WebApi clients

### ISSUE THREAD

**Issue by thevintik** [microsoft/azure-pipelines-task-lib#263]
Hi,

I am trying to instantiate Microsoft.TeamFoundation.Build.WebApi.XamlBuildHttpClient (from assembly [Microsoft.TeamFoundation.Build2.WebApi](https://www.nuget.org/packages/Microsoft.TeamFoundationServer.Client/)) via Get-VstsVssHttpClient function, and I get "Cannot convert the ... value of type System.String to type System.Type" error.

I found similar [Issue 97](https://github.com/Microsoft/vsts-task-lib/issues/197), but I'm already placing all required assemblies in the root of my task.
I've managed to resolve the issue temporarily by renaming Microsoft.TeamFoundation.Buil**d2.W**ebApi.dll into Microsoft.TeamFoundation.Buil**d.W**ebApi.dll
Maybe you can improve your assembly finding [mechanisms](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/VstsTaskSdk/ServerOMFunctions.ps1#L427).

**Comment by ericsciple** [comment]
Makes sense. When building the candidate DLL paths, I think we can special-case this and add:
```powershell
if ($TypeName -eq 'Microsoft.TeamFoundation.Build.WebApi.XamlBuildHttpClient') {
    $dllPaths += ...
}
```

Another workaround for you would be to pre-load the DLL before calling Get-VstsVssHttpClient. The function tries the load the type before attempting to automatically find the assembly (convenience).

**Comment by thevintik** [comment]
I would suggest to special-case the whole namespace Microsoft.TeamFoundation.Build.WebApi.* (e.g. Microsoft.TeamFoundation.Build.WebApi.BuildHttpClient is in the same assembly)

**Comment by damccorm** [comment]
Added a PR to address this
