### ISSUE TITLE
MockTestRunner fail only for exec() but ok for execSync()

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Microsoft/azure-pipelines-task-lib#265]
I'm writing a task. However I found an weird behavior. 
When I use MockToolRunner, unit test fails when I use exec() command.

```
let binary = new ToolRunner(tl.which(this.binary, true));
:
 await binary.exec();
```
```
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Error: istioctl failed. spawn istioctl ENOENT
##vso[task.complete result=Failed;]Error: istioctl failed. spawn istioctl ENOENT

STDERR: (node:1992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Failed to execute istioctl command.

```
However, If I changes it to execSync(), it doesn't happen. Just pass the all unit test.

I'm using `^2.0.3-preview`. I don't use 2.0.5 for the other issue. 
https://github.com/Microsoft/vsts-task-lib/issues/264

**Comment by bryanmacfarlane** [comment]
I'll take a look at this ...

**Comment by TsuyoshiUshio** [comment]
Thank you. If you want to reproduce this, please use this repo. (Master)
https://github.com/TsuyoshiUshio/KubernetesTask

Also, if you have any question, please let me know.

**Comment by TsuyoshiUshio** [comment]
Hi @bryanmacfarlane , I create a sample project for reproducing this issue. It might be much easier to investigate. 

https://github.com/TsuyoshiUshio/vsts-task-lib-reproduce

**Comment by damccorm** [comment]
I'm no longer able to reproduce - is this still an issue for you?

**Comment by damccorm** [comment]
I'm going to close, please reopen if appropriate.
