### ISSUE TITLE
Add support for retrieving secure file variables to the PowerShell SDK

### ISSUE THREAD

**Issue by chelnak** [Microsoft/azure-pipelines-task-lib#270]
It would be great if we could access SECUREFILE_* variables via the sdk. The main function for this would be to obtain the download ticket for a secure file and pass it to a custom helper function.

I can see that the correct env variables are being added to the vault hashtable here:

https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/VstsTaskSdk/InputFunctions.ps1#L360

but there doesn't appear to be support for retrieving them.

An implimentation along the lines of this could work:

```
<#
.SYNOPSIS
Gets a secure file download ticket

.DESCRIPTION
Gets a secure file download ticket

.PARAMETER Id
The id of the secure file

#>
Get-SecureFileTicket {
    [CmdletBindin()]
    Param(
        [Parameter(Mandatory = $true)]
        [string]$Id
    )

   $Key = "SECUREFILE_TICKET_$Id"
   $Description = Get-LocString -Key PSLIB_Input0 -ArgumentList $Id
   Get-VaultValue -Description $Description -Key $Key
}
```

**Comment by TechnologyAnimal** [comment]
Im looking for this too.

**Comment by melborp** [comment]
Hi,
I am also looking into ways to access securefiles from powershell. Any update on this?

**Comment by ericsciple** [comment]
@madhurig

**Comment by ericsciple** [comment]
otherwise I would welcome a PR if it follows the patterns set forth in the ps lib, and unit tests. The lib written in node has the details about the env vars.

**Comment by mmajcica** [comment]
In the version 0.11 of the SDK this was added. @ericsciple  or @madhurig you can close this.

**Comment by damccorm** [comment]
Closing since it looks like this has been resolved.
