### ISSUE TITLE
ToolRunner should respect empty string args

### ISSUE THREAD

**Issue by t-jakurl** [microsoft/azure-pipelines-task-lib#277]
To un-deprecate a package in npm you're supposed to leave the message string blank. 

When this is done in the npm task it throws an error since it expects a message, but it doesn't receive one. To repro this bug, create a build with two consecutive npm custom command tasks. The first command should be "deprecate <pkg>@<version> "message" ", the second should be "deprecate <pkg>@<version> "" ". 

The problem is in the toolrunner class, specifically _argStringToArray. It should parse two consecutive double-quotes into an empty string, but instead it ignores it.  By adding a check for two consecutive quotes at line 43 this can be avoided.

**Comment by damccorm** [comment]
Added a PR to address this.
