### ISSUE TITLE
Running vsts-tasks task test fails if task is referencing lib version 2.1.0 

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/azure-pipelines-task-lib#285]
STDERR
STDOUT ##vso[task.debug]agent.TempDirectory=C:\agent\_temp
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Unhandled: ENOENT: no such file or directory, open 'C:\agent\_temp\.taskkey'
##vso[task.complete result=Failed;]Unhandled: ENOENT: no such file or directory, open 'C:\agent\_temp\.taskkey'

**Comment by stephenmichaelf** [comment]
@bishal-pdMSFT Are you still having this issue?

**Comment by bishal-pdMSFT** [comment]
@stephenmichaelf I haven't tried this recently and most probably won't be trying for next few weeks.

**Comment by stephenmichaelf** [comment]
@bishal-pdMSFT Thanks for the heads up. I am going to close, can you reopen if you still have this issue when you try again? Thanks!

**Comment by omeshp** [comment]
@stephenmichaelf We noticed that below two releases failed because of this issue, hence reopening.
https://microsoftit.visualstudio.com/3d1a556d-2042-4a45-9dae-61808ff33d3b/_release?definitionId=2028&releaseId=291270&_a=release-logs
https://microsoftit.visualstudio.com/3d1a556d-2042-4a45-9dae-61808ff33d3b/_release?definitionId=2028&releaseId=288685&_a=release-logs

**Comment by stephenmichaelf** [comment]
Thanks @omeshp I will take a look!

**Comment by bryanmacfarlane** [comment]
The links above are not available anymore.  Let us know if you can repro with 2.5

**Comment by jepetty** [comment]
Any update on this? I'm hitting this problem on v2.7.7

**Comment by damccorm** [comment]
@jepetty could you share more info on the definition you're seeing this in? I can't repro on my end

**Comment by damccorm** [comment]
Any chance its stemming from this issue - https://github.com/Microsoft/azure-pipelines-task-lib/issues/372

I think that's caused similar errors in the past

**Comment by jepetty** [comment]
@damccorm thanks for the quick response! I have a build task that is using `task.getVariable('Agent.TempDirectory')` to use the agent's temp directory. 

At the beginning of tests for this task, I set the temp directory using `process.env['AGENT_TEMPDIRECTORY'] = 'c:\\tmp';`
##vso[task.debug]agent.TempDirectory=c:\tmp
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Unhandled: ENOENT: no such file or directory, open 'c:\tmp\.taskkey'
##vso[task.complete result=Failed;]Unhandled: ENOENT: no such file or directory, open 'c:\tmp\.taskkey'

I don't believe it's related to `task.getInput` as I'm not using that method. Do I have to mock `task.getVariable` for this case?

**Comment by damccorm** [comment]
That's probably your best bet. Our way of loading data is currently broken when the TEMPDIRECTORY is set. I'm hoping to get a fix in for that soon though.

**Comment by damccorm** [comment]
I'm going to close here since this is really just another manifestation of #372, I'll link to this conversation there as well.
