### ISSUE TITLE
Having a dot in a task variable name is not supported

### ISSUE THREAD

**Issue by henryju** [microsoft/azure-pipelines-task-lib#303]
In a task, if you save a variable with a dot in its name, it will be replaced by a '_'.
`tl.setTaskVariable('foo.bar', 'value');`
https://github.com/Microsoft/vsts-task-lib/blob/a4be3729c2416c90fc6876902eb60e5e062d7c63/node/internal.ts#L260

But when trying to read this variable back, the dot is not replaced, so the value is not found.
`tl.getTaskVariable('foo.bar');`
https://github.com/Microsoft/vsts-task-lib/blob/a4be3729c2416c90fc6876902eb60e5e062d7c63/node/task.ts#L420

**Comment by stephenmichaelf** [comment]
Thanks for letting us know @henryju ! I will take a look.

**Comment by damccorm** [comment]
Added a PR to address this

**Comment by bender2k14** [comment]
@damccorm, can you link to your PR?

**Comment by damccorm** [comment]
https://github.com/microsoft/azure-pipelines-task-lib/pull/414

**Comment by bender2k14** [comment]
Oh, I see the automatically added link above now.  Sorry for the trouble :/
