### ISSUE TITLE
Use defined endpoint data sources from tasks

### ISSUE THREAD

**Issue by jsalado** [microsoft/azure-pipelines-task-lib#353]
## Question
Is there a way to use the defined endpoint data sources in the extension manifest from task's TypeScript code? does the task library support this?

My case is that I need to call the rest service defined in the endpoint from the task. What I've seen so far is that the data sources are mainly used to populate pick lists in the task definition screens.

Since the endpoints of the rest service can be defined in the extension manifest and I can access some of that info from the task (URL, authentication). I was wondering if there is a way to call the external rest service with a simple call in the task lib (I haven't seen anything in the task lib docs). I would be a nice feature if it is not possible now.

Can you confirm if the alternative now is, for example, to build the call to the external rest service in the task and use the node.js request to make the call?

Thanks,
J.

**Comment by omeshp** [comment]
@jsalado Task lib currently doesn't have any such functionality though i agree it will be good to have. Currently the two options are to use [Execute Service Endpoint Request](https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/endpointproxy/execute%20service%20endpoint%20request?view=vsts-rest-5.0) rest API or to call the external rest API directly in task as you mentioned.

**Comment by kiuwan** [comment]
@omeshp Thank you for your answer. I'll try to do everything in the task code then as you suggest.

Do you think the task lib will support using the endpoint datasource definitions any time soon. How can I open a feature request fo it?

Best,
J.

**Comment by jsalado** [comment]
@omeshp Thanks for your answer.
I'll implement the call in the task code as you say.
Is the enhancement going to be developed any time soon? How can I open a feature request for it?
Best,
J.

**Comment by omeshp** [comment]
@GitHubSriramB Can you add this request to backlog, if not already present?

**Comment by jsalado** [comment]
ANy news on this?
