### ISSUE TITLE
Self-associated build artifacts not getting deleted when deleting build

### ISSUE THREAD

**Issue by alexiffland** [Microsoft/azure-pipelines-task-lib#367]
I'm using the PowerShell-API with version 0.11.0 of the sdk. 

When associating a filepath as a build-artifact via 
` Write-VstsAssociateArtifact -Name $buildNumber -Path $destination -Type "filepath"`
, the created folder ($destination) does not get deleted when deleting the build which belongs to the artifact. 

I also tried running 
`Write-Host "##vso[artifact.associate type=filepath;artifactname=$buildNumber]$destination"`
but the outcome was the same.

Associating a filepath with the default _PublishBuildArtifacts_ buildtask works fine and deletes the associated folder, when deleting the corresponding build.

Do I miss something here or is it supposed to only work with the default  _PublishBuildArtifacts_ buildtask?

Thanks,
Alex

**Comment by damccorm** [comment]
This isn't something controlled by this repo, the [agent repo](https://github.com/Microsoft/azure-pipelines-agent) dictates this behavior (I think). @TingluoHuang is this expected?

**Comment by damccorm** [comment]
I'm going to close here since its not an issue for this library. If you're still interested in this, please log an issue in https://github.com/microsoft/azure-pipelines-agent/issues
