### ISSUE TITLE
[Feature Request] Release Definition

### ISSUE THREAD

**Issue by mrichins** [Microsoft/azure-pipelines-task-lib#369]
Being able to define builds in yml files is a huge improvement for defining the process for the company I am working with now. It lets us version control and standardize (maybe someday generate!) build definition configurations for multiple teams. Also keeping the version within a team's repository encourages collaborative ownership of the build process. However, the benefits dry up as soon as we start looking to apply the same principles to release definitions.

Is this a feature on the product roadmap? Am I missing an equivalent functionality elsewhere?

**Comment by ericsciple** [comment]
yep this is on the roadmap

**Comment by stephenmichaelf** [comment]
Going to close this as the work is not tracked in the task lib. Adding releases to yaml is in progress as a feature for the entire product.
