### ISSUE TITLE
Task hangs in case of creating new process inside the power-shell script!

### ISSUE THREAD

**Issue by AhmedAbdohOrtiga** [Microsoft/azure-pipelines-task-lib#376]
My custom build task hangs only in VSTS build
in my power-shell script I create a new process that executes some .exe file
but once I start the process it hangs and never ends (only in VSTS, locally in windows it works fine)

I tried to change the .exe to .dll and it works fine in both VSTS and windows 

Here is sample for the code
1- In case of exe (**which hangs**)

```
[System.Reflection.Assembly]::LoadFrom("App1.dll")
$psi = New-object System.Diagnostics.ProcessStartInfo 
$psi.CreateNoWindow = $true 
$psi.UseShellExecute = $false 
$psi.RedirectStandardOutput = $true 
$psi.RedirectStandardError = $true 
$psi.FileName = "App2.exe"
$psi.Arguments = @($arguments)
$process = New-Object System.Diagnostics.Process 
$process.StartInfo = $psi 
-Start "App2.exe"
[void]$process.Start()
-Hangs after I call start and goes in infinite loop here
$output = $process.StandardOutput.ReadToEnd() 
$process.WaitForExit() 
Write-Host $output
-Assume I'm calling function1 inside "App1.dll" 
[App1.NameSpace.Class]::Function1()
```

2- In case of changing the "App2.exe" to "App2.dll" (**works fine**)
```
[System.Reflection.Assembly]::LoadFrom("App1.dll")
[System.Reflection.Assembly]::LoadFrom("App2.dll")
[App2..NameSpace.Program]::Main(@($arguments)
[App1.NameSpace.Class]::Function1()

```
I've tried all agent pools and still hangs every time but still couldn't figure out what's the issue when I try to use .exe file or when I try to create new process, because it works fine while I'm testing locally from windows power-shell.

**Comment by damccorm** [comment]
@AhmedAbdohOrtiga is this still an issue for you? It definitely is possible to start processes with an exe in general so there's probably something else going on here (for an example of this working, look [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/1d75fa8f66aa1cf7a9cb62946939f30f087b2969/Tasks/DeployVisualStudioTestAgentV2/CreateOfflineTestAgent.ps1#L17)). I don't see anything that's glaringly wrong though.

A little more info about App2.exe/dll would be helpful as well - do you know if its actually entering the App2 code and getting hung up there or if its not even executing any of that code? Also can you provide any info about what App2 is doing? Is it spawning any child processes? It could be related to #389
