### ISSUE TITLE
Include support for Node 8.7+

### ISSUE THREAD

**Issue by lkillgore** [Microsoft/azure-pipelines-task-lib#380]
Using Node ~8.7+ prints warnings like: `(node:37380) Warning: Use Cipheriv for counter mode of aes-256-ctr`

Because the cipher is hardcoded [here](https://github.com/Microsoft/vsts-task-lib/blob/1195328c3ab17a17a75360015e230193177c4981/node/vault.ts#L8) to an algorithm that later versions of Node warn against.

**Comment by damccorm** [comment]
Added a PR to address this.
