### ISSUE TITLE
Command arguments Quotations not visible in Linux agent logs

### ISSUE THREAD

**Issue by vithati** [Microsoft/azure-pipelines-task-lib#383]
I am using docker run task to execute a one liner script in a container just build in the pipeline. The idea is to execute:

docker run -t my-container sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out"

So I set up a docker run task and pass sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out" in the field Command.

To my surprise, the double quotes disappear and there fore the actual command executed by the agent is (from the task output)

docker run -t my-container sh -c ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out 

There is no failure in executing command, just quotation not visible in logs. 

In windows agent, logs showing properly. docker run -t my-container sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out"

**Comment by vithati** [comment]
I looked at code  https://github.com/Microsoft/vsts-task-lib/blob/f22b24bd393becbb370b95f394e3f2cdcc823964/node/toolrunner.ts , looks like for linux, quotations not handled like windows.

**Comment by damccorm** [comment]
I can't say for sure, but if you are passing that in as a string it could be an issue with [_argStringToArray](https://github.com/Microsoft/azure-pipelines-task-lib/blob/f22b24bd393becbb370b95f394e3f2cdcc823964/node/toolrunner.ts#L83). If so, passing something like docker run -t my-container sh -c ```"\"ls .Test/.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out\""``` should solve it. Right now, it sees that you have quotes and thinks that you just want to avoid splitting it up into different args (which I assume is true). Escaping should fix that.

If that doesn't resolve it, I'll take a deeper look - I'm somewhat confused as to why it would work with Windows and not Linux

**Comment by damccorm** [comment]
I'm going to close, please reopen if appropriate.

**Comment by beatcracker** [comment]
> I'm going to close, please reopen if appropriate.

I'm not sure if it's the right place to report this, but escaping seems to be inconsistent:

Here is the Docker task I'm using in the classic release pipeline:

- UI

![image](https://user-images.githubusercontent.com/7583050/73366908-bde04600-42bf-11ea-81f0-a021799a441e.png)

- YAML

```
steps:
- task: Docker@2
  inputs:
    command: run
    arguments: '{\"version\": \"$(Build.BuildNumber)\"}'
```



As you can see, I'm trying to pass a JSON as string (all other arguments are omitted for clarity) and it's not escaped correctly when task is run:

```
[command]/bin/docker run {\version": "1.2.3"}
/bin/docker: invalid reference format.
```
