### ISSUE TITLE
Background process can hold onto streams, causing jobs to not finish

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/azure-pipelines-task-lib#389]
On Linux, the test agents hang indefinitely under the following conditions:

* A main process is launched by the agent 
* Main process launches a new process which inherits the handles of the main process
* Main process exits before the child process

See https://github.com/natemcmaster/repro-vsts-stdout-blocking

We talked about addressing this by watching a couple of Node events and, if some threshold of time elapses between them, letting the user know what's happening. Optionally we could fulfill the promise so Node forcibly returns.

**Comment by nigurr** [comment]
@ericsciple We are also facing the same issue in test execution task. If test code leaves any stale process (typically chrome driver), we end up hitting task timeout in the end even though test execution is completed.

**Comment by ericsciple** [comment]
fixed with commit 800dadcce45aee0b5bd64f293292fe3177c06362 (forgot to close this issue)
