### ISSUE TITLE
Export "Write-LoggingCommand" for Powershell lib

### ISSUE THREAD

**Issue by KennyTangHK** [microsoft/azure-pipelines-task-lib#395]
Currently, the Powershell lib doesn't export the `Write-LoggingCommand` which Node.js lib does.

```
// https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L474
export const command = im._command;
```

It seems the only way to achieve functions like the following is to write the `##vso[]` string manually.
```
// https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L1717
command('results.publish', properties, '');
command('codecoverage.publish', properties, "");
```

The `Write-LoggingCommand` should be exported so that the same functions can be achieved.

**Comment by stephenmichaelf** [comment]
@ericsciple
