### ISSUE TITLE
Azure pipelines github app endpoint connection

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/azure-pipelines-task-lib#400]
Hi everyone,

I'm having some troubling with the new Azure Pipelines app for GitHub while trying to get the Endpoint.

It returns a new type of parameters as you can see here https://github.com/marceloavf/github-tools-vsts/issues/29. I tried to check for some documentation but didn't find anything. IIs there somewhere to ask about this problem or get some information?

Here is a piece of the code that get it:

```js
const tl = require('vsts-task-lib/task')

const githubEndpoint = tl.getInput('githubEndpoint')
const githubEndpointObject = tl.getEndpointAuthorization(githubEndpoint)

if (githubEndpointObject.scheme === 'PersonalAccessToken') {
  githubEndpointToken = githubEndpointObject.parameters.accessToken
} else if (githubEndpointObject.scheme === 'OAuth') {
  githubEndpointToken = githubEndpointObject.parameters.AccessToken
} else if (githubEndpointObject.scheme === 'Token') {
  // Azure Pipeline
  githubEndpointToken = githubEndpointObject.parameters.Signature
}
```

Thank you!

**Comment by damccorm** [comment]
It looks like this isn't an issue with this library, its an issue with the app backend. It is also being tracked in https://github.com/marceloavf/github-tools-vsts/issues/29 so I'm going to close here. Please reopen if appropriate. Please reopen if appropriate.
