### ISSUE TITLE
How to locate tool referenced in .csproj using DotNetCliToolReference?

### ISSUE THREAD

**Issue by Liero** [Microsoft/azure-pipelines-task-lib#403]
Let's say I want to invoke some CLI command that is defined in .csproj like this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <DotNetCliToolReference Include="SomeCliTool" Version="4.1.0" />
  </ItemGroup>
</Project>
```

Now, I would like to invoke the tool.

```typescript
import tl = require('vsts-task-lib/task');
const pathToCliTool = tl.withMsbuild('./MyWebApplication.csproj').which('someclitool')
await ts.tool(pathToCliTool).exec();
```

**Comment by damccorm** [comment]
I don't think I fully understand what you're trying to do. Why are you trying to accomplish by using 'withMsbuild'? The which function should be run directly on tl.

Could you provide more details on the issue you're facing?

**Comment by Liero** [comment]
`tl.which('some-cli-tool-referenced-with-nuget')` does to recognize the tool, since it is not globally installed. If I'm not mistaken...

**Comment by damccorm** [comment]
Ok, so if I understand correctly, you have the tool installed somewhere, but not globally, and you need a way to find the path to tool?

I think what you might need is findMatch, theres some good documentation on this stuff [here](https://github.com/Microsoft/azure-pipelines-task-lib/blob/b9602e028255065aed92c64fa5c07f235542b1bc/node/docs/findingfiles.md). Still not 100% sure I'm answering your question though. What are you trying to do with the 'withMsbuild' function?

**Comment by damccorm** [comment]
I'm going to close, please reopen if appropriate.

**Comment by Liero** [comment]
Sorry, I forgot this issue.

Well, findMatch doesn't find it.

The thing is, that the tools is downloaded by nuget.exe somewhere (I don't now where) and it is possible to use it via Visual Studio's Package Manager Console (PowerShell with some extra paths).

However, I would like to invoke the tool in my build task. 

Maybe somebody from msbuild or nuget team could help....


PS: There is no reopen button

**Comment by damccorm** [comment]
> Well, findMatch doesn't find it.

This still seems to me like a case where findMatch should be used (and if its not working that feels like a bug). How have you tried to use it?

**Comment by damccorm** [comment]
@Liero any update on this - specifically could you provide a little more info on how you're trying to use findMatch?

**Comment by Liero** [comment]
I disvovered  that the tool I wanted to use (LibMan) works only when globally installed and doesn't work with `DotNetCliToolReference`, so this issue is not valid anymore. Thanks
