### ISSUE TITLE
Failed find: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by henryju** [Microsoft/azure-pipelines-task-lib#408]
vsts-task-lib 2.4.0
My task is looking for a file produced during the build. I know the name of the file (report-task.txt), but not its location. So I'm using:
```
tl.findMatch(
  tl.getVariable('Agent.BuildDirectory'),
  path.join('**', 'report-task.txt')
);
```
Unfortunately, when there are too many files in the build directory, it fails with:
```
2018-09-20T09:14:03.3401724Z ##[debug]Agent.BuildDirectory=C:\vsts-agent\agent\_work\2
2018-09-20T09:14:03.3401908Z ##[debug]defaultRoot: 'C:\vsts-agent\agent\_work\2'
2018-09-20T09:14:03.3402086Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2018-09-20T09:14:03.3402256Z ##[debug]findOptions.followSymbolicLinks: 'true'
2018-09-20T09:14:03.3402421Z ##[debug]matchOptions.debug: 'false'
2018-09-20T09:14:03.3402581Z ##[debug]matchOptions.nobrace: 'true'
2018-09-20T09:14:03.3402741Z ##[debug]matchOptions.noglobstar: 'false'
2018-09-20T09:14:03.3402899Z ##[debug]matchOptions.dot: 'true'
2018-09-20T09:14:03.3403057Z ##[debug]matchOptions.noext: 'false'
2018-09-20T09:14:03.3403299Z ##[debug]matchOptions.nocase: 'true'
2018-09-20T09:14:03.3403458Z ##[debug]matchOptions.nonull: 'false'
2018-09-20T09:14:03.3403624Z ##[debug]matchOptions.matchBase: 'false'
2018-09-20T09:14:03.3403783Z ##[debug]matchOptions.nocomment: 'false'
2018-09-20T09:14:03.3403946Z ##[debug]matchOptions.nonegate: 'false'
2018-09-20T09:14:03.3404108Z ##[debug]matchOptions.flipNegate: 'false'
2018-09-20T09:14:03.3404265Z ##[debug]pattern: '**\report-task.txt'
2018-09-20T09:14:03.3408591Z ##[debug]findPath: 'C:\vsts-agent\agent\_work\2'
2018-09-20T09:14:03.3408807Z ##[debug]statOnly: 'false'
2018-09-20T09:14:03.3410070Z ##[debug]findPath: 'C:\vsts-agent\agent\_work\2'
2018-09-20T09:14:03.3410294Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2018-09-20T09:14:03.3410479Z ##[debug]findOptions.followSymbolicLinks: 'true'
2018-09-20T09:14:03.3413368Z ##[debug]  C:\vsts-agent\agent\_work\2 (directory)
[...] (many files)
2018-09-20T09:14:09.9229553Z ##[debug][SQ] Publish task error: Failed find: Maximum call stack size exceeded
2018-09-20T09:14:09.9229867Z ##[debug]task result: Failed
2018-09-20T09:14:09.9230850Z ##[error]Failed find: Maximum call stack size exceeded
2018-09-20T09:14:09.9231251Z ##[debug]Processed: ##vso[task.issue type=error;]Failed find: Maximum call stack size exceeded
2018-09-20T09:14:09.9231740Z ##[debug]Processed: ##vso[task.complete result=Failed;]Failed find: Maximum call stack size exceeded
```

Would it be possible to fix the behavior?

**Comment by henryju** [comment]
Yep.

**Comment by henryju** [comment]
2. the build directory is big because there are node_modules in many places of this project.
3. we don't control the content, since this is the entire user build directory. Cycles can only come from symbolic links right?
4. We could indeed ignore symlinks. But I have the entire log, and I don't see any cycle. Just a lot of files processed (~ 73k when it fails). Still the issue is likely to come from cycle detection (maybe https://github.com/Microsoft/azure-pipelines-task-lib/blob/800dadcce45aee0b5bd64f293292fe3177c06362/node/task.ts#L852). Since disabling symlinks will disable cycle detection, it should be fine for us.

Thanks

**Comment by damccorm** [comment]
Yeah, cycles can only come from symlinks (without symlinks all edges in the generated tree can be considered to be directed deeper into the directory structure), so disabling them should probably work. In addition, disabling symlinks will most likely greatly reduce the longest path in the generated tree.

Looking at the cycle detection itself, I'm pretty sure its not actually broken, and I don't see a whole lot of room to make this algorithm more space efficient. There's probably ways to better optimize for setups depending on if they have dense or sparse symlinks (I'd assume most setups of interest are sparse), but I don't see that changing the overall complexity in any significant way. I think the takeaway here is that once you reach a certain size, particularly if you have a lot of symlinks, you need to ignore symlinks.

I'm going to close, feel free to reopen if you have additional thoughts though!

**Comment by dpurge** [comment]
I am hit by the SonarQube bug that is not resolved, caused by this vsts-task-lib bug: https://jira.sonarsource.com/browse/VSTS-172

I have copied the source directory as it looked like when their publish task starts working.

Then I have replicated the problem by running this JavaScript:

```
var tl = require("D:/Build/snip/_work/_tasks/SonarQubePublish_291ed61f-1ee4-45d3-b1b0-bf822d9095ef/4.6.0/node_modules/vsts-task-lib/task");
tl.findMatch(
  'D:/Build/snip/_work/3-backup',
  '**/report-task.txt');
```

The error was this:

```
(...snip...)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod98 (directory)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod99 (directory)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\report-task.txt (file)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report (directory)
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Unhandled: Failed find: Maximum call stack size exceeded
##vso[task.complete result=Failed;]Unhandled: Failed find: Maximum call stack size exceeded
```

Then I wanted to know if changing the default for findOptions would fix it. Here is the code:

```
var tl = require("D:/Build/snip/_work/_tasks/SonarQubePublish_291ed61f-1ee4-45d3-b1b0-bf822d9095ef/4.6.0/node_modules/vsts-task-lib/task");
tl.findMatch(
  'D:/Build/snip/_work/3-backup',
  '**/report-task.txt',
  { followSymbolicLinks: false });
```

It did not help. Same error:

```
(...snip...)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod97 (directory)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod98 (directory)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod99 (directory)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\report-task.txt (file)
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report (directory)
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Unhandled: Failed find: Maximum call stack size exceeded
##vso[task.complete result=Failed;]Unhandled: Failed find: Maximum call stack size exceeded
```

IMHO you should reopen this bug.  The workaround you mentioned does not seem to work.

**Comment by damccorm** [comment]
I can reopen, I'm not really sure if there's anything I can do here though without a little more info - nothing stands out to me as wrong here, I think there's just not enough memory to handle [the stack](https://github.com/Microsoft/azure-pipelines-task-lib/blob/97f225f48b023be729098e66187376840b2e3a04/node/task.ts#L846) being used.

With that said, I'm happy to take a look, but it would be helpful if you could try to debug a little bit to give me a starting point (maybe add some logging statement in the task module you're importing). I haven't gotten a repro.

**Comment by dpurge** [comment]
I can try to provide more information, but I need some guidance how to gather it - I am not familiar with JavaScript development. I have tried to run my script with `node inspect`, stepped to the exception and run backtrace. Not sure whther this helps you in any way:

```
(...snip...)
< ##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\mod99 (directory)
< ##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\report-task.txt (file)
< ##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report (directory)
break in internal/modules/cjs/loader.js:540
 538     threw = false;
 539   } finally {
>540     if (threw) {
 541       delete Module._cache[filename];
 542     }
debug> bt
#0 tryModuleLoad internal/modules/cjs/loader.js:540:4
#1 Module._load internal/modules/cjs/loader.js:529:2
#2 Module.runMain internal/modules/cjs/loader.js:741:11
#3 startup internal/bootstrap/node.js:285:18
#4 bootstrapNodeJSCore internal/bootstrap/node.js:739:2
debug>
```

Unfortunately I cannot share with you the workspace, but if you can write a script that would print out more useful error message, I can run it in this workspace and comment out any confidential info.

**Comment by damccorm** [comment]
I think the easiest way to debug here is to just add some `console.log` statements in the JS file you're requiring (`"D:/Build/snip/_work/_tasks/SonarQubePublish_291ed61f-1ee4-45d3-b1b0-bf822d9095ef/4.6.0/node_modules/vsts-task-lib/task.js"`). You could try one of the debugging tools that exist out there, but this should be relatively low friction

**Comment by dpurge** [comment]
I can do that. The error is in the find() function.
What kind of info should I log?
For test, I have logged the stack.length (`console.error("Stack length: " + stack.length)`):
```
Stack length: 2530
Error: Failed find: Maximum call stack size exceededStack length: 2530
Error: Failed find: Maximum call stack size exceeded
```

I will play with it a bit and will report here if I find anything of interest, but let me know what would you be interested in?

It's getting late here, so I will probably continue investigation tomorrow morning.

**Comment by damccorm** [comment]
Ok thanks, that's helpful. It doesn't seem like a stack of that size should be causing those sorts of issues.

Another thing that could be helpful is printing out the `FindOptions` passed in to make sure they're actually what we think they are. Also, maybe try setting the `followSpecifiedSymbolicLink` option to false along with `followSymbolicLinks`. I don't think that's causing issues, but it could help to eliminate it as a possibility.

**Comment by dpurge** [comment]
I've logged the length of childItems at the moment when they are pushed onto stack (`stack.push.apply(stack, childItems.reverse());`) and raise an error:

```
Child items length: 127295
Options:
{ followSpecifiedSymbolicLink: true, followSymbolicLinks: true }
```
In the cases when there is no error, `childItems.length` is '0'

Here goes the run with non-default parameters:

```
##vso[task.debug]  D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report (directory)
Child items length: 127295
Options:
{ followSpecifiedSymbolicLink: false,
  followSymbolicLinks: false }
Error: Failed find: Maximum call stack size exceeded
```

To me, it seems like calling the apply on 127295 childItems is a problem.

I have logged them out, here is the sample:

```
 _FindItem {
    path:
     'D:\\Build\\snip\\_work\\3-backup\\.sonarqube\\out\\.sonar\\scanner-report\\changesets-10586.pb',
    level: 6 },
  _FindItem {
    path:
     'D:\\Build\\snip\\_work\\3-backup\\.sonarqube\\out\\.sonar\\scanner-report\\changesets-10587.pb',
    level: 6 },
  _FindItem {
    path:
     'D:\\Build\\snip\\_work\\3-backup\\.sonarqube\\out\\.sonar\\scanner-report\\changesets-10588.pb',
    level: 6 },
  ... 127195 more items ]
```

**Comment by damccorm** [comment]
Yeah, that's [almost certainly the issue here](http://2ality.com/2014/04/call-stack-size.html). So then I guess there's a couple questions:

1) Is that legitimate (aka are there actually 127295 children in `D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report`)? My guess is that it probably is correct since its just relying on node's built in `fs` library.

2) Is there a good way around this. I think that this is just a limitation on the stack size allowed, and there's not a more space-efficient way to traverse a tree than this (just a simple DFS) without getting kinda ugly and losing time-efficiency. With that said, its possible that the reverse or apply are actually what's causing issues here. The last thing I'd ask you to try is taking out the reverse call and just doing:

```
for (var i = childItems.length - 1; i >= 0; i--) {
   stack.push(childItems[i]);
}
```

If that doesn't work I'll need to think a little bit more about possible solutions/tradeoffs

**Comment by dpurge** [comment]
Ad. 1)
The number of files in the `scanner-report` directory is correct:

```
PS C:\snip> Get-ChildItem D:\Build\snip\_work\3-backup\.sonarqube\out\.sonar\scanner-report | measure
Count    : 127295
```

Ad. 2)
Patched code does not throw errors. Code:

```
//stack.push.apply(stack, childItems.reverse());
for (var i = childItems.length - 1; i >= 0; i--) {
    stack.push(childItems[i]);
}
```

Output:

```
##vso[task.debug]370009 results
##vso[task.debug]found 370009 paths
##vso[task.debug]applying include pattern
##vso[task.debug]adjustedPattern: 'D:\Build\KBNDVTBS68-01\_work\3-backup\**/report-task.txt'
##vso[task.debug]1 matches
##vso[task.debug]1 final results
```

I am about to run SonarQube with the patched library to see whether it can be used as a workaround.

**Comment by dpurge** [comment]
I can also confirm that the above patch fixes the SonarQube's Publish Results task.

**Comment by damccorm** [comment]
Great! Thanks for helping me debug this. I'll add a PR to fix this.
