### ISSUE TITLE
powershell/VstsTaskSdk/ToolFunctions.ps1:113 - error with Pipelines

### ISSUE THREAD

**Issue by MSP-Greg** [microsoft/azure-pipelines-task-lib#410]
Getting an error when running in a Pipelines script at [`powershell/VstsTaskSdk/ToolFunctions.ps1:113`](https://github.com/Microsoft/vsts-task-lib/blob/0b96551bd24bc693cdf57552d01742f52ce972a5/powershell/VstsTaskSdk/ToolFunctions.ps1#L113)

```
At D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.136.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1:113 
char:13
 
 +         if ($originalEncoding) {
 
 +             ~~~~~~~~~~~~~~~~~
 D:/a/1/s/spec/ruby/library/win32ole/win32ole/ole_method_spec.rb
```

**Comment by ericsciple** [comment]
Can you provide more details? It looks like you are using the Command Line task. What is your batch script doing? If you have a small repro to share, that would help.

**Comment by MSP-Greg** [comment]
Sorry.  A little frustrated.

The project is [here](https://dev.azure.com/MSP-Greg/ruby/_build/results?buildId=178&view=logs), in the make test-spec` step.  the yml is [here](https://github.com/MSP-Greg/ruby/blob/fce968451928aa81e7b8b1904b348e2ad2e6e866/azure-pipelines.yml#L114-L122) & [here](https://github.com/MSP-Greg/ruby/blob/fce968451928aa81e7b8b1904b348e2ad2e6e866/azure-pipelines.yml#L216-L223).

> It looks like you are using the Command Line task

Yes, I'd prefer to use ps, but since the env is not held between steps (unlike Appveyor & Travis), I need to run `vcvarsall.bat` for the vs builds.  I wish there was a `vcvarsall.ps1` file/task/etc...

Thanks, Greg

**Comment by ericsciple** [comment]
If you know the variables you want to export, you can `echo ##vso[task.setvariable variable=<NAME>]<VALUE>`. An example is [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#set-a-job-scoped-variable-from-a-script). The value will be propagated to downstream tasks as environment variables.

**Comment by MSP-Greg** [comment]
@ericsciple

Thanks.  I'm using that, but not for the env set up with `vcvarsall.bat`.   I guess I haven't felt like digging thru a file that I feel MFST should have provided a long time ago.

Regardless, what I've had running on Appveyor for quite a while will not run consistently in pipelines.  Hopefully I'll discover why...

**Comment by ericsciple** [comment]
I just forked your repo. I've never seen an issue with that particular line in the SDK so i'm interested to see what is going on.

**Comment by MSP-Greg** [comment]
Thanks.

You've probably noticed already, but it's the `azure-pipelines` branch, yml is in the root, and there are two ps1 files for setup in the tool folder, `azure_pipeline_prereqs_vc.ps1` & `azure_pipeline_prereqs_mingw.ps1`.

I'm working in it, and since things aren't working, it's kind of a mess.  When I get things stable, I'll be squashing and re-organizing the commits...

The error seems to be happening during tests with the Ruby win32ole std-lib, and there have also been issues with that with the vc builds in Appveyor.

I've been very active with the MSYS2/MinGW builds on Appveyor, but not the vc builds.

Off topic info:

I often try to encourage ruby related repos to build & test on Windows, mostly using the MSYS2/MinGW build tools, which is what publicly available Ruby builds use.

Ruby itself (the original repo I forked) is testing on Appveyor with vc12, vc14, and mingw.  With serial jobs, it's real slow.  With the introduction of pipelines, I thought I could learn how to use pipelines and also speed up the ruby core testing.  Not quite there yet...

**Comment by ericsciple** [comment]
@MSP-Greg I'm honestly a little confused by the error. I think the error coming from the line in the task sdk `if ($originalEncoding) {` is because the timeout is firing, and the task process is getting the CTRL+C signal.

However, I haven't found how to reproduce the issue outside of your build. For example I tried a few different things, like:
```yaml
pool:
  vmImage: vs2015-win2012r2
steps:
- script: |
    ping -n 100 127.0.0.1
  timeoutInMinutes: 1
```

I think the timeout is the real issue, and the message about `$originalEncoding` is a red herring. Unless, the task sdk script is causing the timeout? Like if the output of ruby is somehow causing a problem for the task sdk. I'll poke at it more later this evening. I'll try redirecting the ruby output on that step, to a file instead.

**Comment by ericsciple** [comment]
I got the same result even after redirecting the streams.

```yaml
      - script: |
          PATH=%INSTALL_PATH%
          attrib -r %TMPDIR_W% /d /s
          cd %SRC%\spec\ruby
          ruby --disable=gems ../mspec/bin/mspec -V -f f -T "--disable=gems" 1>$(system.defaultWorkingDirectory)\asdf.log 2>&1
        failOnStderr: false
        timeoutInMinutes: 10
        displayName: $(System.JobName) make test-spec
```

And still got:

```
2018-10-08T04:29:15.5639968Z ##[section]Starting: x64-mswin64_120 make test-spec
2018-10-08T04:29:15.5642993Z ==============================================================================
2018-10-08T04:29:15.5643054Z Task         : Command Line
2018-10-08T04:29:15.5643092Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2018-10-08T04:29:15.5643148Z Version      : 2.136.0
2018-10-08T04:29:15.5643184Z Author       : Microsoft Corporation
2018-10-08T04:29:15.5643222Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2018-10-08T04:29:15.5643294Z ==============================================================================
2018-10-08T04:29:16.5423230Z Generating script.
2018-10-08T04:29:16.6229278Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\809d1978-7c5e-40c4-8fa7-8b0294caa628.cmd""
2018-10-08T04:39:23.0964031Z Terminate batch job (Y/N)? 
2018-10-08T04:39:23.2598060Z Entering debug mode. Use h or ? for help. 
2018-10-08T04:39:23.2598239Z 
2018-10-08T04:39:23.2604133Z At D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.136.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1:113 
2018-10-08T04:39:23.2604315Z char:13
2018-10-08T04:39:23.2604403Z 
2018-10-08T04:39:23.2604457Z +         if ($originalEncoding) {
2018-10-08T04:39:23.2604491Z 
2018-10-08T04:39:23.2604599Z +             ~~~~~~~~~~~~~~~~~
2018-10-08T04:39:25.8147221Z ##[error]The task has timed out.
2018-10-08T04:39:25.8149164Z ##[section]Finishing: x64-mswin64_120 make test-spec
```

The `if ($originalEncoding)` line is in the [finally block](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/VstsTaskSdk/ToolFunctions.ps1#L113). The task calls cmd.exe (that is why Invoke-Tool from the task SDK is being called). The timeout fires (and CTRL+C signal is sent) first, and then the error from the task SDK. I'll run another test tomorrow morning to confirm the ruby process is not exiting before the CTRL+C signal is sent (prove error from task SDK is red herring, since under normal conditions finally would only run after cmd.exe exits).

**Comment by vtbassmatt** [comment]
@vijayma: Eric is going to keep helping with the specific issue here. There's broader feedback for the C/C++ ecosystem, though -- see https://github.com/Microsoft/vsts-task-lib/issues/410#issuecomment-427601267 where it's challenging to find vcvarsall.bat (which, I believe, is required to make the C/C++ toolchain work properly).

**Comment by MSP-Greg** [comment]
> it's challenging to find vcvarsall.bat

Not quite.  The state it creates may need to be maintained across multiple steps, and it can't be easily used with a PowerShell step.  Working mostly with software that is more rooted In GNU/*nix than Windows, I prefer to work with PowerShell, as it (generally) works with both slashes and backslashes.

Maybe have a task that loads env variables needed for the C/C++ toolchain into build/job variables?  $env:path is the unique one...

People vary with how narrow an issue's discussion should be, but this involves a more general issue of how should steps (and the data they generate) function.

I've build versions of OpenSSL with vc12, vc14, & msys2/mingw.  From memory, it's normal log is approx 80k lines.  I consider that unusable.  So, when I first started using pipelines and saw how the step concept was used in the web ui, I liked it.

Some general thoughts:

1. Log Time - absolute Zulu is shown.  I would prefer elapsed, with no more than hundredths of a second resolution.  Appveyor just shows hh:mm:ss.  Also, if one needs to cut & paste a log segment (like here), the absolute time takes up quite a bit of the line width.  Having a start time and end time in the log would be helpful.

2. Download - So there is separation in the UI, but when one downloads the log, one gets one big file.  maybe it should be a zip of files, each named via displayName, along with a numeric prefix for the step number?

3. Logs web ui lacks absolute links.  One can't include a link to a log line in an issue.

4. Test logs may get long.  If the web log UI had go top/go bottom controls it would help.  Make the UI designers navigate it on a standard MacOS/Android tablet.

5. Web UI - Personal issue - it's either inverted color or not.  Some inverted and some not is a pita.  Maybe add a simple control for it...

6. The state issue.  Appveyor & Travis 'steps' are much less integrated into the UI, but state is maintained between them.  I'm not sure what I think a solution would be.

7. I'm still learning, but I can't help but wonder if the overhead of the framework is too high.  Lines like
```
echo "##vso[task.setvariable variable=JOBS]$env:NUMBER_OF_PROCESSORS"
```
scare me.  More later, after I get Ruby parallel testing stable...

Rant off.  Where is the best place for general pipelines issues/thoughts?   I found the 'UserVoice' site, but it seems like it isn't well visited...

Thanks, Greg

**Comment by MSP-Greg** [comment]
Matt,

I email latter, thanks.

> killing runaway or zombie processes

I was going to say that's someone else's problem, but I recall time limits are much greater with pipelines that other services.  Also, in my Ruby master/trunk/head cron job, I had a bit of ps1 code to time limit the test suites in case any of them froze...

**Comment by ericsciple** [comment]
I modified the step to verify CTRL+C is fired before the ruby process finishes. So I think this proves the `$originalEncoding` error is a red herring and the real issue is why is the command timing out.

```yaml
      - script: |
          PATH=%INSTALL_PATH%
          attrib -r %TMPDIR_W% /d /s
          cd %SRC%\spec\ruby
          echo BEFORE CALLING RUBY >$(system.defaultWorkingDirectory)\z_$(system.phaseName)_$(system.jobName).log
          ruby --disable=gems ../mspec/bin/mspec -V -f f -T "--disable=gems" 1>>$(system.defaultWorkingDirectory)\z_$(system.phaseName)_$(system.jobName).log 2>&1
          echo AFTER CALLING RUBY >>$(system.defaultWorkingDirectory)\z_$(system.phaseName)_$(system.jobName).log
          echo AFTER CALLING RUBY >>$(system.defaultWorkingDirectory)\z_$(system.phaseName)_$(system.jobName).log
        failOnStderr: false
        timeoutInMinutes: 10
        displayName: $(System.JobName) make test-spec

      - script: "echo ##vso[task.uploadfile]$(system.defaultWorkingDirectory)\\z_$(system.phaseName)_$(system.jobName).log"
        condition: always()
```

**Comment by ericsciple** [comment]
Is it always a specific test that is hanging? Another option is to try commenting out the hanging test - may help distinguish a bug in the test versus elsewhere

**Comment by MSP-Greg** [comment]
@ericsciple

I messed up my code refactoring, and I've been trying to get the previous test suite (test-all) stable first.

The test suite with the timeout issue is the test-spec suite, and the problems seemed to be with the OLE tests.  One of the Ruby maintainers is trying to fix the VC builds on Appveyor, and he had issues with the test-all OLE tests, but not the test-spec OLE tests.

Also, I patched some of the OLE tests, and now the log times seem to indicate that the task is shutting down the test, versus before, the test was locked or had already shut down.  I think.

Summary: I've got some more changes I want to make to the base code, then I'll get back into concentrating on where this issue is.

Hopefully, once I get some more experience with this, I may actually be able to come up with repro code instead of 'this doesn't work and I have no idea why'...

Sorry, and thanks for the help,  Greg

**Comment by MSP-Greg** [comment]
@ericsciple

I've tried to narrow the scope of things to find the issue.  It may be related to some tests in Ruby that try to create an 'InternetExplorer.Application' object (while testing the Ruby [WIN32OLE](https://msp-greg.github.io/ruby_trunk/win32ole/index.html) std-lib), and this is failing.  Oddly, if the code retries in too short an interval, something hangs.  When I manually stopped it in the UI, I also got the `$originalEncoding` error.  If I increase the retry interval, errors are generated as they should be (?). 

Some of this may be tied into my experimenting with various step parameters, as I haven't quite determined how best to mimic a 'not fast-finish' layout common to Appveyor or Travis.  IOW, I want all steps to run, but any of them can cause the job to be considered as 'failed'...

**Comment by damccorm** [comment]
@MSP-Greg is this still an issue? Were you able to hone in on the issue with any more success?

**Comment by MSP-Greg** [comment]
@damccorm

Been kind of bouncing around with both pipelines and other things.  Give me a few days to revisit...

**Comment by foolip** [comment]
I've run into what is probably the same issue in https://github.com/web-platform-tests/wpt/issues/15174#issuecomment-459341979, with job "all tests (Edge) Job3
" in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5461.

I also use a `script` step, and it's a time-consuming step that will start and restart the Edge browser lots of times.

In [the logs](https://gist.github.com/foolip/55644c814477946b946e43e87ea20299#file-258-txt-L7208-L7218) I see that "Entering debug mode" happens after about 6 hours, so probably when the timeout was reached. Does this mean that this is how the timeout manifests? If so it would be great with a clearer message in this case.

(Probably what has happened is that `./wpt run` has gotten stuck at some point, for reasons still to be debugged.)

**Comment by vtbassmatt** [comment]
@foolip yeah, I think it's just whatever happens to be running when the Ctrl-C gets sent. I wonder if we could inject a log line *before* we send the kill signal. While it wouldn't prevent the weirdness, it would give you a much stronger signal about what happened.

**Comment by foolip** [comment]
Yeah, that would be great.

**Comment by ericsciple** [comment]
@TingluoHuang this sounds like additional logging from agent.worker would be appropriate (not from task lib). Thoughts?

**Comment by damccorm** [comment]
@TingluoHuang have you been able to take a look at this? We should probably move this to the agent repo so it doesn't get lost/forgotten

**Comment by ethomson** [comment]
I'm seeing a similar issue when I'm running my build on a private build agent.  Interesting, the same build works fine on a hosted build agent.

Here's the minimal reproducible script to get this to fail on my private build agent:

```
pr: none

jobs:
- job: Windows
  timeoutInMinutes: 600
  pool: 'wintest'
  steps:
  - checkout: self
    fetchDepth: 2
  - script: |
      set MSYS_PATH=%CD%\citools\msys64
      choco install msys2 --params="/InstallDir:%MSYS_PATH% /NoPath" -y
    displayName: Install msys2
```

What happens is that I will see that the process _appears_ to have finished - the last line of output is printed after only 2-3 minutes _but_ the build job is not finished.  _Eventually_ it will time out and I'll get this same error message.

(Running this command from a shell finishes normally.)

Interestingly, I ran a private build agent on my local machine to see if it failed in the same way (normally, I've been trying this from a headless private build agent).  I was surprised to see that during the `choco install` process, a terminal window pops up!

Not knowing that much about Windows job control, possible that there's a child process that's still running?

(Note that I still have no idea why this would be different between the hosted build agent and my private build agent, and this is a disappointing failure in that case.)

**Comment by ethomson** [comment]
A little bit more digging and doing that same `choco install` in a `Dockerfile` means that `docker build` _also_ hangs forever.  So, it seems like my primary issue is a problem with `choco install`, _but_ a better error message on timeout would be helpful.  (And I hope these repro steps are helpful.)

**Comment by stephenmichaelf** [comment]
@ericsciple @TingluoHuang FYI.

**Comment by ericsciple** [comment]
@thboop fyi

**Comment by ericsciple** [comment]
Thomas is looking into it

**Comment by thboop** [comment]
I wanted to provide a quick update on this item!

When a timeout occurs, we invoke CTRL + C on that instance in order to end the step. If that fails, we invoke CTRL + break, which results in powershell entering debug mode. The text you see below
```
2018-10-08T04:39:23.2598060Z Entering debug mode. Use h or ? for help. 
2018-10-08T04:39:23.2598239Z 
2018-10-08T04:39:23.2604133Z At D:\a\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.136.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1:113 
2018-10-08T04:39:23.2604315Z char:13
2018-10-08T04:39:23.2604403Z 
2018-10-08T04:39:23.2604457Z +         if ($originalEncoding) {
2018-10-08T04:39:23.2604491Z 
2018-10-08T04:39:23.2604599Z +             ~~~~~~~~~~~~~~~~~
```

is the result of executing CTRL + break when running powershell. However the step is failing due to the timeout, and control + c has not managed to exit the process.

As an aside, in the choco example above provided by @ethomson , the choco install has finished executing, but it kicks off a daemon process during the install, resulting in the powershell process never exiting and the step never completing. We are separately looking into how to address that concern. I’ll update this ticket with a link to that item shortly.

**Comment by damccorm** [comment]
I'm going to close here, we can follow up in the linked agent issue since this is really an issue on the agent.
