### ISSUE TITLE
tl.which('toolname') incompatible with dotnet tool install

### ISSUE THREAD

**Issue by lodejard** [Microsoft/azure-pipelines-task-lib#420]
The which function is calling _tryGetExecutablePath, and that function test for the mode bit 001 to determine if a file is executable

https://github.com/Microsoft/vsts-task-lib/blob/de5f350a063ac2e62da225ea469f224524825277/node/internal.ts#L448

That doesn't work if the executable was created by `dotnet tool install` because the resulting mode bits are 744. Here is an example of installing a tool named `atlas`.

```
ls -la /var/lib/vstsagent/1/_work/r2/a/tools
2018-10-12T18:40:53.4814323Z drwxr-xr-x 3 azureuser azureuser   4096 Oct 12 18:40 .
2018-10-12T18:40:53.4814794Z drwxr-xr-x 3 azureuser azureuser   4096 Oct 12 18:40 ..
2018-10-12T18:40:53.4815183Z -rwxr--r-- 1 azureuser azureuser 106912 Oct 12 18:40 atlas
2018-10-12T18:40:53.4815678Z drwxr-xr-x 4 azureuser azureuser   4096 Oct 12 18:40 .store
```

**Comment by damccorm** [comment]
Added a PR for this

**Comment by jmezach** [comment]
This isn't necessarily limited to dotnet global tools, but the same issue occurs when taking the output of dotnet publish, since that only sets the executable bit for the owner, but not for the group or others.

Any updates on this issue? It seems there's a pull request ready to merge?

**Comment by damccorm** [comment]
@ericsciple would you mind reviewing #421 so that we can close here?
