### ISSUE TITLE
Node version must be >=8.0.0 to use this CLI

### ISSUE THREAD

**Issue by dabutvin** [Microsoft/azure-pipelines-task-lib#458]
I keep getting these errors when I upload my extension and run my task.

I've tried a ton of different config, but no luck.

```
2018-10-18T01:20:02.5327327Z WARNING
2018-10-18T01:20:02.5327492Z WARNING Node version must be >=8.0.0 to use this CLI
2018-10-18T01:20:02.5327577Z WARNING Current node version: 6.10.3
2018-10-18T01:20:02.5327634Z WARNING
2018-10-18T01:20:02.5454170Z ##[error]Unhandled: Unexpected identifier
```

I am packaging the task up as part of an extension. See my config files below in the details.
Any help or something you can spot I am missing would be much appreciated!

### vss-extension.json

```json
{
  "manifestVersion": 1,
  "id": "my-extension",
  "publisher": "dabutvin",
  "version": "0.1.12",
  "name": "My Extension",
  "public": false,
  "targets": [
    {
      "id": "Microsoft.VisualStudio.Services"
    }
  ],
  "description": "My Extension",
  "categories": [
    "Pipelines"
  ],
  "icons": {
    "default": "icon.png"
  },
  "files": [
    {
      "path": "mytask"
    }
  ],
  "contributions": [
    {
      "id": "20ab0ddf-554f-4d09-ace6-20a883cff9cf",
      "type": "ms.vss-distributed-task.task",
      "targets": [
        "ms.vss-distributed-task.tasks"
      ],
      "properties": {
        "name": "mytask"
      }
    }
  ]
}

```

---

### mytask/task.json

```json
{
  "id": "20ab0ddf-554f-4d09-ace6-20a883cff9cf",
  "name": "mytask",
  "friendlyName": "My Task",
  "description": "Generates my task output",
  "author": "dabutvin",
  "helpMarkDown": "Generates my task output",
  "category": "Utility",
  "visibility": [
    "Build"
  ],
  "runson": [
    "Agent"
  ],
  "demands": [],
  "version": {
    "Major": "0",
    "Minor": "1",
    "Patch": "12"
  },
  "minimumAgentVersion": "2.122.1",
  "instanceNameFormat": "My Task",
  "groups": [
    {
      "name": "advanced",
      "displayName": "Advanced",
      "isExpanded": false
    }
  ],
  "inputs": [
    {
      "name": "outputlocation",
      "type": "string",
      "label": "Output path",
      "defaultValue": "output.txt",
      "required": false,
      "helpMarkDown": "Where do you want to output the file?"
    },
    {
      "name": "outputFormat",
      "type": "picklist",
      "label": "Output format",
      "defaultValue": "text",
      "required": true,
      "helpMarkDown": "What format do you want to output the file?",
      "options": {
        "text": "Text",
        "html": "Html"
      }
    },
    {
      "name": "additionaldata",
      "type": "filePath",
      "label": "Additional data",
      "defaultValue": "",
      "required": false,
      "helpMarkDown": "A path to additional checked-in data to include in the output"
    }
  ],
  "execution": {
    "Node": {
      "target": "generate.js"
    }
  }
}
```

### mytask/package.json

```json
{
  "name": "my-task",
  "version": "0.1.12",
  "dependencies": {
    "azure-pipelines-task-lib": "^2.7.0"
  },
  "scripts": {
    "build": "tsc -p ."
  },
  "devDependencies": {
    "@types/node": "^10.12.0",
    "@types/q": "^1.5.1"
  }
}

```

### mytask/generate.ts

```js
import tl = require('azure-pipelines-task-lib/task');

async function run() {
  try {

    // do work
    const output = 'Output...'

    if (output) {
      tl.writeFile('output.txt', output)
      tl.setResult(tl.TaskResult.Succeeded, 'generation complete')
    } else {
      tl.setResult(tl.TaskResult.SucceededWithIssues, 'generated empty')
    }
  } catch (err) {
    console.log(err.stack)
    tl.setResult(tl.TaskResult.Failed, err.message)
  }
}

run()

```

**Comment by damccorm** [comment]
Judging from the error, it looks like a tool you're using needs node 8 or above to be installed - are you sure that's installed where you're running it? Have you tried [running the task locally](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/docs/stepbystep.md#run-the-task) with node 8 installed?

**Comment by dabutvin** [comment]
Hi @damccorm thanks for taking a look

It does run locally with node 8 installed.
I'm getting this error running on hosted agents (I tried all of them)

I also tried the node installer task set to 8.x too as a previous step and got the same error.

Is there a way to set the node minimum version somewhere else?

**Comment by damccorm** [comment]
Edited your comment because your files weren't actually showing up for me (the summary/details tags were blocking them and not letting me expand).

That's especially odd that it fails on all of them since at least Ubuntu should have node installed [by default](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md). Are you able to do some debugging and figure out what tool/call is causing this to fail? I don't see any glaring issues with your config files, though I could be missing something as well.

**Comment by dabutvin** [comment]
👍 thanks for fixing that up (I was trying to be helpful lol)

Okay. So I trimmed down a lot to post the config and what is posted above actually works now.
I just went through and set it all again up and tested in and it runs fine.
It is dependent library I installed on top that is causing the problem.

I am importing a library that depends on OCLIF https://github.com/oclif/oclif
And the CLI the error message is referring to is the oclif CLI not the azure-pipelines-task-lib.

This makes more sense, however I'm still not sure what my options are for getting this to work.
Do you have any ideas why the hosted ubuntu agent would be reporting `Current node version: 6.10.3`

**Comment by damccorm** [comment]
@TingluoHuang any clue why the hosted ubuntu agent would be reporting ```Current node version: 6.10.3```?

**Comment by bryanmacfarlane** [comment]
process.versions.node checks the version of node that's running the task.  Not the version of node that's in the path and runs user code.

Tasks in the market place that use "node" execution handler are run by node 6 that the agent carries as a task runnner.  We can't slide that forward as existing market place tasks would break.

Once again, node that runs tasks is a script interpretter which is different than node / npm installed on the box.

**Comment by dabutvin** [comment]
interesting.

thanks for the explanation @bryanmacfarlane 

Maybe I can use the task runner to collect the arguments and write the results, but shell out to use node 8 to do the actual work? Any other ideas?

**Comment by dabutvin** [comment]
I had some luck with shelling out

### index.ts

```js
import tl = require('azure-pipelines-task-lib/task')
import {exec} from 'child_process'
import * as path from 'path'

async function run() {
  try {
    // do work
    console.log(`Index file reports node version: ${process.versions.node}`)
    exec(
      `node ${path.join(__dirname, 'generate.js')}`,
      (err, stdout, stderr) => {
        if (stderr) {
          console.log(`ERROR!: ${stderr}`)
        }
        if (err) throw err
        console.log(stdout)
        tl.setResult(tl.TaskResult.Succeeded, 'generation complete')
      }
    )
  } catch (err) {
    console.log(err.stack)
    tl.setResult(tl.TaskResult.Failed, err.message)
  }
}

run()
```

### generate.ts

```js
async function generate() {
  console.log(`Generate file reports node version: ${process.versions.node}`)
  // do work here
}

generate()
```


This gave me output:

```
2018-10-18T17:39:05.3582126Z Index file reports node version: 6.10.3
2018-10-18T17:39:10.7795339Z Generate file reports node version: 8.12.0
```

It's not ideal, but I can work with this for now. Thanks for the pointer and the quick responses all
