### ISSUE TITLE
Create control similar to Environment Variables 

### ISSUE THREAD

**Issue by knowds** [Microsoft/azure-pipelines-task-lib#460]
I need a control which needs 4 key value pairs similar to as displayed when showenvironmentvaribales is set to true in task.json. How do I achieve the same ?

**Comment by damccorm** [comment]
I'm not sure what you're asking - are you looking for a way to get the environment variables for your own use? Are you looking for something like [getVariables](https://github.com/Microsoft/azure-pipelines-task-lib/blob/9cb1dc3ee70537fd5c67e1a4a247b1a19740a2b4/node/task.ts#L112)?

**Comment by knowds** [comment]
![image](https://user-images.githubusercontent.com/18011456/47199153-d019c780-d38d-11e8-8c59-27c9c7bd1f90.png) 
Need a user control similar to displayed above wherein user should be able to enter multiple key value pairs

**Comment by damccorm** [comment]
Ok gotcha, why can't you just use showEnvironmentVariables? Or are you just asking how to access the environment variables once they're set?

**Comment by knowds** [comment]
I dont't want to use the control to set environment variables. I need to use it to set a different key value pair based on my requirements.

**Comment by damccorm** [comment]
I think I have a better understanding of what you're trying to do, it is currently not supported though. It is being tracked in #48 so I'm going to close here.

**Comment by damccorm** [comment]
Feel free to reopen if appropriate/if you have further questions
