### ISSUE TITLE
Azure DevOps task calling another task

### ISSUE THREAD

**Issue by Evangelink** [Microsoft/azure-pipelines-task-lib#468]
Hi folks!

I am not sure to be on the right place for this question so feel free to redirect me to the correct repo if I am wrong!

We currently provide a couple of specific tasks for [TFS/Azure-DevOps](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud) to run static code analysis.

We would like to provide a task for the specific behavior of our C/C++ analyzer which needs to wrap the call to the build tool (for example msbuild, gcc...) in order to retrieve some specific information required for us to provide a good level of analysis. 

Looking at the different libraries and examples, I haven't been able to identify any way that would allow us to create a task able to trigger another task. Is this some kind of scenario currently supported? If not, is it something you would plan to support?

Cheers,
Amaury

**Comment by damccorm** [comment]
I don't believe that there is a way to trigger one task from another. However, with the concepts of [demands/satisfies](https://github.com/Microsoft/azure-pipelines-tasks/blob/1d75fa8f66aa1cf7a9cb62946939f30f087b2969/docs/tools.md#satisfies) you can ensure that the build tool (e.g. msbuild) is installed. Does that provide what you need here?

**Comment by Evangelink** [comment]
It's not really what I was expecting although I was expecting a "not possible" answer :)

Here is a command line example of how to use our tool (with for example msbuild):
`build-wrapper-win-x86-64.exe --out-dir bw_output MSBuild.exe /t:Rebuild`

We actually need to have the executable to call with all the required arguments so that we can create a sub process and register (using some OS specific API) to some callbacks so that we can capture things like defined macros, include directories, compiler directives...

It seems pointless to try to create a specific task for each build tools we support on which we would duplicate the configurations from the original task that's why I was wondering if there was any built-in (or planned) mechanism we could use to achieve this behavior.

**Comment by damccorm** [comment]
Ok, I think I understand your use case a little bit better. Unfortunately, what you want isn't directly supported, and I don't think its a feature we're going to support (@bryanmacfarlane am I correct on this?). My recommendation would be that you include the build tool name as an arg (and you can also have them define any additional args passed into the tool), begin your task by searching for the tool, and erroring if its not there. This does somewhat rely on the user to do "the right thing", but I think it might be the best option available.
