### ISSUE TITLE
Potential context setup enhancement for TaskMockRunner

### ISSUE THREAD

**Issue by charleszipp** [Microsoft/azure-pipelines-task-lib#469]
I have been working on creating a pipeline task for terraform. While doing so I was trying to figure a good way to make certain parts of my test reusable from test to test. Some examples of what I was trying to share are the answers and input setup. For most tests I need a `which` answer for terraform and I want a `checkPath` of true. Additionally, certain `exec` answers are needed on almost all tests. For example `terraform version` as this is run to verify terraform is installed before each command is run. 

So what i came up with is still setting up mocha spec's as done in the documented examples
```javascript
describe('terraform init', function(){
    it('should succeed', function(){
        let taskRunnerPath = require.resolve('./init-success');
        let testRunner = new MockTestRunner(taskRunnerPath);    
        testRunner.run();
        assert.equal(testRunner.succeeded, true, 'should have succeeded');
        assert.equal(testRunner.errorIssues.length, 0, "should have no errors");
    });
});
```

But the module that contains the setup and execution of TaskMockRunner looks like this..
```javascript
let scenario = new TaskScenario()
    .givenInput(new TerraformCommandAndWorkingDirectory("init"))
    
    .givenAnswer(new TerraformExists())
    .andAnswer((answers) => new TerraformCommandIsSuccessful(answers))
    .andAnswer((answers) => new TerraformCommandWithVarsFileAsWorkingDirFails(answers))
    .run();
```
The classes being instantiated are decorators the author of the task can create to define a step that is used in multiple scenarios. 

Is this something that you feel would be useful as a contribution to this library? If so i can submit a PR to have this framework added to the testing framework.

More examples here...
https://github.com/charleszipp/azure-pipelines-tasks-terraform/tree/master/TerraformCLI/src/tests

**Comment by damccorm** [comment]
I'm not sure I fully understand what you're doing here. Is it basically a way to set a bunch of inputs in the same way? Couldn't you just do something like:

input_file:
```
export inputs = {key1: val1, key2: val2...}
```

TaskMockRunner file:
```
const inputs = require('input_file').inputs;
for (key in inputs) {
   taskRunner.setInput(key, inputs[key]);
}
```

Maybe I'm missing what's going on here, but this seems overdone.

**Comment by charleszipp** [comment]
@damccorm 
If you look at where my tests started and where they ended up after this, you will notice the amount of repetition in not only the boilerplate code but also, references to input names, file paths, and modules across the tests. I was looking for an example of a way of not doing this and I was not able to find one. If you look through the azure-pipelines-tasks github repo, there isnt any consistency there either about how they promote some reuse across different tests. Some do it using environment vars (dotnetcore), some just repeat most of the boilerplate (npm). 

This is even more challenging in that the pattern for testing is completely different than the BDD style testing that frameworks such as Mocha and Jasmine promote is not usable in these tasks. I cant organize my tests into describes such that the same preconditions are reused by nested `describe` and `it` functions.

I have posted examples of what my scenario files looked like before implementing this. The amount of repetition, especially in the boilerplate setup and key string references has been dramatically reduced. Additionally, the step class describe the intent for which they should be used. 

Feel free to close the issue down if you still feel this is not useful. I can make this available in a separate repo & npm package

init-success
```javascript
import ma = require('azure-pipelines-task-lib/mock-answer');
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import path from 'path';

var taskPath = require.resolve('./../index');
let taskRunner: TaskMockRunner = new TaskMockRunner(taskPath);
let workingDirectory = path.resolve("./../TerraformTemplates/sample");
taskRunner.setInput("command", "init");

// azure pipeline will set this to have the value of the working directory even if no value was provided
taskRunner.setInput("varsFile", workingDirectory);
taskRunner.setInput("workingDirectory", workingDirectory);

let a: ma.TaskLibAnswers = {
    which : {
        "terraform" : "terraform"
    },
    checkPath : {
        "terraform" : true
    },
    exec : {
        "terraform version" : <ma.TaskLibAnswerExecResult>{
            code : 0,
            stdout : "version successful"
        },
        "terraform init" : <ma.TaskLibAnswerExecResult>{
            code : 0,
            stdout : "init successful"
        }
    }
};
a.exec = a.exec || {};
a.exec[`terraform init -var-file=${workingDirectory}`] = <ma.TaskLibAnswerExecResult>{
    code : 1,
    stdout : "init failed. working dir provided to -var-file"
}
a.exec[`terraform init --var-file=${workingDirectory}`] = <ma.TaskLibAnswerExecResult>{
    code : 1,
    stdout : "init failed. working dir provided to --var-file"
}
taskRunner.setAnswers(a);
taskRunner.run();
```

validate-success
```javascript
import ma = require('azure-pipelines-task-lib/mock-answer');
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import path from 'path';

var taskPath = require.resolve('./../index');
let taskRunner: TaskMockRunner = new TaskMockRunner(taskPath);
let workingDirectory = path.resolve("./../TerraformTemplates/sample");

taskRunner.setInput("command", "validate");
taskRunner.setInput("varsFile", workingDirectory);
taskRunner.setInput("workingDirectory", workingDirectory);

let a: ma.TaskLibAnswers = {
    which : {
        "terraform" : "terraform"
    },
    checkPath : {
        "terraform" : true
    },
    exec : {
        "terraform version" : <ma.TaskLibAnswerExecResult>{
            code : 0,
            stdout : "version successful"
        },
        "terraform validate" : <ma.TaskLibAnswerExecResult>{
            code : 0,
            stdout : "validate successful"
        }
    }
};
a.exec = a.exec || {};
a.exec[`terraform validate -var-file=${workingDirectory}`] = <ma.TaskLibAnswerExecResult>{
    code : 1,
    stdout : "validate failed. working directory provided to -var-file arg"
}
taskRunner.setAnswers(a);
taskRunner.run();
```

**Comment by damccorm** [comment]
I guess I just don't fully understand why you can't do something similar to what I suggested in my previous comment, e.g.

shared.ts
```
export sharedInputs = {"command": "validate", "varsFile": workingDirectory};
export sharedAnswers = {which: ....}
```
init-success.ts
```
import ma = require('azure-pipelines-task-lib/mock-answer');
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import shared = require('./shared');

var taskPath = require.resolve('./../index');
let taskRunner: TaskMockRunner = new TaskMockRunner(taskPath);

const sharedInputs = shared.sharedInputs;
for (i in sharedInputs) {
   taskRunner.setInput(i, sharedInputs[i]);
}
let a = shared.sharedAnswers;
a.exec['terraform validate'] = {…}
a.exec[`terraform init -var-file=${workingDirectory}`] = {…}
a.exec[`terraform init --var-file=${workingDirectory}`] = {…}
taskRunner.setAnswers(a);
taskRunner.run();
```
validate-success.ts
```
import ma = require('azure-pipelines-task-lib/mock-answer');
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import shared = require('./shared');

var taskPath = require.resolve('./../index');
let taskRunner: TaskMockRunner = new TaskMockRunner(taskPath);

const sharedInputs = shared.sharedInputs;
for (i in sharedInputs) {
   taskRunner.setInput(i, sharedInputs[i]);
}
taskRunner.setInput("workingDirectory", workingDirectory);
let a = shared.sharedAnswers;
a.exec['terraform init'] = {…}
a.exec[`terraform validate -var-file=${workingDirectory}`] = {…}
taskRunner.setAnswers(a);
taskRunner.run();
```

If you wanted, you could also do this with environment variables as you mentioned to give more of a traditional mocha before(), test(), after() sequence. This isn't really any more code than implementing your suggestion, yours just places a little bit of the complexity in any-steps.ts. Overall, I just feel like this is a little overengineered/introduces an unnecessary additional layer of complexity/size.

**Comment by charleszipp** [comment]
Closing this as this probably isn't the best forum to describe the problem. I'll keep isolated to my own project for now and maybe work with CSE-EEST team to see if they have seen similar issues to what I'm trying to describe.
