### ISSUE TITLE
Values provied to setInput() appear to be shared across tests

### ISSUE THREAD

**Issue by charleszipp** [Microsoft/azure-pipelines-task-lib#471]
I am noticing that inputs set from the tests appear to carry over from test to test. For example lets say I have an `setInput("backendType", "foo")` in my first test. Then in the second test I am asserting what happens if `backendType` input is not set (its an optional input). When the second test executes the stdout shows that the value of `backendType` is still `foo`. 

This looks to be due to the fact that setInput simply sets a process environment variable. The environment variables seem to carry over from test to test. 

I was able to work around this issue by adding this code to the start of each scenario I am testing
```javascript
//clear any environment vars set by the previous run
Object.keys(process.env)
    .filter(key => key.startsWith("INPUT_"))
    .forEach(key => delete process.env[key]);
```

I was expecting each run to execute in an isolated/clean environment. If this is by design feel free to close this. However, I wanted this documented in case someone else runs across the same issue.

**Comment by charleszipp** [comment]
Additional info.. child_process.spawn() by defaults copies the environment vars from the current process into the spawned child process. https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options

**Comment by damccorm** [comment]
Hm, can't speak to the original intent here, but this doesn't seem like desired behavior to me. It would probably be a fairly easy fix - I think we can basically just run the code you included at the end of each test run - it would be a potentially breaking change though. This could be a good thing to fix when we release our next major version (which we should be doing fairly soon).

**Comment by charleszipp** [comment]
Another option i might suggest rather than implementing my workaround, is that you expose an optional parameter in MockTestRunner.run(). That parameter accepts the environment vars object and its default would be process.env. The value of that parameter is then fed into child_process.spawnSync's options param. 

Surfacing the control of this reference value would allow this to be a non-breaking change and give the consumers more flexibility. You may have tests out there that are depending on the unit tests sharing state.

**Comment by damccorm** [comment]
I think in theory I like this, but having both this option and the setInput option feels confusing to me - I don't really like the idea of having both and duplicating functionality in a way that works slightly differently. Really the only difference between using setInput and passing in an object would be that setInput values persist across test runs, and that feels a little too subtle for me to be comfortable with. I think I'd probably rather wait until we release the major version (again, this shouldn't be too far away)
