### ISSUE TITLE
toolrunner.arg adds unwanted quotes around value

### ISSUE THREAD

**Issue by hoffiz** [Microsoft/azure-pipelines-task-lib#475]
Already looked into the submitted issues but can't figure out how to enable the following option:
```
windowsVerbatimArguments
```

I'm fairly new to javascript and typescript.

**Comment by damccorm** [comment]
Are you calling exec? Exec takes in an optional [options parameter](https://github.com/Microsoft/azure-pipelines-task-lib/blob/9fdd82cd724c61aa1615e732a20d3a5ffce67397/node/toolrunner.ts#L778). This is an IExecOptions object which extends IExecSyncOptions, which in turn contains a [windowsVerbatimArguments field](https://github.com/Microsoft/azure-pipelines-task-lib/blob/9fdd82cd724c61aa1615e732a20d3a5ffce67397/node/toolrunner.ts#L40), so you should just be able to pass it in like this:
```
const options: IExecOptions = <IExecOptions>{windowsVerbatimArguments: true};
exec(options);
```

**Comment by bryanmacfarlane** [comment]
looks like this is answered.  if you have issues using it let us know
