### ISSUE TITLE
No command wrappers in node lib

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/azure-pipelines-task-lib#476]
In powershell library we have plenty of the wrapper that do make code cleaner and easier to use, like Write-VstsUploadFile
https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Commands.md#write-vstsuploadfile

In Node lib this is missing and it would make the code I'm writing way cleaner.
I was wondering, would a PR with some of the commands be welcome?

**Comment by damccorm** [comment]
Sure, that sounds like a good improvement!

**Comment by damccorm** [comment]
Fixed by #477
