### ISSUE TITLE
Missing documentation on how to get user capability value via TypeScript API

### ISSUE THREAD

**Issue by FejZa** [Microsoft/azure-pipelines-task-lib#480]
Hi,

I've developed a custom build task for Azure pipelines and it demands the capability "myCap" to exist on the agent. Now in the task itself I need to get the value that is set for this capability in the agent configuration. I've been searching the docs and google a lot and I am not sure if this is even possible. Am I missing something here?

[Reference to the setting I am talking about](https://1drv.ms/u/s!ApWA4y9RKCvzrrNsaYq8PD3CHjO1LQ)

Thanks!

**Comment by damccorm** [comment]
I'm not sure what exactly you're asking - are you trying to find the version of the capability that has been added? I don't think that there's a special way to do that, you should be able to examine the files that have been added to satisfy the demand and determine the version from that, there's not a standardized way to do that for all demands though so the responsibility probably can't be on the agent for that. Am I understanding your question correctly?

**Comment by bryanmacfarlane** [comment]
Capabilities and demands are only used for routing (picking an agent in a heterogenous pool of private agents).   

The tool should be added in to the path and the task should use `task-lib.which()`

Example:
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/XcodeV5/xcode.ts#L31

You can also code the task to take an advanced input where the user can override

use input type of path and `task-lib.filePathSupplied` to know whether to use value in path or the override supplied by the user

https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L276

The user can supply relative or absolute paths in an override

**Comment by FejZa** [comment]
Then I don't get the point of defining user-capabilities with a key - value pair to be honest. Because it seems the only thing relevant is the whether the key exists or not. Thank you for explaining.

**Comment by damccorm** [comment]
I believe the point of having the value is so that you can specify accepted values for that key. One example of where you might do this is ```Agent.Version```.

In a demand you can specify something like ```Agent.Version -gtVersion 2.141.0``` - this would be satisfied by an agent with the capability ```Agent.Version | 2.142.1``` but not by an agent with the similar capability ```Agent.Version | 2.140.0```, even though the both have the ```Agent.Version``` key.

So the advantage of having the value on top of just the key is that you can do better matching than just "does the key exist?"
