### ISSUE TITLE
Add ability to author tasks in c#

### ISSUE THREAD

**Issue by jachin84** [Microsoft/azure-pipelines-task-lib#481]
I have some existing build tools that I would like to use in Azure DevOps. At the moment I am having to wrap these tools with either a node or powershell task in order to execute them. Is there any mechanism to write the task in c#?

**Comment by damccorm** [comment]
No, we don't have a handler on our agent that directly allows you to write tasks in languages other than C# or PowerShell. This is not a feature we plan on adding at this point in time.

**Comment by jachin84** [comment]
> No, we don't have a handler on our agent that directly allows you to write tasks in languages other than C# or PowerShell. This is not a feature we plan on adding at this point in time.

Was that a typo, you said you support C# or PowerShell above

**Comment by damccorm** [comment]
> Was that a typo

Yes, sorry - meant to say Node or PowerShell. Corrected in the original comment as well.

**Comment by stephenmichaelf** [comment]
@vtbassmatt FYI.

**Comment by vtbassmatt** [comment]
@jachin do you need a task, or can you just run them from a script? Tasks mostly just map inputs and give a convenient way to distribute to others - but it sounds like this may be custom to your instance.

**Comment by jachin84** [comment]
I suppose it comes down to maintenance/testing and limiting friction. The simplest method to use my existing C# build utilities is to compile them as an executable and then wrap either wrap them in an in-line Powershell script or build a Powershell or node based task to wrap the existing functionality.

Another approach would be to re-author these tools into either Powershell or nodesjs. Neither of these options appeals to me as that’s not where my skillset lies and they all introduce more fiction in maintaining my build process. 

My ideal would be to implement ITask or something similar and just provide an assembly in a custom task.

As an example of the kinds of tasks we have my most recent task is for app settings substitution. This is similar to the functionality built into the IISWinRM task but without the web deploy part. Basically searching appSettings for any pipeline variables and performing a substitution. This doesn’t exist for non-web project so I need to make one. The only way to get at all the variables in a pipeline, including secrets is to author a custom task. 

I’ve used PowerShell for the example above and it was a length process to debug and test a PowerShell task locally, particularly one that works on variables. I would have much preferred a c# class that I could easily unit test and debug in a familiar dev environment.

**Comment by damccorm** [comment]
> The only way to get at all the variables in a pipeline, including secrets is to author a custom task.

I'm a little curious what you mean here - you should be able to access the same variables in a PowerShell script task rather than building your custom task, you just need to [scope secrets in](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables).

**Comment by jachin84** [comment]
Scoping in the secret require that I specify the name explicitly. I want the exact behaviour as the IISWinRM task where the variables don’t need to be specified anywhere they are simply substituted in if they are in an appSettings or connectionString section.

I have actually written a custom task in PowerShell to do this by reverse engineering the IISWinRM task. Unfortunately it was written in node so I had to work with two unfamiliar languages to get it to work. By far this was the most difficult and lengthy part of developing my release pipeline.

In a perfect world the in-built tasks would do everything that’s needed however real life is complex and messy. For me this request is about limiting friction for c# devs who don’t have experience with node or PowerShell. I’m not saying drop support for PowerShell or node, just add C# or even C# Script. I see that there is a similar issue in the agent repo 
https://github.com/Microsoft/azure-pipelines-agent/issues/774. Perhaps there is more demand for this than you think?

**Comment by damccorm** [comment]
> I want the exact behaviour as the IISWinRM task

Ah, that makes sense, thanks for clarifying.

> I see that there is a similar issue in the agent repo

Thanks for pointing that out, I wasn't aware of that issue (it was before my time working on the product) - you might be right that there's more demand than I thought.

With that said, if this change is going to happen it would need to be driven from the agent repo first, so this discussion probably does still belong there. I'm going to close here, but I'll try to revive the agent repo issue again/put it on the radar of the appropriate people.
