### ISSUE TITLE
scheduledReleaseTrigger.schedule.daysToRelease is returned as string instead of number

### ISSUE THREAD

**Issue by akhanna38** [Microsoft/azure-pipelines-task-lib#488]
scheduledReleaseTrigger.schedule.daysToRelease is returned as string instead of number
```
import TFS_Release_Client = require("ReleaseManagement/Core/RestClient");
const context = VSS.getWebContext();
const releaseClient = TFS_Release_Client.getClient();
const releaseDef = await releaseClient.getReleaseDefinition(context.project.id, 1); // add a valid release definition id with a scheduled trigger
```
releaseDef.triggers[0].schedule.daysToRelease is returned as string instead of number

Sample trigger output
schedule:
**daysToRelease: "8"**
jobId: "4def89dd-b181-4b21-889a-1ab8ee2d5769"
startHours: 10
startMinutes: 0
timeZoneId: "UTC"
triggerType: 2

from VSS

export interface ReleaseSchedule {
    /**
     * Days of the week to release
     */
    daysToRelease: ScheduleDays;
.
.
.
}
export enum ScheduleDays {
    None = 0,
    Monday = 1,
    Tuesday = 2,
    Wednesday = 4,
    Thursday = 8,
    Friday = 16,
    Saturday = 32,
    Sunday = 64,
    All = 127
}

**Comment by damccorm** [comment]
I don't think this is an issue with this library/I'm not really sure where you use this library in your code. What are ```VSS``` and ```ReleaseManagement/Core/RestClient``` referencing here? Are you using the [azure-devops-node-api](https://github.com/Microsoft/azure-devops-node-api)?

**Comment by akhanna38** [comment]
I am using vss-web-extension-sdk. should i put the bug in that repo then ?

**Comment by damccorm** [comment]
Yeah, that would probably be a better place. We don't own that repo, so it would be challenging for me to diagnose the issue. I'm going to close the issue here.
