### ISSUE TITLE
[Question] Powershell modules

### ISSUE THREAD

**Issue by balfa666** [Microsoft/azure-pipelines-task-lib#489]
Hello,
 We are trying to use make.json to get powershell module from an internal repo. Is there a way to get the module dependencies with make.json or I have to use an external script?

**Comment by damccorm** [comment]
I'm not sure I'm understanding the question correctly, but if you're trying to use an internal module you would need to package that with the task. Could you clarify what you are trying to do a little bit?

**Comment by balfa666** [comment]
Normally we would do Install-Module and all the dependencies from the .psd1 would install themselves. I'm trying to replicate this with the make.json.

**Comment by damccorm** [comment]
Ah, I see. 

Tasks need to carry their dependencies. In other words, Install-Module is a task build time operation (not runtime). Every task needs to carry it's full dependency tree (every task is self contained).

Does that help?

**Comment by damccorm** [comment]
Yeah, or something along those lines that lets you package in your dependencies.

**Comment by balfa666** [comment]
thanks for your help
