### ISSUE TITLE
visibility property in task.json not supported anymore

### ISSUE THREAD

**Issue by jsalado** [Microsoft/azure-pipelines-task-lib#490]
Hello,

I've just noticed that the visibility property in the task.json file is not supported anymore.

According to issue #392 this is because its assumed that "most" task should run in both build and release pipelines. I think that is assuming too much. In my case I have an extension with 2 tasks, one suitable for both pipelines and another only for Build.

The visibility property was perfect for me, my users on had the possibility of adding only the right task when adding tasks to their release pipelines.

Now, I have to add code to my task to make it aware of the type of pipeline it is running and do nothing or fail with a message to the users telling them to not use that task in release pipelines, which is silly... and confusing.

Any chance it will be back?

Thanks

**Comment by damccorm** [comment]
I think this was actually taken out because it wasn't being completely supported/honored. Unfortunately I don't think that this is something we will be adding back/supporting in the near future as our goal is to move towards a more unified pipelines structure.

**Comment by jsalado** [comment]
Hi,

thanks for your answer @damccorm. It's a pity (at least for me...) that this feature is not coming back. Even if it came back in the far future, I still will need to have the code in my tasks that make them pipeline type (Build or Release) aware for backward compatibility with older versions of Azure DevOps Server (former TFS).

Now my problem is to make the tasks pipeline type aware... I'm currently with the different variables that the 2 pipelines types expose. 
For example, Build.SourcesDirectory is exposed in build pipelines but not in Release pipelines. It is a variable my tasks use. So for the one task that can run on Release pipelines I fall back to getting Agent.ReleaseDirectory and append the Release.PrimaryArtifactSourceAlias (provided the primary artifact defined is the application source code). That is where the agent checks out any source code artifact using the alias, and the only one I can get from a variable is the primary one artifact

Although this is currently working, I have 2 objections to this approach and I need your help to see if there is a better approach to overcome these objections, now or in the future:

1. Using Build.SourcesDirectory to identify the pipeline type is not robust. It will stop working if you guys decide to expose that variable in a release pipeline as you currently do with other Build.* variables such as Build.SourceBranch (which maps to Release.Artifacts.{Primary artifact alias}.SourceBranch).
2. The Release.PrimaryArtifactSourceAlias is available in Azure DevOps but in Azure DevOps Server (TFS). I tried with 2015 update 3, 2017 and 2018. This unreliable if the user changes the default alias for the source code artifacts (I've added code to fall back to Build.ProjectName if Release.PrimaryArtifactSourceAlias is undefined)

It would be nice to have a native way to know the pipeline type, and a way natively and easily get the source code directory of any sorce code artifacts in release pipelines. That would make my life a lot easier in the future. I guess I will still need to leave my current code for backward compatibility until I decide to stop supporting *old* versions of TFS.

Do you think any of this will be possible?

**Comment by damccorm** [comment]
1. I think you can use ```System.HostType``` to infer the pipeline type https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops#system-variables
2. I'm not 100% sure I understand what you're asking for, but it sounds like you might be looking for [Primary Artifact Variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch#primary-artifact-variables)? If that's not what you're asking about could you provide a bit of additional clarification?

**Comment by jsalado** [comment]
Hello,

thank you for your answers. 

I wasn't aware of System.HostType, it'll work for me, it's perfect. There are so many variables that that one slipped thru my reading.

Sorry about my explanation of my second issue, here is another try...
My problem is that I need to know the directory where the sorce code artifacts are checked out to during a release. That directory is always Agent.ReleaseDirectory/{artifact alias}, for example C:\agent.vsts\_work\r1\a\_NorthWindTraders.Net, where _NorthWindTraders.Net is the alias (this the default in Azure DevOps) of the source code artifact of my NorthWindTraders.Net project.
The only variable exposed with the value of an artifact alias is  Release.PrimaryArtifactSourceAlias. So if the source code artifact is the primary one, I can get all the info I need.
My problem is that the Release.PrimaryArtifactSourceAlias is available in Azure DevOps but not in the on-prem Azure DevOps Server (former TFS). I tried on 2015 update 2, 2017 and 2018 versions, in none of them that variable is defined as it is in Azure DevOps. You can see that because of this, my extension won't work on all Azure DevOps platform.
So what I do if Release.PrimaryArtifactSourceAlias is not defined, is to use Build.ProjectName, since that is the default alias for source code artifacts (in on-prem platforms), and hope the user didn't change it.
As you can see this not very reliable and I'm asking if there is a better way to do this so my extension works fine on all platforms.

Thanks again for your support.

**Comment by damccorm** [comment]
Ah gotcha, thanks for clarifying. Unfortunately I don't think there's a great way to do this, I think that's why the ```PrimaryArtifactSourceAlias``` was introduced, and will be supported going forward (in future on-prem versions as well). My recommendation would probably be to take the artifact alias as an input. Sorry I can't be of more help here :(

**Comment by jsalado** [comment]
Thank you very much @damccorm 

I'll see what I do... Yup, the input field is always a possibility. I'll implement something documenting it as much as possible, get feedback from my users and adapt to what is best for them.

Closing the issue. Best,
J.
