### ISSUE TITLE
getInput on a Picklist change data type from "string" to "int"

### ISSUE THREAD

**Issue by drakonien** [Microsoft/azure-pipelines-task-lib#498]
### Environment
azure-pipelines-task-lib version: 2.7.7

### Issue Description
In an Azure DevOps (VSTS) custom extension, when retrieving a value from a picklist input parameter using _getInput_, the value "7.0" as string is changed to "7". It seems like there is some kind of conversion to type _int_ while recovering the value.

The picklist is defined as follows:
```json
{
      "name": "FunctionPhpVersion",
      "label": "App Service PHP Version",
      "type": "picklist",
      "options": {
        "Off": "Off",
        "5.6": "5.6",
        "7.0": "7.0",
        "7.1": "7.1",
        "7.2": "7.2"
      },
      "required": false,
      "defaultValue": "Off",
      "groupName": "TaskParameterOptions",
      "visibleRule": "ParameterSetSelector = InputParameter"
}
```

Using any other value like "Off", "5.6" or "7.1" works without problems, but "7.0" is changed to "7".
That change implies that, later in the release pipeline, when the provided value is validated against the valid values it raises an error because "7.0" != 7

```
The argument "7" does not belong to the set "Off,5.6,7.0,7.1,7.2" specified by the ValidateSet attribute.
```

### Expected behaviour
The actual value recovered is "7.0" as string, with the dot and the trailing 0.

### Actual behaviour
The value recovered is "7" without the dot and the trailing 0.

### Steps to reproduce
1. Set a pickList parameter with "7.0" value
2. Invoke getInput
3. Returned value is not as expected

### Logs
Extract from Azure DevOps extension output using console.log to view param type and recovered value after calling _getInput_
```
##[RunTask]Reading value param.GetCccParamValues....... 'FunctionPhpVersion' type = [picklist]
##[RunTask]Readed value param.GetCccParamValues....... 'FunctionPhpVersion' [7]
```

**Comment by jcampuzano** [comment]
Hi, I have the same issue with strings that represent numbers. When invoke getInput with a value "1.0", it return integer 1...

**Comment by damccorm** [comment]
Hi, sorry for the delayed response, I am now looking into this.

**Comment by damccorm** [comment]
I think this is probably an issue with how we handle this internally, not with this library, I'll go ahead and reach out to the team that owns this.

**Comment by damccorm** [comment]
We're struggling to get a repro on our end, and it looks like some tasks are [using the behavior you're describing](https://github.com/Microsoft/azure-pipelines-tasks/blob/22b5fb36018c96d407a54f578d9ddc7d8c8bc6d4/Tasks/XamarinAndroidV1/task.json#L117) with no problems. Could you provide a little more info? Is there a specific task you're seeing this with or is it your own private custom task?

**Comment by drakonien** [comment]
Hi @damccorm,

For the las 30 min aprox, I was preparing the anwser to your last comment. Gathering logs, some PowerShell and JavaScript code, JSON with the picklist definition, and so on...

While doing this i saw a line in this code:
```JavaScript
let inputValue: any;
console.log(`##[RunTask]GetCccParamValues: reading value for '${input.name}' with type = [${input.type}]`);
switch (input.type) {
    case 'boolean':
        inputValue = tl.getBoolInput(input.name, input.required);
        break;
    default:
        inputValue = tl.getInput(input.name, input.required);
}
if ((inputValue === undefined || inputValue === null) && input.defaultValue) {
    inputValue = input.defaultValue
}

//If any value was readed
if (!(inputValue === undefined || inputValue === null)) {
    //Try to convert the value as json
    try {
        inputValue = JSON.parse(inputValue.replace(/\'/g, '"'));
    } catch { } //I know, empty catch, it's just for this test ;-P
    //Add the value to results  
    retVal[input.name] = inputValue;
    console.log(`##[RunTask]GetCccParamValues: readed value for '${input.name}' is [${inputValue}]`);
}
```

This line!
```JavaScript
inputValue = JSON.parse(inputValue.replace(/\'/g, '"'));
```

I made a test:
![image](https://user-images.githubusercontent.com/18159615/54108241-b4b26600-43db-11e9-8c16-79f848a7680a.png)

And found the culprit!!
It's the _JSON.parse_ the one that is changing the data type.

Sorry for making you waste your time in this!!
I'm closing the issue.
Thank you for your attention and one more time, sorry!

@jcampuzano please check if this could be your issue as well, or at least something similar.

**Comment by damccorm** [comment]
Glad you found the issue, thanks for letting me know!
