### ISSUE TITLE
dataSourceBindings

### ISSUE THREAD

**Issue by kripajoym** [Microsoft/azure-pipelines-task-lib#501]
I am developing a custom VSTS task.
To populate the values in a drop down list am using the below dataSourceBindings.
and am able to populate is successfully.

If the list contains a value like TestApp" or "TestApp" including the double quotes it is listed differently.
{ "Value" : "e5966dc2-f1cb-41dc", "DisplayValue" : "TestApp"" }
or 
{ "Value" : "e5966dc2-f1cb-41dc", "DisplayValue" : ""TestApp"" }
How can I handle the values with double quotes? Special characters like % or $ is working fine as any other string.

"dataSourceBindings": [
{
"target": "applications",
"endpointId": "$(TestService)",
"endpointURL":"{{endpoint.url}}/test/Apps/",
"resultselector":"jsonpath:$.[*]",
"resultTemplate":"{ "Value" : "{{{Id}}}", "DisplayValue" : "{{{Name}}}" }"
}
]

**Comment by damccorm** [comment]
I'm not 100% sure I'm understanding your question correctly, but I think you should be escaping the quotes (e.g. see [here](https://github.com/Microsoft/azure-pipelines-tasks/blob/93f1fa0b3bdc279721f7d56cde7107387d0d7e1e/Tasks/DownloadGitHubReleaseV0/task.json#L87)). Does that help? If not, could you try to clarify what you're asking?

**Comment by kripajoym** [comment]
![image](https://user-images.githubusercontent.com/36063366/53254746-01165a00-36ea-11e9-974b-dbb618a8f141.png)

My bad, i was indeed escaping the quotes. Here's the right DataSourceBinding.
{
        "target": "EclipseProject",
        "endpointId": "$(TestService)",
        "endpointURL":"{{endpoint.url}}/rest/joy/Apps/",
        "resultselector":"jsonpath:$.[*]",
        "resultTemplate":"{ \"Value\" : \"{{{Id}}}\", \"DisplayValue\" : \"{{{Name}}}\" }"
      } 
in task. json

While fetching the key value pairs, If DisplayValue-Name contains double quotes (eg. "AppWithQuotes" or AppWith"Quotes), the dropdown is displaying the entire key value pair as it is (refer attachment).
For other cases (when double quotes are not present), the drop down displays the DisplayValue name alone as expected (eg. Demo/123). 

Does this mean that I cannot have double quotes in the DisplayValue-Name, or is there a way to get it working in all cases?

Thanks in advance

**Comment by kripajoym** [comment]
Okay, looks like escaping double quotes seems to remove the back-slash in this comment box. attaching a screenshot for clarity
![image](https://user-images.githubusercontent.com/36063366/53263444-73456980-36ff-11e9-9ca1-98a959d292f4.png)

**Comment by damccorm** [comment]
Huh, that's weird, not sure why GitHub does that. Looks like `\\""` does the trick, alternately sticking it in a code block seems to work.

Concerning the actual behavior in question here, I'm not 100% sure of how this is supposed to behave because we don't own that part of the functionality in this library, but I think since this [behaves essentially as a mustache template](https://github.com/Microsoft/azure-pipelines-extensions/blob/0437e1b000985d1151cd625cc19e77f3a26c2aa6/docs/authoring/endpoints/dataSources.md#resultTemplate), what you have as the value of `Name` will directly replace `{{{Name}}}` in the output. So if you escape the `"` in `Name` it should work, but just passing in a non-escaped `"` will blow up (as you've seen).

**Comment by damccorm** [comment]
I'm going to close since I think I've answered the part of the question concerning this library

**Comment by knowds** [comment]
Please reopen , since we just fetch and show the data as is. More details here: https://github.com/janl/mustache.js/issues/694

**Comment by damccorm** [comment]
Hey @knowds since this is a more general service question, could you open a ticket at https://developercommunity.visualstudio.com/spaces/21/index.html? We're trying to get a little cleaner at routing issues to the most appropriate place so they get routed to the right people more quickly
