### ISSUE TITLE
Combo box as task input

### ISSUE THREAD

**Issue by armanik11** [Microsoft/azure-pipelines-task-lib#504]
Is it possible to have a combo box input for a custom task? Currently it's a pickList (populated by API Call) but we would also like the ability for users to provide their own input. This task mostly gets injected at release time so the values get passed from the release definition but there are scenarios where a user can add the task directly in the release definition.

Ex:

 {
      "name": "definition",
      "type": "pickList",
      "label": "Branch",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Branch id",
      "dependencyInputIds": [
        "connection",
        "serviceid"
      ]
    },

**Comment by damccorm** [comment]
This isn't currently supported and isn't controlled by this library unfortunately :( - I'd recommend adding this as a request to the developer community - https://developercommunity.visualstudio.com/spaces/21/index.html.
