### ISSUE TITLE
Slow performance in VsTestV2 for searching TestAdapter

### ISSUE THREAD

**Issue by jirikanda** [microsoft/azure-pipelines-task-lib#517]
### Environment
azure-pipelines-task-lib version: 2.x

### Issue Description
File system is traversed to find test adapters even when file system was already traversed to search test assemblies. As described in #516 file system traversal is very expensive for some projects (see log attached at 516).
Files found in the filesystem could be re-used to find test adapters.

### Expected behaviour
Redundant file system traversals should be eliminated.

**Comment by damccorm** [comment]
I'm not sure I understand, how is this different from #516? Or should we close here and just track this there?

**Comment by jirikanda** [comment]
Thank you for the reply and sorry for the confusion. I will try to describe it more precisely.

### Situation
Test test files (testAssemblyVer2): *A.dll, *B.dll, *C.dll.

### Actual behavior
There are four file system traversals performed:

1. File system traversal for *A.dll
2. File system traversal for *B.dll
3. File system traversal for *C.dll
4. File system traversal for **\\*TestAdapter.dll

### Related issue
Performance degradation for repeating file traversal for test files in bullets 2 and 3 are in #516.

### This issue
In this issue I try to describe that searching for **\\*TestAdapter.dll in bullet 4 adds one more file system traversal, which was already performed (and the found files are already in memory). Only one file system traversal should be performed for searching all four patterns (depends on configuration, of course).

**Comment by hakenr** [comment]
As far as I understand:

#516 says, that 1+2+3 are implemented as single call of [findMatch()](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L1467) with three patterns and the internal implementation of findmatch() can be easily adjusted not to perform file system traversal for every single pattern again and again.

#517 says, that although (1+2+3) vs. 4 are probably two different calls to [findMatch()](https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L1467), they perform the very same slow file system traversal and this should be improved too.

**Comment by damccorm** [comment]
Ah, that makes more sense, thanks for the clarification.

For this issue, I'm not really sure how we can improve this. Since we don't know ahead of time which files will be searched for again and we can't store all of the files we ever traverse in memory, I'm not sure there's a good way to do this. Maybe I'm missing something here, but as I see it this doesn't feel like something that can be solved.

I'll address #516 in its own issue. It seems more tractable to me, but I need to think a little bit more about it.

**Comment by hakenr** [comment]
Is there any chance to wrap the [find(findPath, findOptions)](https://github.com/Microsoft/azure-pipelines-task-lib/blob/11c9439d4af17e6475d9fe058e6b2e03914d17e6/node/task.ts#L1585) calls ([implementation](https://github.com/Microsoft/azure-pipelines-task-lib/blob/11c9439d4af17e6475d9fe058e6b2e03914d17e6/node/task.ts#L811)) with some simple memory-cache?

**Comment by damccorm** [comment]
That could help. I'm not sure I'd want it enabled by default, but it could be a useful parameterized option to include.

I'll take a harder look at this when I get bandwidth, there are some other things in this library that I probably want to address first though. We also take PRs if you want to take a crack at it 😃

**Comment by stephenmichaelf** [comment]
I renamed, this doesn't look like it degraded due to a change. Please correct me if I'm wrong.

**Comment by jirikanda** [comment]
Thats fine, thanks.
