### ISSUE TITLE
resultSelector, negate jsonPath?

### ISSUE THREAD

**Issue by MichelZ** [Microsoft/azure-pipelines-task-lib#519]
### Environment
azure-pipelines-task-lib version: latest

### Issue Description
Struggling with a jsonPath expression that tests that a property does NOT exist.

I have the following response in a dataSource (picklist):
https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/queries/list?view=azure-devops-rest-5.0#examples

The task configuration (dataSourceBindings) is as follows:

```
{
            "target": "query",
            "endpointId": "tfs:teamfoundation",
            "parameters": {
                "project": "$(project)"
            },
            "endpointUrl": "{{endpoint.url}}/{{{project}}}/_apis/wit/queries?$depth=2&api-version=5.0",
            "resultSelector": "jsonpath:$..[?(@.isPublic == true)]",
            "resultTemplate": "{ \"Value\" : \"{{{id}}}\", \"DisplayValue\" : \"{{{path}}}\" }"
        }
```

This works, and gives me all queries that are "public" (e.g. "Shared Queries").
I now need to further filter this list to NOT include folders.
As a complicating factor, this property is only stamped when it is actually a folder (isFolder = true), the property does NOT exist, when it is NOT a folder. (So there is no "isFolder == false" to test for)

I tried:
 `"resultSelector": "jsonpath:$..[?(@.isPublic == true && !@.isFolder)]",`
but it doesn't like the negating "!".

Any ideas how I can accomplish this?
What exact flavor of jsonPath is used?

Thanks

**Comment by MichelZ** [comment]
Shortly after writing this I found that I can test for the existence of "queryType", which does not exist on folders to accomplish what I need.

Out of curiosity, I'd still be interested if it is possible for a "property does not exist" or similar filter to accomplish what I need using the original requirement of using "isFolder"?

**Comment by damccorm** [comment]
This isn't owned by this library, so I'm not a complete expert on this. With that said, [from here](https://github.com/Microsoft/azure-pipelines-extensions/blob/0437e1b000985d1151cd625cc19e77f3a26c2aa6/docs/authoring/endpoints/dataSources.md#datasource) you can read that `resultSelector` is either a JSONPath or XPath query (yours is clearly a JSONPath in this example). Looking at [JSONPath filter operations](https://github.com/json-path/JsonPath#filter-operators), it looks like `nin` (not in) might do the trick here?

**Comment by MichelZ** [comment]
Thanks. I saw someone from the azure-pipeline-task team suggest that these questions belong here. Where would be the correct place for this question?

Also, there are many flavors of json path.
On the site you reference, there is a sentence here:
https://github.com/json-path/JsonPath#inline-predicates

> You can use ! to negate a predicate [?(!(@.price < 10 && @.category == 'fiction'))].

which suggests that `!` is in fact, legal. 
I will do some testing with `nin`, I haven't seen this one yet.

Thanks a lot for your time!

**Comment by damccorm** [comment]
> Where would be the correct place for this question?

I think since the docs live in https://github.com/Microsoft/azure-pipelines-extensions that's probably the best place for dataSource specific questions. With that said, this repo is never a bad starting place for task authoring questions if you're ever uncertain where they belong - we own most things surrounding that (this is just one exception), and can usually at the very least help route the question.

**Comment by MichelZ** [comment]
Thanks, I will ask my question there. 
Cheers
