### ISSUE TITLE
Question: Overriding default behavior in Control Options for a pipeline task

### ISSUE THREAD

**Issue by dichternebel** [Microsoft/azure-pipelines-task-lib#522]
Hi there,

not sure if this is the right location to ask my question but here's what I'm trying to achieve:
I'm building a custom task that needs to be run by default even if previous errors occurred. So basically I want to override the default in "Control Options"/"Run this task" to "Even if a previous task has failed, even if the deployment was canceled" when the task is added to Agent job.

Any idea how this would be possible?

Thanks in advance,
Sascha

**Comment by stephenmichaelf** [comment]
Hey Sascha,

We do not have a mechanism for overriding the Run this task control options.

We are about to release a new feature where you can inject tasks at the start or end of every build. The vehicle for this is by installing an extension. Would that solve your needs?

These are controlled conditionally by yaml but the yaml gets evaluated for every job that runs across your account.

Also if the deployment was cancelled we don't have a mechanism to force run anything else.

What is the task you want to run and is it OK if it runs for all jobs in your entire organization?

**Comment by bryanmacfarlane** [comment]
It’s the definition designers choice ( designer or yaml ) whether to always run your unit of work ( task ).  The task offers the unit of work

**Comment by damccorm** [comment]
Yep, the user can control this from their end with `condition: always()` (in yaml) or by using the control options in the task.

Docs on this here - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

**Comment by dichternebel** [comment]
Thanks for the replies! Very appreciated.
I am aware that the defintion designer is in charge to control this behavior but I know my "users"... ;-) They simply forget that.
@stephenmichaelf  Your feature description seem to do exactly what I'm trying to achieve and yes it is ok that it runs for all jobs inside our organization since I would need it to notfiy a third-party tool that is used to track progress in change management. So I'm looking forward to trying out this extension.

**Comment by stephenmichaelf** [comment]
@dichternebel Could you email me: stfrance at microsoft.com

I will follow up with you once the feature is available to try :)
