### ISSUE TITLE
SetVariable with variable names containing '=' failed the task 

### ISSUE THREAD

**Issue by Yiming-Jia** [microsoft/azure-pipelines-task-lib#535]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 
2.8.0
### Issue Description

tl.SetVariable with variable names containing '=' failed the task 
### Expected behaviour

the task is no failed
### Actual behaviour

Task failed
Build link: https://dev.azure.com/yijia/AppConfig-Test/_build/results?buildId=100

### Steps to reproduce
1. tl.setVariable("=", "="); 

### Logs

Log snippet as below:
```
##[debug]Set variables: =; v: "="
##[debug]set ===
##[error]Unable to process command '##vso[task.setvariable variable==;issecret=false;]=' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.
##[debug]System.Exception: Required field 'variable' is missing in ##vso[task.setvariable] command.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
##[debug]Processed: ##vso[task.setvariable variable==;issecret=false;]=
##[debug]Set variables: ==; v: "haha"
##[debug]set ===haha
##[error]Unable to process command '##vso[task.setvariable variable===;issecret=false;]haha' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Required field 'variable' is missing in ##vso[task.setvariable] command.
##[debug]System.Exception: Required field 'variable' is missing in ##vso[task.setvariable] command.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
```

**Comment by damccorm** [comment]
This behavior is actually controlled by the [agent](https://github.com/microsoft/azure-pipelines-agent), with that said, I think this behavior is by design - there are simply some values that have to be reserved, and it looks like `=` is one such reserved character.

**Comment by Yiming-Jia** [comment]
But it seems this is a bug in their code. As any keys containing `=` will failed, or key-value will be mess up, something like if key is `a=b` and value is `a=b`, it will be end up like key is `a`, and value is something like `b=a=b`. I consider this is a bug because [the document](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md) is not clear about the reserved character.

**Comment by damccorm** [comment]
Neither Windows nor Linux (and I'd guess Mac as well) allow = in environment variables.

From [Windows docs](https://docs.microsoft.com/en-us/windows/desktop/ProcThread/environment-variables) - "The name of an environment variable cannot include an equal sign (=)."

From [Linux docs](http://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap08.html) - "names shall not contain the character '='"

Since the variable is exposed as an environment variable (as the docs you linked to mention), its reasonable to expect them to follow the same rules.

**Comment by damccorm** [comment]
I'm going to close since this isn't an issue with our repo. If you disagree feel free to comment and I'll reopen if appropriate.

**Comment by Yiming-Jia** [comment]
Hello @damccorm 

Part of the issue I found was, when `tl.setVariable` failed, the `try-catch` block didn't catch up the exceptions. Do you have any clues of why that happens from stack trace? My guess is that the exception in agent code didn't bubble up to the task library.

**Comment by damccorm** [comment]
> My guess is that the exception in agent code didn't bubble up to the task library

That's sort of right. The pattern we follow here is that `setVariable` eventually writes a [`command`](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L186), which in turn just writes to the [outStream](https://github.com/microsoft/azure-pipelines-task-lib/blob/198b22ef9ba5b13eeb95fd68efc74ec101720e4e/node/internal.ts#L278). The agent then takes that output and reads it in/processes it - so from this libs perspective nothing exceptional occurred.

Once the agent does that, in this case it throws which causes the result to be set to `TaskResult.Failed` [with the exception](https://github.com/microsoft/azure-pipelines-task-lib/blob/198b22ef9ba5b13eeb95fd68efc74ec101720e4e/node/task.ts#L99) - this is what you should be looking for if you want good error handling here. In general, you shouldn't really be setting variables that might fail - I struggle to see a use case here.

**Comment by Yiming-Jia** [comment]
@damccorm 

Thank you for the information. The `TaskResult.Failed` the expected behavior in our case. The use case I'm seeing here is that failures in `setVariable` will console out the message like `##[error]Unable to process command '##vso[task.setvariable variable===;issecret=false;]haha' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)`. In some user scenarios, user doesn't want to print out the values for the production build/release. Also, since customer may have many key-value settings, it's not worth to set all of them as secret, because customer need to have extra configuration steps for each key-value pair, due to [the document](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md). So we'd like to know if there is a way that not print key-value when `setVariable` fails. 

Thanks,
Yiming

**Comment by damccorm** [comment]
There's not a way to suppress that as far as I know. The right thing to do here is probably just to do some pre-validation which checks if your key is a valid env var name and if so don't try to set it.

With that said, if the customer has things that they don't want leaked they should absolutely be marked as secrets.

**Comment by Yiming-Jia** [comment]
I see. So we need to maintain a list of reserved characters right? Do you know any characters besides `=` ?

**Comment by Yiming-Jia** [comment]
@damccorm 

Let's sync up on Monday. Just a heads up about [Azure App Configuration task](https://marketplace.visualstudio.com/items?itemName=AzureAppConfiguration.azure-app-configuration-task&targetId=cafb1f13-e645-423d-a793-2e596e1ba9de&utm_source=vstsproduct&utm_medium=ExtHubManageList). Since we helps customers to manage their settings. For us, we have no idea if the settings are secrets or not when customers use our task. So it's definitely not acceptable to dump all key-values once the `setVariable` failed. Could you consider suppress key-values output as a feature request.

**Comment by damccorm** [comment]
> Do you know any characters besides = ?
Not off the top of my head. The only other thing I could see causing trouble is `;` since that is used to terminate the variable (aka `##vso[task.setvariable variable=varName;...`), I'm not sure how we handle that though - I think it should actually be ok. Everything else should follow normal env variable rules.

> Could you consider suppress key-values output as a feature request.

No - that's the point of having secrets. If you're not sure whether something is a secret or not, it should be marked as a secret, one key purpose of secrets is that they get masked from the output. We very intentionally do not do this for non-secrets. Even if we make that an option here, there are other places where that could easily get leaked

**Comment by Yiming-Jia** [comment]
Synced offline with @damccorm , here are the two points that Danny said:

1. They assume that if user set as secret, then they're responsible to protect the data; if user set as non-secret, then user don't guarantee if the data gets released; And user is aware of the fact that their data is not protected if set as non-secret.
2. If masking the non-secret data, it will mislead user that the key-value is well-protected as secret, because there is chance to leak non-secret data.

**Comment by Yiming-Jia** [comment]
@damccorm 
As the workaround of not printing user's value:

We thought to use logic:
1. setVariable(key, "***").
2. getResult()
3. if not failed, setVariable(key, value)

But I haven't find any related Api for getResult(), could you kindly point me where/how I can get the task result. Thanks

**Comment by damccorm** [comment]
I thought we had one, on review it looks like that doesn't exist. Also, setting the task result to failed is unreversable I think.

That's probably for the best though, again I would actively encourage you to make things that can't leak secrets and discourage you from this current path - its simply not secure.
