### ISSUE TITLE
Native PowerShell Core task execution support

### ISSUE THREAD

**Issue by dmitryserbin** [microsoft/azure-pipelines-task-lib#537]
### Enhancement request

We need a native **PowerShell Core** task execution for Windows-based agents. Is it possible to add new PowerShell6 execution handler to support this?

### Expected behaviour

Updated `task.json` schema and underlying API to support PowerShell Core execution:

```json
    "execution": {
      "type": "object",
      "additionalProperties": false,
      "description": "Execution options for this task",
      "properties": {
        "PowerShellCore": {
          "$ref": "#/definitions/executionObject"
        }
      }
    },
```

**Comment by damccorm** [comment]
To be clear, is this the same issue as #314? If so, I'd rather keep the conversation there - I recognize it had gone stale, but tried to respond now and will try to be more responsive.

There's a lot of context there that I'd prefer we not lose/better to address one problem in one place.

**Comment by dmitryserbin** [comment]
Thanks for looking into this @damccorm ! Yes, this is quite similar to #314 , however our concern is Windows agents only at this stage - not sure if this makes it any easier for you.

**Comment by damccorm** [comment]
Ok. I think the answer is more or less the same - its not currently high priority for us right now so we don't have an eta. I also think if we add one it will be for all 3 platforms (I don't see any reason not to do this), so I'd probably rather just track in #314 - does that seem fair?

**Comment by dmitryserbin** [comment]
Yep that's fine with me @damccorm . Just one more question - what does it take to make it a priority for you guys? We could push it through our official channels with MS, if needed.

Just some background: we got a lot of custom Azure DevOps tasks running our custom Azure deployment mechanism. All of those tasks are currently using AzureRM on PowerShell 5, which is fine. However, we can't update to Az module (as we want new Az features) because we'll need to run PowerShell 6 which is not currently supported by the task. We could hack it as a workaround, but I would prefer a native execution handler to address this. Also, we're running custom Windows agents, so agents pre-requisites for PowerShell Core is not a problem for us.

**Comment by srrl** [comment]
> Ok. I think the answer is more or less the same - its not currently high priority for us right now so we don't have an eta. I also think if we add one it will be for all 3 platforms (I don't see any reason not to do this), so I'd probably rather just track in #314 - does that seem fair?

This is really frustrating. It is a huge blocker for our team as well...

**Comment by damccorm** [comment]
> what does it take to make it a priority for you guys? We could push it through our official channels with MS, if needed.

@dmitryserbin to be honest I'm not sure what the best path is. Official channels might be your best bet, our team is pretty much full to capacity at the moment though so I'm not sure what the response will be.

Sorry, I know that's not the most satisfying response, our hands are just somewhat tied

**Comment by bryanmacfarlane** [comment]
Note that it's not a blocker.  You can write the task in typescript and use the ToolRunner class to call pswh against a script you write for your task.  There's nothing preventing a task from carrying a powershell core script and running it.

**Comment by dmitryserbin** [comment]
Thanks @bryanmacfarlane this might be a good workaround until pswh is natively supported.

**Comment by leoniDEV** [comment]
Cant [this](https://devblogs.microsoft.com/powershell/introducing-powershell-as-net-global-tool/) help (and potentially speedup) with the implementation of the Powershel Core handler?

**Comment by shayki5** [comment]
> Note that it's not a blocker. You can write the task in typescript and use the ToolRunner class to call pswh against a script you write for your task. There's nothing preventing a task from carrying a powershell core script and running it.

Can you give an example please?

**Comment by dmitryserbin** [comment]
Is there any update on this? We can't really use `Invoke-VstsTool` or typescript `tool runner` because this method creates a new PowerShell session, which makes task parameters unacceptable in new scope - i.e. things like `Get-VstsInput` or `Get-VstsEndpoint` will not work. Not to mention task modules from `ps_modules` directory will not be available by default either.

**Comment by knom** [comment]
+1

**Comment by vtbassmatt** [comment]
Thanks for the discussion.

We're not planning to add any new PowerShell-based handlers, even PowerShell Core. Additional handlers complicate the story for other features like running inside containers. Every container would have to carry `pwsh` on the off-chance that a task written in PowerShell gets used in a pipeline.

The handler is just infrastructure. It doesn't have to be where the bulk of your work occurs. You can write a small amount of JavaScript to grab the task inputs, invoke your script with them as arguments, and handle exit codes. This has the benefit of working for any language you want to bring along: PowerShell, but also Python, Ruby, or a native executable (if you know which platforms your task needs to run on).

I haven't tested this code, but it would look something like:

```js
import tl = require('azure-pipelines-task-lib/task');
import tr = require('azure-pipelines-task-lib/toolrunner');

const firstVar = tl.getInput('firstVar');
const secondVar = tl.getInput('secondVar');

async function run() {
  let pwshPath: string = tl.which('pwsh', true);
  let pwsh = tl.tool(pwshPath);
  pwsh.arg('path/to/script.ps1');
  pwsh.arg(firstVar);
  pwsh.arg(secondVar);

  let options = <tr.IExecOptions> {
    failOnStdErr: false,
    // Direct all output to STDOUT due to Node's buffering strategy
    errStream: process.stdout, 
    outStream: process.stdout,
    ignoreReturnCode: true
  };

  let exitCode: number = await pwsh.exec(options);

  let result = tl.TaskResult.Succeeded;

  // Fail on exit code.
  if (exitCode !== 0) {
    tl.error(`Failed with exit code {exitCode}`);
    result = tl.TaskResult.Failed;
  }

  tl.setResult(result, null, true);
}
```

**Comment by dmitryserbin** [comment]
There must be a miscommunication of the requirements @vtbassmatt: we don't really ask for out-of-the-box pwsh support on _all type of agents_. All we need is support for task API to execute pwsh.exe (same as powershell.exe) - that's all. Let your customers worry about prerequisites and pwsh availability on the agents.

We are having **A LOT** of troubles running PWSH via JS or PowerShell 5 (I could easily bore you to death with details). The workaround you're recommending is extremely ugly and I cannot believe this is **official** Microsoft response. This may work for very basic PowerShell scripts, but not even close when we're dealing with complex solutions.

You guys already have `PowerShell` and `PowerShell3` handlers in the [task.json schema](https://github.com/microsoft/azure-pipelines-task-lib/blob/f2c40a3884f54bce5ec4531174ad5b1a721d0727/tasks.schema.json#L272) and I do not believe that one more handler type will give you so much troubles.

**Comment by vtbassmatt** [comment]
Please share details. If there are problems executing PowerShell from a Node-based task, then there are likely problems with other languages and systems as well. I can fix those.

The lack of desire to do another PowerShell handler is based on our experiences building the first two. Handlers come with higher expectations - it's very weird for a customer to download a task from the Marketplace only to encounter infrastructure errors trying to run it. The handler has to run on the agent host, on a same-OS container, and recently, on a different-OS container. We have to bring along the handler runtime with the agent, or know without a doubt it'll be there.

**Comment by dmitryserbin** [comment]
Thanks for getting back to me @vtbassmatt.

We're using self-hosted agents in our enterprise environment - same, as I believe, many other Microsoft customers. There's a lot of corporate bs why we're forced to do so - it's a topic for another conversation. For this reason, pre-installed PowerShell is not a problem for us (even if we use microsoft-agents, installing prerequisites is a separate concern).

In our case, we're successfully building in-house extensions and tasks to help with CI/CD in Azure DevOps. Most of our tasks are PowerShell-based running bespoke deployment framework module (50k+ lines of code) based on Az PowerShell modules to deal with Azure deployments.

Since Azure DevOps is our one and only CI/CD platform, we're basically stuck with PowerShell 5 technology and blocked from migrating out codebase to use PowerShell 6 or even 7 - just because pwsh handlers aren't supported.

We have managed to use JS/PowerShell 5 invoke method to run our deployment framework in pwsh instance, however it's not going to cut it and as there are some significant (for us at least) problems with this approach. So far we have discovered the following:

1) Complexity. Instead of simply running our code in task.ps1 we now have to split it in chunks. Separately initializing task parameters and service connections using VstsTaskSdk features in native PowerShell 5 session, then passing it through to pwsh runner to start another PowerShell 6 session. In some cases addressing this may require significant amount of code refactoring - often in a very hacky and ugly way. Not to mention backward comparability we still need to worry about - this adds another complexity layer. Simple things become very complicated.

2) Prerequisites. Basically, we loose ability to bring some modules with the task. Having another PowerShell session means that we need to worry about wiring and re-loading prerequisite modules as task instance with `ps_modules` isn't available. Also, some native things like pipeline variables and tokens are no longer available from new pwsh session - for some solutions this might be a blocker.

3) Exception handling. We're forced to parse output from `& pwsh 2>&1` line by line under PowerShell 5 session, reading `[System.Management.Automation.ErrorRecord]` types and formatting `$_.Exception.Message` using `Write-VstsTaskError`. Also rely on `LASTEXITCODE` - which is waaay too many assumptions. Basically, same as you guys do in [AzurePowerShellV4 task](https://github.com/microsoft/azure-pipelines-tasks/blob/121c26b940d65fe97215d334ccf63a615e409222/Tasks/AzurePowerShellV4/AzurePowerShell.ps1#L124). It's not for me to judge, but I would _let go_ the person who came up with this solution. It's ugly and unreliable.

4) Stdout handling. Since we're using pipe to run pwsh and parse errors, using `Write-Output` to print console output in our modules/scripts is no longer an option - we're forced to use [Write-Host](https://blogs.msdn.microsoft.com/timid/2014/03/25/scripting-best-practices-or-write-host-considered-harmful/) instead. We also loose ability to see anything external apps we execute using `&` (which we do a lot), for example `& nunit3-console.exe app.dll` or anything similar (unless we output it in a variable and then print with `Write-Host` - loosing ability to see live output from the app). On top of this, things like `Write-Warning` do not get recognized by pipelines anymore and displayed as plain text. We have to add some string parsing and output to Write-Host which extremely inconvenient (also doesn't work well with `Write-Progress`).

I am confident there's another 100+ issues we don't know about just yet. It's one thing after another. Bottomline, **nothing can replace native PowerShell handler**. We have to build a bicycle with crutches every time we wan't to use or do something very simple. Pwsh invoke method do work for simple script, but doesn't when you have more complex PowerShell solution - which is pretty much any enterprise organization.

**Comment by jessehouwing** [comment]
With regards to 3, have you tried issuing the formatted log commands directly from your own powershell libraries? 

The magic strings are explained here: 
https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md

But all the issues you are presenting are exactly why creating new powershell handlers are hard to make and hard to maintain. 

A workaround I've seen used, albeit pretty ugly too, is to call `cmd /c pwsh script.ps1`, funnily enough, cmd will normalize everything.

You can also initialize the current task like inside of the pwsh session. Since all communication with the host happens through environment variables, most functions will just work.  There is no direct communication between the lib and the agent through API connections.

Some things, like requesting a ClientOM may fail on powershell core, as these rely on the presence of the TFS/AzDevOps client object mobile binaries for your platform.

Not trying to discourage creation of a new handler, just trying to help in the interim.

**Comment by vtbassmatt** [comment]
Thanks for enumerating the difficulties, and I understand this isn't intended to be a complete list. The complexity angle definitely resonates.

It's a long shot but, could you by chance share the source of one of these tasks with me? Especially one that illuminates problems 2, 3, or 4. I have a few ideas in mind but am not sure if they'll hold up against the scope of your issues. My email is mattc@xbox.com.

**Comment by dmitryserbin** [comment]
Thanks for your reply @jessehouwing, here's my comments:

> With regards to 3, have you tried issuing the formatted log commands directly from your own powershell libraries?

This might be a good workaround, however we develop platform-agnostic code (i.e. out PowerShell-based framework), so it can be run locally on a Windows machine or in any other system. Everything related to Azure DevOps is decoupled and sits in the `task.ps1`. We could add extra condition logic into the core logger to do this stuff in Azure DevOps environment only, but this will introduce unnecessary complexity we're tying to avoid.

> But all the issues you are presenting are exactly why creating new powershell handlers are hard to make and hard to maintain.

I understand that, however you guys already have two PowerShell handlers. It's difficult for me to judge without looking into the implementation, but it feels like new PWSH handler would be very similar to existing `PowerShell3`, which means, if done right, there will be a lot of re-usable features/code.

> A workaround I've seen used, albeit pretty ugly too, is to call `cmd /c pwsh script.ps1`, funnily enough, cmd will normalize everything.

Will try that just for curiosity, thanks.

> You can also initialize the current task like inside of the pwsh session. Since all communication with the host happens through environment variables, most functions will just work. There is no direct communication between the lib and the agent through API connections.

This is where we're struggling as well when using integrated or user-specific service connections (for example task's `connectedService:AzureRM` and `Get-VstsEndpoint -Name SystemVssConnection` in PowerShell session). With proposed approach we have to initialize Azure endpoint in PowerShell session and pass it to PWSH as a parameter.

**Comment by dmitryserbin** [comment]
> It's a long shot but, could you by chance share the source of one of these tasks with me? Especially one that illuminates problems 2, 3, or 4. I have a few ideas in mind but am not sure if they'll hold up against the scope of your issues. My email is [mattc@xbox.com](mailto:mattc@xbox.com).

Sorry for taking ages to reply, I just came back from holiday and will send you some details as you asked within the next few days.

**Comment by vtbassmatt** [comment]
@dmitryserbin no worries, and that would be amazing. I had just sat down to play with this yesterday, but without a real-world example of some PowerShell someone wants to move, it feels like a toy. I'll be taking some time off over the holidays, but if you email me anything, I may log in and take a look anyhow.

**Comment by jikuja** [comment]
> Official channels might be your best bet, our team is pretty much full to capacity at the moment though so I'm not sure what the response will be.

Are there any existing requests on the official channels? Tied to find but the search functionality on https://developercommunity.visualstudio.com/ is really limited.


>  it's very weird for a customer to download a task from the Marketplace only to encounter infrastructure errors trying to run it. 

So true. I'm tired to see the following error messages after setting up tasks that are wrappers around the existing PowerShell Core code base:
> ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

The error message should be changed because most of the failing tasks I've used are PowerShell Core and the limitation comes from the task executor.
