### ISSUE TITLE
Exec ToolRunner against remote servers

### ISSUE THREAD

**Issue by ChristopherHaws** [microsoft/azure-pipelines-task-lib#54]
I was wondering if it is possible to provide a ToolRunner with remote machine information so that exec runs the tool on remote machines. It looks like this functionality exists for PowerShell tasks via `Invoke-RemoteDeployment` which is part of the module `Microsoft.TeamFoundation.DistributedTask.Task.Deployment.RemoteDeployment`.

If this hasn't been implemented yet, I would propose that an option `remote` be added to IExecOptions with the following syntax:

``` typescript
/**
 * Interface for exec remote options
 */
export interface IExecRemoteOptions {
    /**
     * List of machines to execute the command on. Can be IP Address, FQDN, or Machine Group Name
     * @type {string[]}
     */
    machines: string[];
    /**
     * Optional: The username to use when executing the command
     * @type {string}
     */
    username?: string;
    /**
     * Optional: The password to use when executing the command
     * @type {string}
     */
    password?: string;
    /**
     * Optional: Must be 'http' or 'https'
     * Default: https
     * @type {string}
     */
    protocol?: 'http' | 'https';
    /**
     * Optional: Whether or not the tools should run in parallel on the remote machines
     * Default: false
     * @type {boolean}
     */
    parallel?: boolean;
}
```

And its usage would be:

``` typescript
var tool = createToolRunner("foo.exe");
tool.exec({
    remote: {
        machines: ['127.0.0.1', 'server.remote.com', 'my-machine-group']
        username: 'username'
        password: 'password',
        protocol: 'https',
        parallel: true
    }
});
```

On Windows machines this could use WinRM similar to the `Invoke-RemoteDeployment` command. On Linux and Mac's it could use SSH. This would allow for tasks written in node to be able to target remote machines.
http://vsts-deploy-guide.readthedocs.org/en/latest/target-machines/

WinRM for Node:
https://www.npmjs.com/package/winrmjs

SSH for Node:
https://www.npmjs.com/package/node-ssh

**Comment by madhurig** [comment]
@ChristopherHaws: We don't have this ability in the ToolRunner but we released an SSH task that helps with deployments on Linux. Take a look to see if this meets your needs: https://blogs.msdn.microsoft.com/visualstudioalm/2016/07/30/ssh-build-task/ 

Thanks,
Madhuri

**Comment by ChristopherHaws** [comment]
I don't think that the use cases are the same. What I am talking about is making it so that people who are creating custom build tasks don't have to jump through hoops to execute commands on remote Windows machines. Currently it is possible with PowerShell via WinRM, however building tasks in Node.JS that are platform agnostic is extremely difficult. The only way I have been able to do it with the current tooling is to make separate scripts in PowerShell and Node, even though most of the logic is identical. This become a maintenance problem when the scripts get out of sync.

The SSH task is used for executing shell scripts that are part of your project against a machine. In other words, not for building additional reusable, cross platform, tasks.
