### ISSUE TITLE
Single quotes passed to line function is getting escaped for OSX/Linux

### ISSUE THREAD

**Issue by ajinkya599** [microsoft/azure-pipelines-task-lib#541]
### Environment
azure-pipelines-task-lib version: 2.0.5

### Issue Description

When there are `'` characters in an input, they are getting escaped for `OSX/Linux agents`.
As mentioned in [issue 10159](https://github.com/microsoft/azure-pipelines-tasks/issues/10159), the kubectl command with `'` in arguments input is [failing ](https://dev.azure.com/ajazdev/playground/_releaseProgress?_a=release-environment-logs&releaseId=8&environmentId=8)on Hosted Ubuntu 1604 agents:
![image](https://user-images.githubusercontent.com/11447401/58707678-3ad6bb00-83d3-11e9-9b0b-f706a4310c7c.png)

While the command when invoked from Ubuntu terminal succeeds:
![image](https://user-images.githubusercontent.com/11447401/58707610-1084fd80-83d3-11e9-862e-c1a0af467a2f.png)

The behavior of the task is the same, as when the `kubectl` command is invoked on Ubuntu terminal by escaping the `'` characters:
![image](https://user-images.githubusercontent.com/11447401/58707784-84bfa100-83d3-11e9-942b-02eac6fee30f.png)

The Kubernetes task [calls](https://github.com/microsoft/azure-pipelines-tasks/blob/030925eab74f375f0cc992e9983299400a8e7f4a/Tasks/KubernetesV1/src/kubernetescommand.ts#L20) the `line` method in `toolrunner` to add the arguments.

Note
### Expected behaviour

The argument should be passed without escaping the `'` characters.

### Actual behaviour

The `'` characters in the argument are escaped. This causes the `kubectl` command to fail, as it does not expect `'` characters in the `pod-name` input.

**Comment by damccorm** [comment]
Looks like this is more or less the same issue you're solving for double quotes in #511 - do you want to just add in logic to do the same thing with single quotes?

**Comment by ajinkya599** [comment]
Hey @damccorm, to me it seems more complicated than the other issue. There is no behavior change in terms of execution in #511. It involved only change in logging.

This one can be trickier, as it can potentially break other scenarios (where the expectation is that `'` would get escaped by default).

I would suggest to taking the two separately, and would be happy to give any inputs required from me on this one :)

**Comment by damccorm** [comment]
Ah I see, didn't quite read this closely enough the first time. Yeah, I'm a lot more hesitant to break compat.

Agreed on your assessment, lets definitely address this one seperately.

**Comment by damccorm** [comment]
Closing since we decided not to do this in #511
