### ISSUE TITLE
Cannot use task.setvariable to define variable containing "%3B".

### ISSUE THREAD

**Issue by cgranade** [microsoft/azure-pipelines-task-lib#542]
### Environment
azure-pipelines-task-lib version: 
```
Current agent version: '2.152.1'
```

### Issue Description
When attempting to use `##vso[task.setvariable]` to set a variable to a value containing a literal `%3B`, the variable is instead stored to a value containing `;` as per the unescaping rules at https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/node/taskcommand.ts#L83.

For instance, the following pipeline raises the issue:

```yaml

variables:
  Foo: Bar

pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: |
    echo ("vso[task.setvariable variable=Abc.Beans;]$(Foo)%" + "3Bdef")
    echo ("##vso[task.setvariable variable=Abc.Lolz;]$(Foo)%" + "3Bdef")
    echo "##vso[task.setvariable variable=Abc.Def;]$(Foo)%253Bdef"
    echo "##vso[task.setvariable variable=Abc.Things;]$(Foo)%25def"
  displayName: 'Run a one-line script'

- script: |
    echo '$(Foo)'
    echo "Something still else changed"
    echo '$(Abc.Beans)'
    echo '$(Abc.Def)'
    echo '$(Abc.Things)'
```

### Expected behaviour
```
echo "Something still else changed"
echo 'Bar%3Bdef'
echo 'Bar%253Bdef'
echo 'Bar%25def'
```

### Actual behaviour
```
echo "Something still else changed"
echo 'Bar;def'
echo 'Bar%253Bdef'
echo 'Bar%25def'
```

**Comment by damccorm** [comment]
That's by design - certain characters have to be syntactically reserved, `;` is one of them. To provide a way to get your variable to actually resolve to `;` we chose to use `%3B` since that's the URL safe encoding.

Basically we're choosing to reserve `%3B` instead of `;`.

Does that make sense?

**Comment by cgranade** [comment]
@damccorm Thanks for the quick response! That does make sense, but I'd have expected in that case that `%` itself would escape to `%25` such that I could embed a literal `%3B` as `%253B`. Thanks again for the help!

**Comment by damccorm** [comment]
Ah, I see - that makes more sense. Yeah, I think we should be doing that. I'll add a PR
