### ISSUE TITLE
Cannot define Azure Devops pipeline variables in format "Input.SomeKey"

### ISSUE THREAD

**Issue by SumiranAgg** [microsoft/azure-pipelines-task-lib#544]
**Issue Description:**
If pipeline variables contain something beginning with "Input.", the task-lib stores it into the vault and deletes it from envvar map. As such it is not available during task operations.

Why dont we have these predefined variable names something specific to tasks ? INPUT_ and SECRET_ are too generic keys which the customer might want to use as variables in his pipeline.

**Customer issue reference:** https://github.com/microsoft/azure-pipelines-tasks/issues/10589#event-2396140653

**Comment by stephenmichaelf** [comment]
As you can see [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch) there are some reserved prefixes:

```A few variable prefixes are reserved by the system and should not be used. These are: endpoint, input, secret, and securefile. Any variable which begins with one of these strings (regardless of capitalization) may not be available to your tasks and scripts.```

This is a core assumption throughout the entire codebase.

Closing as this is expected functionality.
