### ISSUE TITLE
How to obtain the full url of a nuget feed passed as task input

### ISSUE THREAD

**Issue by lukka** [microsoft/azure-pipelines-task-lib#548]
How to get the full publishing URL of a Nuget feed?

In my task.json i define this input:

```
{
      "name": "nugetFeed",
      "aliases": [
        "vstsFeed"
      ],
      "type": "pickList",
      "label": "Artifact feed to cache the built binaries:",
      "defaultValue": "",
      "helpMarkDown": "Specify where to cache the binaries built.",
      "required": "false",
      "properties": {
        "EditableOptions": "True"
      }
    },
...
  "dataSourceBindings": [
    {
        "target": "nugetFeed",
        "endpointId": "tfs:feed",
        "endpointUrl": "{{endpoint.url}}/_apis/packaging/feeds",
        "resultSelector": "jsonpath:$.value[*]",
        "resultTemplate": "{ \"Value\" : \"{{#if project}}{{{project.id}}}\\/{{/if}}{{{id}}}\", \"DisplayValue\" : \"{{{name}}}\" }"
    }
  ]
}
```

Using   `tl.getInput("nugetFeed");` I only get a guid.

What i want is to get the full URL like:
`https://pkgs.dev.azure.com/name/_packaging/feedname/nuget/v3/index.json
`

**Comment by jtpetty** [comment]
@lukka - I apologize for the delay in responding. I think the method you are looking for is `tl.getEndpointUrl("nugetFeed")`

**Comment by lukka** [comment]
@jtpetty using `tl.getInput("nugetFeed")` I get a GUID, is there any documentation about that return value? How to use this return value?

**Comment by jtpetty** [comment]
@lukka - `tl.getInput("nugetFeed") `will definitely return the GUID for the service connection. If you use `tl.getEndpointUrl("nugetFeed")` it will return the URL based on the GUID for the service connection

**Comment by jtpetty** [comment]
@lukka - Did this address your question?

**Comment by lukka** [comment]
yes, thanks a lot!
