### ISSUE TITLE
Versioning: extension vs. task vs. yaml

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-task-lib#552]
How does the versioning scheme work exactly?

Which version does the following yaml reference exactly:
```
steps:
- task: MyTask@0
```

* There is a three-part extension version number.
* There is a three-part task version number.
* It looks like you cannot write `- task MyTask@0.0.1` in the YAML

How do you separate 0.0.1 from 0.0.2?
Is it referencing the extension version or the task version?

Best regards,
D.R.

**Comment by stephenmichaelf** [comment]
This is referencing the task version number.

We only let you pin to major versions so this is "latest minor/patch with 0 major version".

This allows a balance of control over what task you're using while also letting tasks get (non breaking) improvements.

**Comment by damccorm** [comment]
See docs [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-versions)
