### ISSUE TITLE
Set icon for a task?

### ISSUE THREAD

**Issue by drauch** [microsoft/azure-pipelines-task-lib#554]
### Issue Description
I am able to set an icon for my whole extension in the `vss-extension.json`, however, my two tasks which are contained within the extension do not get this icon. How to set a proper icon for my two tasks? Is there a way to configure it in `task.json`?

### Expected behaviour
Task should have my extension's icon.

### Actual behaviour
Task is shown with generic icon:
![image](https://user-images.githubusercontent.com/1516470/61042510-a2215b00-a3d4-11e9-9bf7-109d6c5a7412.png)

Any help is appreciated, thank you!

Best regards,
D.R.

**Comment by stephenmichaelf** [comment]
You can see a sample folder structure here:

https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/ANTV1

You will want to add icon.png to the root of the task folder.

**Comment by drauch** [comment]
So I don't have to put the information anywhere, it is just called icon.png by convention?

**Comment by stephenmichaelf** [comment]
Correct :)

**Comment by drauch** [comment]
OK, great, thanks for your quick replies!

PS: maybe I've just overlooked it, if not: would be a great addition to the docs at https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops
