### ISSUE TITLE
"validation" field on task.schema.json

### ISSUE THREAD

**Issue by lucaslra** [microsoft/azure-pipelines-task-lib#555]
azure-pipelines-task-lib version: Not sure. The schema I am using is the master branch version

### Issue Description
"validation" field with regular expressions works perfectly! But it is not part of the schema or properly documented anywhere I could find.

### Expected behaviour
Documented field and added to the schema

### Actual behaviour
I can use the field, but I just learned about it by accident. It is a shame, because it is very useful! And improves the UX 500%

### Steps to reproduce
1. Create a new VSTS Extension
2. Add an input with a "validation" field
    ```json
    {
      "name": "inputName",
      "type": "integer",
      "....":"....",
      "validation": {
        "expression": "isMatch(value,'^([1-9]|[1-8][0-9]|9[0-9])$','IgnoreCase')",
        "message": "The number can only be between 1 and 99"
      }
    },
    ```
3. Deploy to a VSTS Project
4. Use the Task and fill in invalid input value
5. Magic happens!

Is there a particular reason for it not to be added?
And if so, couldn't we think of a `beta` schema with not fully implemented features?

**Comment by ranarn** [comment]
Any update on this?

**Comment by nexsodev** [comment]
Up
