### ISSUE TITLE
Semicolon-separated paths starting with ./ parsed incorrectly

### ISSUE THREAD

**Issue by bender2k14** [microsoft/azure-pipelines-task-lib#558]
### Environment
azure-pipelines-task-lib version: Unsure...current?

Whatever version is being used right now when I execute the task DotNetCoreCLIV2.  See my [initial bug report](https://github.com/microsoft/azure-pipelines-tasks/issues/11009) for this issue against DotNetCoreCLIV2.

### Issue Description
In an effort to improve readability, I prefer to start relative paths with `./`.  But when I combined two suchs paths withj a semicolon between, the function [`getPathInput`](https://github.com/microsoft/azure-pipelines-tasks/blob/9002e807e472a2f7ee77fadbba3bbff7cd6eadde/Tests-Legacy/lib/vsts-task-lib/task.ts#L277) does not return the correct value.

If I remove the initial `./` from my relative paths, then `getPathInput` behaves as expected.

### Steps to reproduce
1. Pick a task (such as DotNetCoreCLIV2) with a property (such as `searchPatternPack`) that is obtained (and partially altered) by [`getPathInput`](https://github.com/microsoft/azure-pipelines-tasks/blob/9002e807e472a2f7ee77fadbba3bbff7cd6eadde/Tests-Legacy/lib/vsts-task-lib/task.ts#L277)
2. Set the value of this property to `'./A/A.csproj;./B/B.csproj'`
3. Execute this task

### Expected behaviour
`getPathInput` returns the same string I specified as a property in some task.  It is also acceptable (but unnecessary I think and definitely unexpected to me) if it converts some relative paths into absolute paths.  It is also acceptable to standardize the path separator character.

An acceptable expected return value would be `d:\a\1\s\A\A.csproj;B\B.csproj`

### Actual behaviour
The actual return value is `d:\a\1\s\A\A.csproj;\B\B.csproj`.

### Logs
See also my [initial bug report](https://github.com/microsoft/azure-pipelines-tasks/issues/11009) for this issue against DotNetCoreCLIV2.

On input `'./A/A.csproj;./B/B.csproj'`, the relevant logs entries are
```
##[debug]searchPatternPack=d:\a\1\s\A\A.csproj;\B\B.csproj
...
##[debug]pattern: 'd:\a\1\s\A\A.csproj'
##[debug]expanding braces
##[debug]pattern: 'd:/a/1/s/A/A.csproj'
##[debug]findPath: 'd:\a\1\s\A\A.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]1 matches
##[debug]pattern: '\B\B.csproj'
##[debug]expanding braces
##[debug]pattern: '/B/B.csproj'
##[debug]findPath: '\B\B.csproj'
##[debug]statOnly: 'true'
##[debug]ENOENT
##[debug]found 0 paths
##[debug]applying include pattern
##[debug]0 matches
##[debug]1 final results
##[debug]Found 1 files
##[debug]--File: d:\a\1\s\A\A.csproj
```

On input `'A/A.csproj;B/B.csproj'`, the relevant log entries are
```
##[debug]searchPatternPack=d:\a\1\s\A\A.csproj;B\B.csproj
...
##[debug]pattern: 'd:\a\1\s\A\A.csproj'
##[debug]expanding braces
##[debug]pattern: 'd:/a/1/s/A/A.csproj'
##[debug]findPath: 'd:\a\1\s\A\A.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]1 matches
##[debug]pattern: 'B\B.csproj'
##[debug]expanding braces
##[debug]pattern: 'B/B.csproj'
##[debug]findPath: 'd:\a\1\s\B\B.csproj'
##[debug]statOnly: 'true'
##[debug]found 1 paths
##[debug]applying include pattern
##[debug]adjustedPattern: 'd:\a\1\s\B/B.csproj'
##[debug]1 matches
##[debug]2 final results
##[debug]Found 2 files
##[debug]--File: d:\a\1\s\A\A.csproj
##[debug]--File: d:\a\1\s\B\B.csproj
```

**Comment by jtpetty** [comment]
@bender2k14 - I have looked into this and I believe it is a misconfiguration of the the task itself. I have reopened your original issue against the task and supplied some relevant information. Hopefully that will be enough to get a fix in soon.
