### ISSUE TITLE
DatasourceBindings

### ISSUE THREAD

**Issue by balfa666** [microsoft/azure-pipelines-task-lib#559]
Hello, Is there a way to do a POST in the datasourcebindings section of the task.json?

**Comment by damccorm** [comment]
Hey @balfa666 sorry for the slow response. I'm not totally sure what you're asking - could you provide a little more context on your use case?

**Comment by balfa666** [comment]
I didn't see any mention of being able to do a POST only a GET when using datasourcebindings.

**Comment by damccorm** [comment]
Sorry, I think I was a little unclear - I more meant could you give an example of why you would want to do a POST?

With that said, I think in retrospect I might actually recommend that you ask this question in https://github.com/microsoft/azure-pipelines-extensions/ - that's where [docs on datasource bindings](https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/dataSources.md) live, so they'll probably be both better equipped to answer your question there, and will be able to update docs accordingly.

Seem fair?

**Comment by balfa666** [comment]
Yes, i will leave a comment in that github. no problem.

**Comment by damccorm** [comment]
Cool, thanks. Closing here in that case, feel free to comment if you think this one should be reopened
