### ISSUE TITLE
Get-VstsInput Powershell Core Support???

### ISSUE THREAD

**Issue by TechnologyAnimal** [microsoft/azure-pipelines-task-lib#565]
I created a custom azure devops extension that manages all of our terraform deployments.  The only steps for our development teams to deploy their application and all of the supporting cloud infrastructure is to point the extension to the main.tf file in their code repo and map a variable group that's used to set environment variables.

I recently converted all of the scripts inside the extension to use Powershell core.  Testing on a private windows build server works perfectly, but I cannot get the extension working on a Linux VM running Powershell Core.

It seems that my issue is the **VstsTaskSdk is only supported on Windows**.  Is there another module I can use that gives me the **Get-VstsInput** cmdlet or are there any other alternative solutions that would allow me get user input from a custom extension that can run on a linux VM or container?

Any help would be greatly appreciated.

Here is the error I am getting:

> 2019-08-28T04:58:22.6199963Z ##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

**Comment by stephenmichaelf** [comment]
> are there any other alternative solutions that would allow me get user input from a custom extension that can run on a linux VM or container

Hey @TechnologyAnimal , Our recommendation for writing cross platform tasks is to use Node.
