### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by DanielHabenicht** [microsoft/azure-pipelines-task-lib#568]
### Environment
azure-pipelines-task-lib version: current

### Issue Description
There is no documentation on how to use the node lib for common scenarios. 

### Expected behaviour
There is clear documentation with examples for the most common (or all) commands. 
1. for Example the `tl.exec()` command
2. for getting `connectedService` secrets, handling and using them
3. general construction of the UI and its features

Just pointing to working code or config files is not documentation. 

I am sorry if something like this already exists, but I was unable to find it. It's late over here so please point to the right links.

**Comment by TeaEnthusiast** [comment]
+1 for this. Also perhaps docs on how these things are tested.

I'm trying to use the pipeExecOutputToTool and the testing of it has been pretty hard without docs.

**Comment by DanielHabenicht** [comment]
not stale :)

**Comment by DanielHabenicht** [comment]
Not stale!

**Comment by mindlessroman** [comment]
+1 For this - I'm trying to figure out how to use any `mock-answer` functionality but the docs do not help fill this knowledge gap in. I've been trying to suss out some clues from someone else's issue (#469 ) but that is _not_ how someone should try to figure out how this works. @stephenmichaelf - is there any movement on getting more documentation here?

**Comment by DanielHabenicht** [comment]
not stale

**Comment by mindlessroman** [comment]
not stale

**Comment by DanielHabenicht** [comment]
can you reopen too?

**Comment by paule96** [comment]
the docs folder is [here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/azure-pipelines-task-lib.md). That has the most documentation for the functions of `tl` or `task` (depends on your import?)

But it missing for example the `connectedService` mentioned by @DanielHabenicht.

So it's missing something functions.
Also the mocking stuff mentioned by @mindlessroman isn't documented there.

**Comment by DanielHabenicht** [comment]
Yep, that's basically what you can derive from going through the source-code...

**Comment by mindlessroman** [comment]
Sorry about the `not stale` miss. I got the notification too late. I also don't have the ability to reopen the issue @DanielHabenicht :( - I would if I were able. @stephenmichaelf or someone on the team may be able to revive?

@paule96 those docs you linked are (I believe) taken straight from the source code and do not elaborate much further.
