### ISSUE TITLE
Migrating to Az Module 

### ISSUE THREAD

**Issue by Adikota** [microsoft/azure-pipelines-task-lib#571]
We are in the process of converting the AureRM to Az Module on our TFS Build Servers. While looking for any dependecies for AzureRM, we have found that the importFunctions.ps1 in VstsAzureHelpers they are references to AzureRM and AzureRM cmdlets.

Is there an update scheduled to have the VstsAzureHelpers  to use Az Module?

**Comment by stephenmichaelf** [comment]
That [file](https://github.com/microsoft/azure-pipelines-tasks/blob/aefe05fe69ada9d8180943b7e8d4e66c4680eaf7/Tasks/Common/VstsAzureHelpers_/ImportFunctions.ps1) exists in the tasks repo, we should file this issue there.

Also note that common is used only for in the box tasks (tasks that ship inside Azure Dev Ops).
