### ISSUE TITLE
v2.9.2 additional folders break dependent builds on windows

### ISSUE THREAD

**Issue by davidknise** [microsoft/azure-pipelines-task-lib#574]
### Environment
azure-pipelines-task-lib version: v2.9.2

### Issue Description
We had our package.json set to ^v2.7.7, so we automatically received the v2.9.2 package when it was shipped Friday. This includes a _download/archive folder of nested node_modules folders that exceeds 256 character file paths. When our build copies these files or attempts to delete the folder on Clean, it fails.

### Expected behaviour
npm install azure-pipelines-task-lib --production only includes necessary files

### Actual behaviour
npm install azure-pipelines-task-lib --production includes additional files that are longer than 256 characters, breaking some copy/clean up build steps on dependent Windows consumers

### Steps to reproduce
1. Install azure-pipelines-task-lib on Windows (anywhere)
2. Open a File Explorer to the folder
3. Attempt to delete the folder
4. Observe errors

### Mitigation
We updated our build to hard reference v2.8.0. Non-blocking, no rush.

**Comment by damccorm** [comment]
Hey, sorry we didn't close the loop here - we published 2.9.3 to fix this a little while back. I'm going to close here, if this is still causing issues please comment and we can reopen
