### ISSUE TITLE
Pre-render task.json

### ISSUE THREAD

**Issue by pilarragorri** [microsoft/azure-pipelines-task-lib#578]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
This is a question/request for help, is there any way to render the task.json? I want to be able to check how the task I'm creating looks like before uploading it to AZ Devops

### Steps to reproduce
1. 
2. 
3. 
4. 
5.

**Comment by damccorm** [comment]
Not sure I understand the question - are you saying you want to see how the task.json will show up in the visual editor?

**Comment by pilarragorri** [comment]
Yep, exactly that

**Comment by damccorm** [comment]
Just trying to understand your use case a little better

**Comment by damccorm** [comment]
Closing since we don't currently have plans to do this - happy to reopen/continue the conversation if you have more thoughts
