### ISSUE TITLE
What is the proper way to authenticate within custom build task

### ISSUE THREAD

**Issue by eric-labelle** [microsoft/azure-pipelines-task-lib#579]
I found the [following issue](https://github.com/Microsoft/azure-pipelines-tasks/issues/6793#issue-308393012) by @gregpakes and had the exact same question which led to no answer other than it should be asked on this repo, so here it is.

Would it be possible to have a clear guide on how to get the access token to access Azure REST API? 

* Hosted Microsoft Agent (macOS)
* Custom build task

I tried with the SystemVssConnection `getEndpointAuthorizationParameter('SystemVssConnection', 'AccessToken', false);` and it's working but [official documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken) mention that we have to enable oauth on the job and get the token from `System.AccessToken`. 
I am confused on which way to use in my custom task I am developing. vssconection would be much more straight forward as I would not have to mention to enable oauth access to use my task.

Thanks

**Comment by jessehouwing** [comment]
Tasks have explicit access to the oauth token through the `getEndpointAuthorizationParameter('SystemVssConnection', 'AccessToken', false);`. 

Only when a pipelines author wants to pass the access token to a custom script or an executable etc, must they enable access to the token outside of the more trusted task context.

**Comment by eric-labelle** [comment]
Ok thanks for the confirmation for VSS. Is there a way to mock this for local use?
With `tl.getVariable("System.AccessToken")` I used to be able to mock it when running outside of the azure environment with `process.env.SYSTEM_ACCESSTOKEN = "mylocalauthtoken"` but not sure how to do that with the VSSCONNECTION's AccessToken since it's not a variable.

**Comment by jessehouwing** [comment]
Not 100% sure. I think it's along these lines:

```
ENDPOINT_URL_VSSCONNECTION=https://dev.azure.com/account
ENDPOINT_AUTH_VSSCONNECTION={ "parameters": { "apitoken": "token", "username": "user", "password": "password" }, "Scheme": "basic" }
```

**Comment by eric-labelle** [comment]
Yeah I found several task using something like that `process.env['ENDPOINT_AUTH_SYSTEMVSSCONNECTION'] = "{\"parameters\":{\"AccessToken\":\"token\"},\"scheme\":\"OAuth\"}"` but I must be missing something because it always give me the same error when running locally with `node index.js`. I changed it for your version but still, same error.

**Error:**
`Endpoint auth data not present: SystemVssConnection`

**Logs:**
```
##vso[task.debug]agent.TempDirectory=undefined
##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading ENDPOINT_AUTH_VSSCONNECTION
##vso[task.debug]loading INPUT_ORGANIZATION
##vso[task.debug]loaded 2
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]Agent.SkipCertValidation=undefined
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Endpoint auth data not present: SystemVssConnection
##vso[task.complete result=Failed;]Endpoint auth data not present: SystemVssConnection
```

**Comment by jessehouwing** [comment]
From other logs, you could try setting:

```
ENDPOINT_AUTH_SYSTEMVSSCONNECTION 
ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION 
ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
```

This is what the old SDK used.

**Comment by eric-labelle** [comment]
Awesome, just got it. My second error was a mistyping.
Turns out I only needed to replace `process.env.SYSTEM_ACCESSTOKEN` by `process.env.ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN`.

**OLD**
```
process.env.SYSTEM_ACCESSTOKEN="" 
```
then the following code to get the authHandler finds it's token
```
let authToken = tl.getVariable("System.AccessToken")
let authHandler = azdev.getPersonalAccessTokenHandler(authToken);
```
**NEW**
```
// use: az login
// then: az account get-access-token | grep "accessToken"
process.env.ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN="" 
```
then the following code to get the authHandler finds it's token
```
let authToken = tl.getEndpointAuthorizationParameter('SystemVssConnection', 'AccessToken', false);
let authHandler = azdev.getPersonalAccessTokenHandler(authToken);
```

Thank you for your help!!

**Comment by eric-labelle** [comment]
Hey @jessehouwing , one more question for you.. I swapped from `System.AccessToken` to `SystemVssConnection` and everything works well locally and in pipeline using **Basic Editor** but it fails when I try the task using the **YAML pipeline**. 

```
##[debug]agent.TempDirectory=/Users/runner/runners/2.159.2/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading SECRET_AZURE_API_PAT
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 4
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]System.TeamProject=
##[debug]task result: Failed
##[error]Endpoint auth data not present: SystemVssConnection
##[debug]Processed: ##vso[task.issue type=error;]Endpoint auth data not present: SystemVssConnection
##[debug]Processed: ##vso[task.complete result=Failed;]Endpoint auth data not present: SystemVssConnection
``` 

I know we had to add `env: SYSTEM_ACCESSTOKEN: $(System.AccessToken)` with the predefined variable, but since SystemVssConnection is documented nowhere, I'm not sure what's missing for YAML.

There is mention on how to use a _custom service connection_ [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection) but I figured since this one is built-in I don't have to specify this.

Thank you for your time!

**Comment by jessehouwing** [comment]
I'm not aware of any special treatment needed for YAML.
