### ISSUE TITLE
FindMatch() not working if pattern contains box bracket characters

### ISSUE THREAD

**Issue by vinodkumar3** [microsoft/azure-pipelines-task-lib#585]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
FindMatch() is unable to find matching pattern if input pattern contains box bracket ('[' or ']') characters.

### Logs
Logs are attached with this [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11673).

**Comment by damccorm** [comment]
We use minimatch to find things. I believe `[` and `]` are special characters, so escaping should fix the problem

**Comment by vinodkumar3** [comment]
@damccorm 
Tried modifying the task and found out that in case of special characters, escaping is working with Ubuntu agents but not with Windows. Seems something related to back or forward slashes in file paths.
I can see a related issue https://github.com/NuGet/Home/issues/3584 with Glob pattern.

**Comment by damccorm** [comment]
Could you share your repro? Minimatch should be able to handle that I believe, if I'm understanding the issue correctly.

**Comment by damccorm** [comment]
@vinodkumar3 any update?

**Comment by vinodkumar3** [comment]
PFA logs with updated ARM task (added modification of escaping special characters in file path, '[' & ']' in this example) where Ubuntu is correctly finding the path but Windows doesn't.

[ububtu-escape.zip](https://github.com/microsoft/azure-pipelines-task-lib/files/3840603/ububtu-escape.zip)
[windows-escape.zip](https://github.com/microsoft/azure-pipelines-task-lib/files/3840604/windows-escape.zip)

**Comment by damccorm** [comment]
It looks to me like you're escaping incorrectly on windows. 
On Ubuntu, the pattern is: `/home/vsts/work/1/s/a \[abc\] Subscription Deploy/resourcegroup.json`
On windows, its: `d:\a\1\s\a \[abc\] Subscription Deploy\resourcegroup.json`

Note that in the windows version, the way you currently have it escaped there's no way to distinguish between a path seperator (`\`) and the escaping backslash.

With that said, escaping minimatch on Windows is weird, see - https://github.com/isaacs/node-glob/issues/212. We have docs on how to do this [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops#escaping).

**Comment by vinodkumar3** [comment]
@damccorm 
Thanks for pointing me to the right documentation. This is something I was missing. You may close the issue now.
