### ISSUE TITLE
Add logging to the task lib?

### ISSUE THREAD

**Issue by simchev** [microsoft/azure-pipelines-task-lib#586]
From https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md, I see that it's possible to print to stdout with a command to log warnings in this format "##vso[task.logissue]error/warning message".

Is there a reason this is not available in the lib? I know that the lib is doing something similar to setup variables.

Maybe I just missed it.

**Comment by damccorm** [comment]
We do have it - https://github.com/microsoft/azure-pipelines-task-lib/blob/3183fa8c256b504b875022c0d20b5355b89459f9/node/task.ts#L1997

**Comment by simchev** [comment]
Then it should probably be added in the doc?

**Comment by damccorm** [comment]
The doc provides the commands and is agnostic of this library.

**Comment by simchev** [comment]
So you're saying there's no official doc for this lib? Or at least nothing complete? I'm quite surprised, it seems very unlike Microsoft. If you keep adding functions to this and don't document it somewhere, nobody other than the devs will know they exist, which is not the purpose of this lib.

**Comment by damccorm** [comment]
Ah - I didn't see that it was missing from those docs, was looking at the link from your original comment.

I agree, we should add it there - want to open a PR? Or I can if you don't have the time right now

**Comment by simchev** [comment]
Sure, I can do that.

**Comment by simchev** [comment]
Honestly I'm quite unfamiliar with the project, I'm just developing an extension at the moment. Could you just confirm if it's generated from the source (I see some doc in the source files and azure-pipelines-task-lib.json) or if I just have to manually edit the doc?

**Comment by damccorm** [comment]
Yeah. Doing some digging, I've never actually gened these before, but it looks like the generation code isn't in great shape and won't work out of the box. You can dig into that further, or create another issue for it and I'll dig in further
