### ISSUE TITLE
Errors on compilation of doc generation tools, unable to generate doc

### ISSUE THREAD

**Issue by simchev** [microsoft/azure-pipelines-task-lib#587]
I am unable to generate the docs using the scripts in node/docs. More specifically, I get errors when compiling node/docs in the file TypeScriptSourceToJson.ts. If I ignore compiler errors, the gendocs.js script still fails.

**TypeScriptSourceToJson.ts errors on compilation**:
TypeScriptSourceToJson.ts(29,9): error TS4104: The type 'readonly SourceFile[]' is 'readonly' and cannot be assigned to the mutable type 'SourceFile[]'.
TypeScriptSourceToJson.ts(103,73): error TS2554: Expected 1 arguments, but got 0.
TypeScriptSourceToJson.ts(159,91): error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.
TypeScriptSourceToJson.ts(179,9): error TS4104: The type 'readonly Symbol[]' is 'readonly' and cannot be assigned to the mutable type 'Symbol[]'.
TypeScriptSourceToJson.ts(188,55): error TS2554: Expected 1 arguments, but got 0.
TypeScriptSourceToJson.ts(196,58): error TS2554: Expected 1 arguments, but got 0.
TypeScriptSourceToJson.ts(206,55): error TS2554: Expected 1 arguments, but got 0.
TypeScriptSourceToJson.ts(214,39): error TS2339: Property 'Export' does not exist on type 'typeof NodeFlags'.

**"node gendocs.js" exception (failing because of TypeScriptSourceToJson)**:
var superType = typeChecker.getTypeAtLocation(superTypeNode);
                                        ^

TypeError: Cannot read property 'getTypeAtLocation' of undefined
    at ...\azure-pipelines-task-lib\node\node
_modules\typescript\lib\typescript.js:114423:41
  [...]
    at visit (...\azure-pipelines-task-lib\no
de\docs\TypeScriptSourceToJson.js:136:8)

**Note**: Doc generation needed to include some of the latest additions.

**Comment by damccorm** [comment]
Fixed by #598
