### ISSUE TITLE
Cache user data between builds

### ISSUE THREAD

**Issue by mauleb** [microsoft/azure-pipelines-task-lib#590]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
Howdy, not an issue but a inquiry. Is it currently possible to cache runtime generated data such that it is accessible between builds? Y'all have a page in your general pipelines documentation about [pipeline caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#using-the-cache-task) which is the behavior I am trying to utilize in some of our custom tasks. Is it possible to run other tasks as sub processes within a custom task or some other way to implement caching?

**Comment by stephenmichaelf** [comment]
Hey @mauleb what kind of data are you trying to cache between builds?

> Is it possible to run other tasks as sub processes within a custom task or some other way to implement caching?

No this is not possible to do today.

**Comment by mauleb** [comment]
One example would be caching node js node modules between builds using a package-lock as a cache key.

**Comment by damccorm** [comment]
As far as I know, we don't currently support any caching primitives for tasks to use, we require users to cache things themselves with the caching task. @fadnavistanmay, could you fact check me on that one? Do you know if we're planning on doing anything like that?

**Comment by fadnavistanmay** [comment]
@damccorm - correct. @mauleb - If you want to cache between builds, you could use the Pipeline Caching task, there are bunch of folks caching the node_modules between builds. Are you facing difficulty using the Cache task?
