### ISSUE TITLE
How to set variable in unit test of task

### ISSUE THREAD

**Issue by CodeTroopers** [microsoft/azure-pipelines-task-lib#593]
I try to set variables before run a task in a unit test

### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
I tried to set variables in the unit test with
```
import * as fs from 'fs';
import * as path from 'path';
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import { TaskLibAnswers } from 'azure-pipelines-task-lib/mock-answer';

const task: TaskMockRunner = new TaskMockRunner(taskPath);
task.setInput('excelFilePath', excelFilePath);
task.setVariableName('Build.BinariesDirectory', __dirname);
task.setVariableName('Product.Version', '0.1.0');

// Mock answer for excel file path
let answers: TaskLibAnswers = <TaskLibAnswers>{
	"checkPath": {
		[excelFilePath]: fs.existsSync(excelFilePath)
	}
};
task.setAnswers(answers);

task.run();
```

And in the task i get variables in run function with :
```
import { TaskResult, VariableInfo, getPathInput, setResult, getVariables } from 'azure-pipelines-task-lib/task';
...
let variables: VariableInfo[] = getVariables();
```
but the array is always empty

### Expected behaviour
The variables array should contains 'Build.BinariesDirectory' and 'Product.Version'

### Actual behaviour
The array is always empty
I also tried with:
```
task.setVariableName('BUILD_BINARIESDIRECTORY', __dirname);
task.setVariableName('PRODUCT_VERSION', '0.1.0');
```
or
```
process.env['Build.BinariesDirectory'] = __dirname;
process.env['Product.Version'] = '0.1.0';
```
or
```
process.env['BUILD_BINARIESDIRECTORY'] = __dirname;
process.env['PRODUCT_VERSION'] = '0.1.0';
```

**Comment by jtpetty** [comment]
@CodeTroopers - task.setVariableName() is for setting task variables which have a different scoping than variables.

I think what you want to use is the setVariable() method as defined in tasks.ts

**Comment by CodeTroopers** [comment]
Sorry, I don't understand because setVariable doesn't exist in mock-task and i can't use setVariable from task.js :

In my test, when i set input only then excel file path is correctly setted for the task :
```
import path from 'path';
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';

const taskPath = path.join(__dirname, "../index.js");
const excelFilePath = path.join(__dirname, 'resources/InstallerFiles.xlsx');

// Mock task
const task: TaskMockRunner = new TaskMockRunner(taskPath);
task.setInput('excelFilePath', excelFilePath); 
```

If i use setVariable from task.js, then excel file path is not setted for the task  :
```
import path from 'path';
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';
import { setVariable } from 'azure-pipelines-task-lib/task';

const taskPath = path.join(__dirname, "../index.js");
const excelFilePath = path.join(__dirname, 'resources/InstallerFiles.xlsx');

// Mock task
const task: TaskMockRunner = new TaskMockRunner(taskPath);
task.setInput('excelFilePath', excelFilePath);

setVariable('Build.BinariesDirectory', __dirname);
setVariable('Product.Version', '0.1.0');
```

output :`##vso[task.issue type=error;]Input required: excelFilePath`

**Comment by jtpetty** [comment]
instead of just importing setVariable, try importing the tasklib like:


```
import path from 'path';
import tl = require('azure-pipelines-task-lib/task');
import { TaskMockRunner } from 'azure-pipelines-task-lib/mock-run';

const taskPath = path.join(__dirname, "../index.js");
const excelFilePath = path.join(__dirname, 'resources/InstallerFiles.xlsx');

tl.setVariable('Build.BinariesDirectory', __dirname);
tl.setVariable('Product.Version', '0.1.0');

// Mock task
const task: TaskMockRunner = new TaskMockRunner(taskPath);
task.setInput('excelFilePath', excelFilePath);
```

**Comment by CodeTroopers** [comment]
@jtpetty Happy new year and sorry for the delay
Importing the tasklib has no effects, I have the same error

> ##vso[task.issue type=error;]Input required: excelFilePath

**Comment by jtpetty** [comment]
@CodeTroopers - Is your task code accessible that I could clone and debug on my end?

**Comment by CodeTroopers** [comment]
The repository is [here](https://github.com/CodeTroopers/BuildExtensions)
Say me if you need more...

**Comment by jtpetty** [comment]
Ok, I found one issue. setVariable/getVariable/getVariables is for variables set by the agent. 

I think what you want is setVariableName/getTaskVariable, but there was a bug with the setVariableName in the mock task runner where it was not transforming environment variable name to what the getTaskVariable was expecting. There is not an equivalent getTaskVariables() method that will return all of the task variables.

To work around the bug for now:

in your test:
```task.setVariableName('Product_Version', '0.1.0')```

in your index.ts
```getTaskVariable('Product.Version')```

**Comment by CodeTroopers** [comment]
@jtpetty Ok, thanks for your help
But i'm not sure to undertstand. 

> I think what you want is setVariableName/getTaskVariable

**My task currently works fine** with `getVariables`. I use it in builds for production releases. 
Our developers can create Excel files to create directories to deploy.
They can use predefinned variables of build or agent _(like $(Build.BinariesDirectory), $(Agent.WorkFolder), $(Agent.ToolsDirectory), $(Build.Repository.LocalPath), $(Build.ArtifactStagingDirectory))_ or custom variables _(like $(Product.Version), $(Product.Name), $(Product.Manufacturer))_ to define source paths or target paths. I cannot know the variables that will be used in the excel file.

 My problem is only for unit tests, where i can not set variables correctly

**Comment by jtpetty** [comment]
ok, I think I understand now. I have a work around for you. The issue appears that when you use a method from task-lib in your unit test, it does some initialization and then the mocking for task.setInput no longer works.

Here is a work around to set the variables and have getVariables() return the right thing:

```
process.env['PRODUCT_VERSION'] = '0.1.0';
process.env['BUILD_BINARIESDIRECTORY'] = __dirname;
process.env['VSTS_PUBLIC_VARIABLES'] = '["Product.Version","Build.BinariesDirectory"]';
```

**Comment by jtpetty** [comment]
@CodeTroopers - Did this address your problem?

**Comment by CodeTroopers** [comment]
Yes, thanks for your help
