### ISSUE TITLE
TLS 1.2 issues on .NET 4.5 agents

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-task-lib#596]
It looks like the Microsoft tasks have "patched" the SecurityProtocol setting:
https://github.com/microsoft/azure-pipelines-tasks/pull/6905

This means that every other task author must steal this file. Any chance this can be merged into the PowerShell Task Library and be auto-initialized? 

Or can the agent perform this for each powershell execution handler initialization? It feels weird that it's a helper module in the tasks repo, instead of a proper fix in the agent or the lib.

**Comment by jessehouwing** [comment]
Yes

**Comment by vtbassmatt** [comment]
@damccorm the bot closed this even after Jesse responded to its comment request. Thoughts?

@stephenmichaelf what should we do here?

**Comment by damccorm** [comment]
Hm, apparently stale [doesn't respect comments](https://github.com/actions/stale/issues/21) (I had thought it did) - we can either remove the configuration for now or just manually unlabel any that come in like this. I get notifications for comments, so I can handle doing that for now.

**Comment by vtbassmatt** [comment]
Closing stale issues is great, wouldn't want to lose that. If it becomes a burden on you, then we could automate with another Action.

**Comment by damccorm** [comment]
> Closing stale issues is great, wouldn't want to lose that. If it becomes a burden on you, then we could automate with another Action.

Yeah, let's see. It looked like they wanted to fix the issue I linked to, so may be a non-issue. Worst case, I might follow up in that repo with a PR.

**Comment by damccorm** [comment]
Hm, the bot was persistent here since we didn't remove the stale label. I think in theory we should pick up changes from the action itself to fix this automatically though, so lets see if the stale label gets removed automatically next time it runs

**Comment by jessehouwing** [comment]
This is still pretty much valid.

**Comment by vtbassmatt** [comment]
@stephenmichaelf is this tractable for us to take in the lib? If so, we can talk offline about how to staff it.
