### ISSUE TITLE
Adding a succeeding failure unit-test to a custom task fail Azure DevOps pipeline

### ISSUE THREAD

**Issue by springcomp** [microsoft/azure-pipelines-task-lib#603]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description

I’m trying to build a very simple task that compute a valid version number based upon the current date/time.

I’m following the instructions on the [Add a build or release task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops) page and am trying to run unit-tests from an Azure DevOps pipeline.

Obviously, because there is _failure_ test, I’m getting the failed output of the task in the failure test, like so:

![image](https://user-images.githubusercontent.com/8488398/72253351-a76c9600-3601-11ea-9ec0-a668183913ef.png)

However, because this is a custom DevOps task, it includes the `#vso[task.issue type=error;]` pattern as part of the failing test output. That pattern fails the Azure DevOps build:

### Actual behaviour

![image](https://user-images.githubusercontent.com/8488398/72253622-43969d00-3602-11ea-8528-6cf12deab883.png)

Is there a way to prevent the task from emitting output during unit-testing.
I probably could do it by supplying a custom input and change the code of my tasks but I wanted to know if there was a solution you had in mind.

**Comment by mcafaro** [comment]
Same question, although it looks like you've got an assertion error as well. It must be possible because these types of neg tests are all over https://github.com/microsoft/azure-pipelines-tasks.

**Comment by mcafaro** [comment]
I discovered my issue. You need to make sure you call `mocha` with the path to the `suite.js`. If you just `cd` in to the test directory and call `mocha`, it will spit out all of the `##vso` lines.

@springcomp , you appear to be correctly calling `mocha` with the path to the `suite.js`, but you have an assertion error.

**Comment by jtpetty** [comment]
@springcomp - Are you still having issues with your test?

**Comment by springcomp** [comment]
Yes I do.

As far as I can tell, there are no errors in my unit-tests.
This assertion only happens on Azure DevOps.

I noticed that the official tasks unit-tests are run using `makejs` and not by running `mocha` directly.
I'm almost certain that my analysis stands. I'll try and have some time this week to switch my unit-tests to use `makejs` and report if it makes a difference, as I suppose it will.

Over the week-end, I'll try and setup running the unit-tests via AppVeyor and hope to prove that there really is an interaction between the outputs of my failure tests and the way they are interpreted by the DevOps pipelines.

**Comment by springcomp** [comment]
I going ahead and closing this issue as I don’t have time to work on this.

**Comment by sthussey** [comment]
I'm hitting this same issue. Looking through https://github.com/microsoft/azure-pipelines-tasks I don't see anything different they are doing when running `mocha` than I do in my CI pipeline. Could the proper pattern for running expected failure unit tests for a custom task be documented somewhere?

**Comment by springcomp** [comment]
Going back to this issue now, I can confirm this is still not solved.
Would be great to have official guidance for running failure unit tests in Azure DevOps.
