### ISSUE TITLE
How can I call a task from my own custom task

### ISSUE THREAD

**Issue by BSanchidrian** [microsoft/azure-pipelines-task-lib#604]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description

Hello everyone, I'm creating a pipeline task and I wanted to know whenever is possible to call/invoke another task.

For example:
I'm the custom task I'm writing I need to login into a Docker registry using a predefined Azure Service Connection. The task [Docker@2](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/DockerV2) already provides that functionality but seems like the only way of using it would be to copy and include all of its source code into my own repository. That sounds like a terrible solution.

Does anyone on here knows if it is possible or is there any workaround?

Thanks in advance

**Comment by damccorm** [comment]
Hey @BSanchidrian - there's not a way to invoke a task from another task. The idiomatic way to do this would be to publish a shared npm package that both tasks rely on. You could file an issue in the [tasks repo](https://github.com/microsoft/azure-pipelines-tasks) asking them to do that, though I don't know of us doing that with any of our first party tasks
