### ISSUE TITLE
"success:true" printed when reading output from mock runner task

### ISSUE THREAD

**Issue by jepetty** [microsoft/azure-pipelines-task-lib#605]
### Environment
azure-pipelines-task-lib version: 2.7.7

### Issue Description
I have a task that reads JSON from the output of a task invocation, and then parses it to assign variables. In the test [mock-runner](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/mock-toolrunner.ts#L253) "success:true" is printed, which than fails when I try to parse it as JSON.

Why is this printed? Can there be a way to opt out so I can still read the output of a task from a test?

**Comment by jtpetty** [comment]
@jepetty - Can you share your test code? Have you tried updating to the latest task-lib which is 2.9.3?

**Comment by jepetty** [comment]
Yes, I've updated the version of task-lib.

My code is roughly as follows. In production, I call foo.exe which is expected to print a JSON object to stdout. In test code, 
```ts
exec: {
   'foo.exe': {
       code: 0,
       stdout: "{\"result\": \"true\"}"
   }
}
```
The output of that (i.e. "{\"result\": \"true\"}") is then parsed as `JSON.parse(output.toString())`.

When I run the test code mocking this, it fails with
```
##vso[task.issue type=error;]SyntaxError: Unexpected token s in JSON at position 0
##vso[task.complete result=Failed;done=true;]SyntaxError: Unexpected token s in JSON at position 0
```

I can see in [code](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/mock-toolrunner.ts#L253) where the extraneous "s" is written to stdout. Why is this happening? Can I opt out of it?

PS great username. Could only be better if one letter was different ;)

**Comment by jtpetty** [comment]
Thanks for the debug assist. It looks like not all of the writes to stdout were properly guarded by the silent check. I pushed a PR that I think will fix the issue.

And I had thought the same thing wrt your username :)
