### ISSUE TITLE
Picklist "editableOptions" has to be capitalized

### ISSUE THREAD

**Issue by lucaslra** [microsoft/azure-pipelines-task-lib#607]
### Environment
azure-pipelines-task-lib version: 

### Issue Description
In the tasks.schema.json file, what is documented as `"editableOptions": "True"` actually must be `"EditableOptions": "True"`, with capitalized E at the beginning

### Expected behaviour
Picklist value can be edited manually

### Actual behaviour
Picklist value canNOT be edited manually if used as documented on the schema file

### Steps to reproduce
1. Create a new Extension contribution with a picklist field
2. Set options to `"editableOptions": "True"`
3. Picklist field will have incorrect behavior

**Comment by damccorm** [comment]
Fixed by #608
