### ISSUE TITLE
toolrunner pollutes stdout of the tool itself

### ISSUE THREAD

**Issue by AArnott** [microsoft/azure-pipelines-task-lib#611]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description

When spawning a tool using the API offered by this library, I can give a `Writable` stream to receive the tool's stdout stream. Except that in recent versions of this library, this stream *also* gets polluted with the command line being printed to my stream at the beginning and an extra EOL character at the end of it.
This broke my task when I upgraded from 2.7.7 to the 2.9.3 version of the library.

I see there is a `silent` property that suppresses... not just the pollution, but *all* writing to this stream. Why would I need to suppress it *all*? If I didn't want any of it, I could just provide a null-stream. But I wish there were a property I could set to silence the extra stuff so I can get *only* the output of the tool itself. 

See this relevant source code:

https://github.com/microsoft/azure-pipelines-task-lib/blob/63d954e0202c20011fbc0fbe2ab08980a6b626bf/node/toolrunner.ts#L812-L830

### Expected behavior

The `IExecOptions.outStream` should receive *just* stdout from the invoked tool.

**Or** provide another writable stream property or options so that I have some way of getting just the tool's output.

### Actual behaviour

The `IExecOptions.outStream` receives headers and footers around the invoked tool's own stdout.

**Comment by jtpetty** [comment]
@damccorm - Did we release a new version of this that includes this PR? If not, can we?

**Comment by damccorm** [comment]
Yes, we released I guess this issue just never got updated - sorry about that!
