### ISSUE TITLE
[Question] Usage of this library in Azure DevOps pipeline?

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azure-pipelines-task-lib#614]
In my Azure DevOps release pipeline, I need to evaluate a glob/minimatch pattern to get a list of filenames, which I then need to pass to a PowerShell script. There doesn't seem to be a predefined Azure DevOps pipeline task that takes in a glob and outputs what it matched; my search for one has led me to this repo as the closest thing, in particular the [`Find-VsTsMatch`](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/FullHelp/Find-VstsMatch.md) function which I grabbed via the [instructions to download the SDK](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md). But I have some questions around usage:

1. Is it acceptable (permitted by license) for me to use this library in the manner I intend?
2. It seems that `Find-VsTsMatch` does not exist any more? It appears to have been renamed to just [`Find-Match`](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/VstsTaskSdk/FindFunctions.ps1#L20) so I'm not sure if the docs are out of date or what.
3. `Install-Module VstsTaskSdk` wants to clobber `Out-Default`, is this intentional/harmful?
4. What would be the recommended way to consume this library? Store a copy of `FindFunctions.ps1` in my own repo and dot-source it in my own PS scripts? Add a [PowerShell task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell) that does `Install-Module VstsTaskSdk` to get the SDK and have my scripts `Import-Module VstsTaskSdk`? Or something else (please suggest)?

**Comment by damccorm** [comment]
Hey, sorry for the slow response:
> Is it acceptable (permitted by license) for me to use this library in the manner I intend?

Yep! We use the MIT license - https://github.com/microsoft/azure-pipelines-task-lib/blob/master/LICENSE

> It seems that Find-VsTsMatch does not exist any more? It appears to have been renamed to just Find-Match so I'm not sure if the docs are out of date or what.

The vsts prefix is added at export time, so it doesn't show up in the function definition, but that's how you invoke it.

> Install-Module VstsTaskSdk wants to clobber Out-Default, is this intentional/harmful?

I'd use `Save-Module` (see docs in next answer)

> What would be the recommended way to consume this library? Store a copy of FindFunctions.ps1 in my own repo and dot-source it in my own PS scripts? Add a PowerShell task that does Install-Module VstsTaskSdk to get the SDK and have my scripts Import-Module VstsTaskSdk? Or something else (please suggest)?

We'd recommend packaging it with the task (see [here](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md))
