### ISSUE TITLE
ServiceFabricDeploy should support dynamic application names (may be new task)

### ISSUE THREAD

**Issue by henry-padilla** [microsoft/azure-pipelines-task-lib#620]
### Environment
azure-pipelines-task-lib version: 

### Issue Description
Service fabric can create dynamic applications (based on "root" applications) but there is no way to update them. 

### Expected behavior
ServiceFabricDynamicDeploy should have an input for "ApplicationNamePrefix"/"ApplicationNameSuffix" that would be used (with "ApplicationRootName") to create update packages for dynamic applications.

### Actual behavior
There is currently no "Actual behavior". Dynamic applications must be destroyed and recreated to update them.

### Steps to reproduce
1. Create a "root" application that spawns dynamic applications.
2. Use ServiceFabricDeploy to update the "root" application.
3. Notice the dynamic applications are not updated.

**Comment by damccorm** [comment]
Hey @henry-padilla - this looks like an issue with a task, not with this library - would you mind filing this issue at https://github.com/microsoft/azure-pipelines-tasks
