### ISSUE TITLE
Unable to mock Windows in `getPlatform` call

### ISSUE THREAD

**Issue by tillig** [microsoft/azure-pipelines-task-lib#621]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
When mocking `getPlatform` you can't set a response that indicates Windows.

The mock answers handler returns `null` [if the value of the mock answer isn't truthy](https://github.com/microsoft/azure-pipelines-task-lib/blob/34e17f6ca02c256bcb4e121880f6d4b7da65eed2/node/mock-answer.ts#L45). The [`Platform` enum has `Windows` as the first entry](https://github.com/microsoft/azure-pipelines-task-lib/blob/34e17f6ca02c256bcb4e121880f6d4b7da65eed2/node/task.ts#L49) which means the value of `Platform.Windows` is zero.

Here's the rendered JS:

```js
/** Platforms supported by our build agent */
var Platform;
(function (Platform) {
    Platform[Platform["Windows"] = 0] = "Windows";
    Platform[Platform["MacOS"] = 1] = "MacOS";
    Platform[Platform["Linux"] = 2] = "Linux";
})(Platform = exports.Platform || (exports.Platform = {}));
```

What that means is if you have answers defined:

```typescript
const answers: ma.TaskLibAnswers = {
  'getPlatform': {
    'getPlatform': tl.Platform.Windows,
  },
};
runner.setAnswers(answers);
```

Then you'll see something like this in your debug output:

```text
##vso[task.debug]looking up mock answers for "getPlatform", key '"getPlatform"'
##vso[task.debug]mock response not found
```

This becomes troublesome for code like this:

```typescript
export function setConsoleCodePage(): void {
  if (tl.getPlatform() === tl.Platform.Windows) {
    tl.execSync(path.resolve(process.env.windir as string, 'system32', 'chcp.com'), ['65001']);
  }
}
```

You can work around this by being slightly less explicit:

```typescript
export function setConsoleCodePage(): void {
  if (!tl.getPlatform()) {
    tl.execSync(path.resolve(process.env.windir as string, 'system32', 'chcp.com'), ['65001']);
  }
}
```

but it'd be nice if the mocking didn't drop non-truthy answers.

**Hypothetically, this may also drop other non-truthy answers, too** but I see [things like the `checkPath` mock, where you'd potentially want to say `false` to simulate a missing file](https://github.com/microsoft/azure-pipelines-task-lib/blob/34e17f6ca02c256bcb4e121880f6d4b7da65eed2/node/mock-task.ts#L241), handle the falsy values directly.

### Expected behaviour
I expect the mock for `getPlatform` to return 0 (Windows) when configured to mock that value.

### Actual behaviour
The mock returns `null` and indicates no mock is set up for `getPlatform`.

### Steps to reproduce
1. Create a simple task that just does ``tl.debug(`Platform: ${tl.getPlatform()}`);``
2. Set up a test that tries to mock the `getPlatform` call. Set the value to `0` to indicate Windows.
3. Run the test with the `TASK_TEST_TRACE` environment variable set.
4. Inspect the output and notice the value is `null` rather than `0`. Also notice the mock logging indicates there's _no answer_ rather than an answer indicating `0`.

**Comment by SignalRichard** [comment]
I was able to mock the `getPlatform` function using `registerMockExport` on the TaskMockRunner.

`tmr.registerMockExport('getPlatform', () => { return 0; });`

I know this isn't exactly the same issue as described above but this works as an alternative for mocking the `getPlatform` function.

**Comment by tillig** [comment]
[It appears this is still an issue.](https://github.com/microsoft/azure-pipelines-task-lib/blob/34e17f6ca02c256bcb4e121880f6d4b7da65eed2/node/mock-answer.ts#L45)

**Comment by tillig** [comment]
Yup, still an issue.

**Comment by tillig** [comment]
Would it be more accurate to check `hasOwnProperty` and whether the value is not `null`?

**Comment by tillig** [comment]
Not stale, and can't seem to get any maintainer feedback.

**Comment by tillig** [comment]
Not stale, still no feedback.

**Comment by tillig** [comment]
Not stale, still no feedback.

**Comment by kuleshovilya** [comment]
Hello @tillig . Tried to reproduce the issue and received proper return value, the example you've provided worked for me. But the version that you've used at the time is really old now, could you please update library and try again, whether it will work for you. If not, we'll try to get all the details to reproduce it.

**Comment by tillig** [comment]
@kuleshovilya [The code causing the issue hasn't changed](https://github.com/microsoft/azure-pipelines-task-lib/blob/45747eb60680c826883d772e3539b88e1b587ed5/node/mock-answer.ts#L43) so I'm not sure how it was resolved, but sure, I can try it again.

**Comment by tillig** [comment]
@kuleshovilya I have verified that this is absolutely still a problem on the latest library. [Here is a repo that contains a demonstration of the issue.](https://github.com/tillig/azure-pipelines-task-lib-621) You'll see that I can mock `getPlatform` _if and only if_ it's not `Windows` because `Windows` is `0` in the enumeration value, so the simple `!` not check in the mocking system incorrectly determines that there's "no mock answer" and responds with `null` instead of `0`.

**Comment by kuleshovilya** [comment]
@tillig Yes, I can see it now. Although it's not the code that you referencing at fault,this one checks for empty cmd, which is a string value, the faulty check is [below](https://github.com/microsoft/azure-pipelines-task-lib/blob/34e17f6ca02c256bcb4e121880f6d4b7da65eed2/node/mock-answer.ts#L52). We are implementing the fix for it, will notify you when its merged.

**Comment by kuleshovilya** [comment]
The change has been published to npm. Please check when you can. I'll close ticket for now, please feel free to reopen it if something is wrong or ping me at my email v-ikuleshov@microsoft.com

**Comment by tillig** [comment]
Verified, this fixes it. Thanks!
