### ISSUE TITLE
Add MultiValue input for Azure DevOps pipeline tasks

### ISSUE THREAD

**Issue by malingel** [microsoft/azure-pipelines-task-lib#622]
### Description
I have written a few custom build & release pipeline tasks.  There have been a couple of instances where I would have loved to have a multi value picklist input.  For example:

> I want to present the user a list of options for applications to put in maintenance.  I want to pre-populate this list with a data source binding so that we can avoid typos and to keep the user from needing to go look them up.  I want the user to also be able to select multiple applications in one task instead of creating multiple copies of the task to run the same code for multiple applications.

Right now, the best option I have found for this is to present the user with a pickList of populate values that they can copy/paste from into a multi line text box input.

Something like [this](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vsts-extensions-multivalue-control) would be great.

**Comment by damccorm** [comment]
Hey @malingel - this repo is specifically for the task-lib and probably isn't the best place for a non-task-lib specific request - would you mind sharing this at https://developercommunity.visualstudio.com/content/idea/post.html?space=21?
