### ISSUE TITLE
Search pattern for one * acts like **

### ISSUE THREAD

**Issue by Saibamen** [microsoft/azure-pipelines-task-lib#623]
### Environment
azure-pipelines-task-lib version: Like in Azure DevOps
vmImage: 'windows-latest'
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az28'
Current agent version: '2.165.0'
Current image version: '20200301.1'

### Issue Description
I'm using Azure DevOps. While using search patterns with one asterisk (`*`), tasks acts like it was double asterisk (`**`).

Related: https://github.com/microsoft/azure-pipelines-tasks/issues/12436

### Expected behaviour
Searching only in current folder.

### Actual behaviour
Searching in all folders.

### Steps to reproduce
Use search pattern in any available azure pipeline task, like `NuGetCommand`, `DotNetCoreCLI`:
```
- task: NuGetCommand@2
  inputs:
    restoreSolution: 'X/*.sln'
    verbosityRestore: 'Normal'
```

### Logs
```
##[debug]solution=d:\a\1\s\X\*.sln
##[debug]NuGet.UseLegacyFindFiles=undefined
##[debug]system.defaultWorkingDirectory=d:\a\1\s
##[debug]defaultRoot: 'd:\a\1\s'
##[debug]matchOptions.noglobstar: 'undefined'
##[debug]matchOptions.dot: 'undefined'
##[debug]matchOptions.noext: 'undefined'
##[debug]matchOptions.nocase: 'undefined'
##[debug]matchOptions.nonull: 'undefined'
##[debug]matchOptions.matchBase: 'undefined'
##[debug]matchOptions.nocomment: 'undefined'
##[debug]matchOptions.nonegate: 'undefined'
##[debug]matchOptions.flipNegate: 'undefined'
##[debug]pattern: 'd:\a\1\s\X\*.sln'
##[debug]expanding braces
##[debug]pattern: 'd:/a/1/s/X/*.sln'
##[debug]findPath: 'd:\a\1\s\X'
##[debug]statOnly: 'false'
##[debug]findPath: 'd:\a\1\s\X'
##[debug]findOptions.allowBrokenSymbolicLinks: 'undefined'
##[debug]findOptions.followSpecifiedSymbolicLink: 'undefined'
##[debug]findOptions.followSymbolicLinks: 'undefined'
##[debug]  d:\a\1\s\X (directory)
##[debug]  d:\a\1\s\X\.dockerignore (file)
##[debug]  d:\a\1\s\X\.gitignore (file)
##[debug]  d:\a\1\s\X\YYYYYYY (directory)
##[debug]  d:\a\1\s\X\YYYYYYY\appsettings.json (file)
##[debug]  d:\a\1\s\X\YYYYYYY\appsettings.Test.json (file)
##[debug]  d:\a\1\s\X\YYYYYYY\Common (directory)
##[debug]  d:\a\1\s\X\YYYYYYY\Common\ApiResponse.cs (file)
```

**Comment by Saibamen** [comment]
.

**Comment by Saibamen** [comment]
.

**Comment by Saibamen** [comment]
r

**Comment by Saibamen** [comment]
.

**Comment by Saibamen** [comment]
.

**Comment by kuleshovilya** [comment]
Just wanted to confirm that you still see this behaviour in your environment? Quick testing showed that it iterates correctly over the folders.

**Comment by kuleshovilya** [comment]
Hello @Saibamen . Any update on the issue?

**Comment by Saibamen** [comment]
I don't have time to test it, sorry

**Comment by kuleshovilya** [comment]
Alright, I'll close the issue for now, if needed you can either reopen the issue or ping me at the email v-ikuleshov@microsoft.com
