### ISSUE TITLE
MockTaskRunner blocks

### ISSUE THREAD

**Issue by lmmarsano** [microsoft/azure-pipelines-task-lib#624]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
`MockTaskRunner#run` blocks.
https://github.com/microsoft/azure-pipelines-task-lib/blob/0a6b208c2e94339d2ee9d33d971d965ca25d61de/node/mock-test.ts#L68
How about *not* doing that?
You've already made it hard enough to mock http responses by launching the SUT in a different process.
Now we can't even run a mock http server from our test runner, because you're blocking that, too?
Wow.

### Expected behaviour
This test suite

`tests/_suite.ts`
```typescript
import * as path from 'path'
import * as assert from 'assert'
import * as ttm from 'azure-pipelines-task-lib/mock-test'
import axios from 'axios'
import ServerMock = require('mock-http-server')

describe('Sample task tests', () => {
    const server = new ServerMock({host: 'localhost', port: 0})
    before(done => server.start(() => {
        process.env.SYSTEM_TEAMFOUNDATIONCOLLECTIONURI = `http://localhost:${server.getHttpPort()}/`
        done()
    }))

    after(done => server.stop(done))

    it('non-blocking code completes', () => {
        server.on({path: '*'})
        return axios({
            method: 'GET',
            url: process.env.SYSTEM_TEAMFOUNDATIONCOLLECTIONURI
        })
            .then(res => assert.strictEqual(res.status, 200))
    })

    it('blocking code completes', done => {
        const tp = path.join(__dirname, 'success.js')
        const tr: ttm.MockTestRunner = new ttm.MockTestRunner(tp)
        server.on({path: '*'})
        tr.run()
        done()
    })
})
```
with these scripts
`tests/success.ts`
```typescript
import ma = require('azure-pipelines-task-lib/mock-answer')
import tmrm = require('azure-pipelines-task-lib/mock-run')
import path = require('path')

const taskPath = path.join(__dirname, '..', 'index.js')
const tmr: tmrm.TaskMockRunner = new tmrm.TaskMockRunner(taskPath)

tmr.run();
```
`index.ts`
```typescript
import tl = require('azure-pipelines-task-lib/task')
import axios from 'axios'
const url = tl.getVariable('system.teamFoundationCollectionUri')
axios.get(url!)
```
shouldn't deadlock.
That would mean offering a promise returning method like `#runAsync` by maybe calling [`fork`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) instead.
### Actual behaviour
Deadlock.
Since no such function exists, we only get a deadlocking synchronous `#run`.
```shellsession
$ npm run build && npm test

> tester@1.0.0 build /home/LOM0227/project/ALM.Wreckorator/asset_yml_check_whitelist/src
> tsc


> tester@1.0.0 test /home/LOM0227/project/ALM.Wreckorator/asset_yml_check_whitelist/src
> mocha tests/_suite.js



  Sample task tests
      non-blocking code completes
```
the second test never completes.
It shouldn't be this hard to mock http responses: some tasks will need to do network IO, and we need a way to test them.
### Steps to reproduce
Transpile & run the above code.

**Comment by damccorm** [comment]
I'd recommend doing this with a standard http mocking library (e.g. nock) - we do this all over the place in our tasks repo if you'd like examples (e.g. https://github.com/microsoft/azure-pipelines-tasks/blob/7e2d65456791dd520f9840c656a8df292b2cd65a/Tasks/AppCenterDistributeV3/Tests/L0PublishStore.ts#L4). You can also mock the source of the calls themselves (e.g. https://github.com/microsoft/azure-pipelines-tasks/blob/7e2d65456791dd520f9840c656a8df292b2cd65a/Tasks/NodeToolV0/Tests/L0FirstDownloadSuccess.ts#L59)

I can't speak to why this was originally written this way, but I do see a lot of rationale for doing it - the way our library is currently set up, even if we offered something like runAsync there's not a clear/easy way to wait on the result here. Additionally, it more closely mirrors the actual execution that happens on the agent this way.

I'm not necessarily opposed to doing this, but I don't see it rising in priority at the moment since there are other ways to do this.

**Comment by lmmarsano** [comment]
Node.js is fundamentally a cooperative multitasking system that runs JavaScript in a single thread.
Pretty much every introduction to Node.js covers this and stresses the importance of not blocking the main thread by keeping synchronous calls to a minimum/avoiding them entirely.
Just from Node.js' own [guides](https://nodejs.org/en/docs/guides/)
- [Overview of Blocking vs Non-Blocking](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/)
	- [Dangers of Mixing Blocking and Non-Blocking Code](https://nodejs.org/en/docs/guides/blocking-vs-non-blocking/#dangers-of-mixing-blocking-and-non-blocking-code)
-  [Don't Block the Event Loop (or the Worker Pool)](https://nodejs.org/en/docs/guides/dont-block-the-event-loop/)

Performing synchronous calls despite these clear warnings is a failure to cooperate, a fundamentally bad practice for Node.js.
In this project, it leads to some awkward workarounds, like [the scattering of 'mock test runner' files required just to setup mocks and run the task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#step-2-unit-test-your-task-scripts), instead of allowing more straightforward testing setup & teardown directly from the test suite file.

If this Node.js library is going to depart from a basic standard and defy common expectations of Node.js libraries, then documentation should at least clearly point this out and explain the compensations necessary to support that departure where more natural approaches for more cooperative libraries would fail.

Would a `Promise` that resolves on completion of the forked process not wait on the result?
`Promise`s & callbacks are commonplace for Node.js.

**Comment by lmmarsano** [comment]
Needs better adherence to node conventions & more explicit documentation of departures.
