### ISSUE TITLE
VstsTaskSdk.psd1 not found

### ISSUE THREAD

**Issue by Angr1st** [microsoft/azure-pipelines-task-lib#628]
### Environment
azure-pipelines-task-lib version: ?
I am trying to build a build task that only runs on windows using the Powershell SDK (VstsTaskSDK Version 0.11.0).

### Issue Description
I used the `Save-Module -Name VstsTaskSdk -Path .\` command to download the newest version of the VstsTaskSDK. The path to the VstsTaskSdk.psd1 is 

> ps_modules\VstsTaskSdk\0.11.0\VstsTaskSdk.psd1

but when calling the build task it looks here:

> ps_modules\VstsTaskSdk\VstsTaskSdk.psd1

Do I need to manually remove the 0.11.0 Folder or is there some configuration file or something to fix this? FYI I am not a powershell expert I basically want to wrap a dotnet executable and call that with the task.ps1. I started out using the legacy powershell task handler but azure devops showed that I should use this. If we find out what I am missing this should be added to the documentation.

### Expected behaviour
It should find the VstsTaskSdk.psd1 even with the Version Number Folder.

### Actual behaviour
It outputs:

> ##[error]File not found: 'C:\Agent\vsts-agent-win-x64-2.165.2\_work\_tasks\MINTEST_e213000f-5d5c-4791-802d-52ea3e7be1f1\1.0.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'

### Steps to reproduce
1. Create a custom build task that wraps a powershell script and uses the new powershell3 Task executer.
2. Download the Sdk
3. Package the extension
4. Upload the extension
5. Run Task

I have published my task [here](https://github.com/Angr1st/CustomBuildTaskRepro) so you could alternatively just clone my repo and update the vss_extension.json.

**Comment by TclasenITVT** [comment]
You could try loading to VstsTaskSdk.psd1 manually using this powershell: 
`Import-Module (Get-Childitem -Path .\ -Include VstsTaskSdk.psd1 -recurse | Select-Object -first 1).ToString()`. If someone could point me to the place where the Powershell3 TaskHandler loads powershell modules I could try adding functionality to include versioned Powershell Modules (always load the newest(highest) version by default).

**Comment by jessehouwing** [comment]
```
\taskfolder
   \task.json
   \ps_modules\vststasklib
```

See structure here:
https://github.com/jessehouwing/azure-pipelines-variable-tasks

**Comment by Angr1st** [comment]
So you have to manually remove the version number folder created by calling
the Save-Module Cmdlet. Maybe state that explictly in the documentation or
Update the Code to Download the Module and automatically remove the version
folder.

Jesse Houwing <notifications@github.com> schrieb am Di., 5. Mai 2020, 16:31:

> ```
> \taskfolder
> \task.json
> \ps_modules\vststasklib
> ```
>
> See structure here:
> https://github.com/jessehouwing/azure-pipelines-variable-tasks
>

**Comment by jessehouwing** [comment]
Yeah, use exactly the structure above. the docs show this structure already:

https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md#package-the-sdk-with-the-task

**Comment by Angr1st** [comment]
#631 I opened a pr to improve the documenation for others and made this fact more explicit.
