### ISSUE TITLE
Question, is the task.schema listed here the taskgroup schema

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/azure-pipelines-task-lib#634]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 

### Issue Description
Question, is the task.schema listed here the taskgroup schema? I'm looking for documentation on using groups, and groupname in my TaskGroups and thus far it's severely lacking. I'm not sure that this is the right group, but hopeful someone here could point me to the right person.

Thanks in advance!

**Comment by jessehouwing** [comment]
This is the schema for custom tasks, I suppose the format is similar, but it's not the same thing.

**Comment by jeffpatton1971** [comment]
@jessehouwing, yea I figured, but it's interesting when you export a task from the taskgroup, the output is identical. It just appears grouping isn't honored, so I was rather confused.
