### ISSUE TITLE
Provide .NET Core task lib 

### ISSUE THREAD

**Issue by conficient** [microsoft/azure-pipelines-task-lib#639]
### Environment
azure-pipelines-task-lib version:  n/a

### Issue Description
Writing tasks in PowerShell limits you to windows agents, and writing in Node is **really hard** (and has a lot of overhead having to include `node_modules` in each task). Since .NET Core is cross-platform there should be a task-lib using .NET Core so we can write tasks with a more capable framework.

### Expected behaviour
Writing azure pipelines tasks should not be this hard

### Actual behaviour
I've spent days trying to wrap my head around Node tasks, mocha testing etc. If this was .NET Core and C# it would be a few hours.

### Steps to reproduce
1. Try writing a task from scratch

**Comment by damccorm** [comment]
We are not planning to natively support any additional native handlers (languages) at this time. You can see some discussion around this and PowerShell core at https://github.com/microsoft/azure-pipelines-task-lib/issues/537.

Note that if you'd like to write tasks in .NET Core, you can write a node script that just runs a .NET. E.g. something like this but for dotnet:

```
import tl = require('azure-pipelines-task-lib/task');
import tr = require('azure-pipelines-task-lib/toolrunner');

const firstVar = tl.getInput('firstVar');
const secondVar = tl.getInput('secondVar');

async function run() {
  let pwshPath: string = tl.which('pwsh', true);
  let pwsh = tl.tool(pwshPath);
  pwsh.arg('path/to/script.ps1');
  pwsh.arg(firstVar);
  pwsh.arg(secondVar);

  let options = <tr.IExecOptions> {
    failOnStdErr: false,
    // Direct all output to STDOUT due to Node's buffering strategy
    errStream: process.stdout, 
    outStream: process.stdout,
    ignoreReturnCode: true
  };

  let exitCode: number = await pwsh.exec(options);

  let result = tl.TaskResult.Succeeded;

  // Fail on exit code.
  if (exitCode !== 0) {
    tl.error(`Failed with exit code {exitCode}`);
    result = tl.TaskResult.Failed;
  }

  tl.setResult(result, null, true);
}
```

**Comment by conficient** [comment]
Thanks for the reply.. I'll look into this.

**Comment by conficient** [comment]
Reading the above example I have to use Node to run PowerShell to run .NET core, which just adds two new sets of technologies on top of the issues I'm having with Node.  So I guess we're stuck with Node for now, which is a shame

**Comment by damccorm** [comment]
> Reading the above example I have to use Node to run PowerShell to run .NET core, which just adds two new sets of technologies on top of the issues I'm having with Node. So I guess we're stuck with Node for now, which is a shame

You can invoke .NET core directly from Node (don't need the powershell intermediary) - I just had the powershell example handy. But yeah, our recommended path here is to use Node, this is just a workaround for anyone who finds that a nonstarter for whatever reason.

**Comment by conficient** [comment]
I've managed to coax my node version to work with a few hacks (some node modules libs had files with spaces in the names that the `tfx extension create` command didn't like).

Still think a .NET Core task would be waaaay simpler to write and test, and have a lower overhead than loading a node modules tree.
