### ISSUE TITLE
How to set a multi-job output variable

### ISSUE THREAD

**Issue by charleszipp** [microsoft/azure-pipelines-task-lib#640]
I was wondering if it is possible to set a variable such that it can be accessed by multiple jobs as documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable)?

The `task` object currently only allows for setting the variable name and isSecret bool. I would like to be able to have my extension set variables that can be access across multiple jobs like this...

```text
##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value
```

**Comment by jessehouwing** [comment]
If the task manifest (task.json) has the output variable declared, it will be lifted automatically is my experience.

If you want to register arbitrary output variables, you need to use a custom console output.

The special commands can be issued manually but simply writing them to the output (console.log or write-host).

**Comment by damccorm** [comment]
We could pretty easily add support for this in the setVariable function, would probably just take adding a param here - https://github.com/microsoft/azure-pipelines-task-lib/blob/c532de60cd68ba382b17d574c669333beabe0b9f/node/task.ts#L187

@charleszipp if you (or someone else) want to add a PR I'd be happy to review/merge/publish an updated library.

**Comment by damccorm** [comment]
Adding `help wanted` tag since this is a pretty good first issue

**Comment by charleszipp** [comment]
Thanks @jessehouwing and @damccorm for the suggestions. These are all helpful. Adding the parameter would be ideal as it would be less configuration for users of my task. However, @jessehouwing's suggestions provide a good workaround in the interim. When i get back to adding support for this on my task, I will will submit a PR if one hasnt been created by then.
