### ISSUE TITLE
PowerShell LoggingCommandFunctions fail on non-Windows OS

### ISSUE THREAD

**Issue by fredrikhr** [microsoft/azure-pipelines-task-lib#642]
Running a Write function from the LoggingCommandFunctions in a PowerShell command on a non-windows Azure Pipelines Agent fails.

### Environment
azure-pipelines-task-lib version: Current `master` branch
LoggingCommandFunctions.ps1: https://github.com/microsoft/azure-pipelines-task-lib/blob/c532de60cd68ba382b17d574c669333beabe0b9f/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1

### Issue Description
It seems that PowerShell on a non-windows system is not able to successfully set the Console coloring when executing the function `Write-TaskDebug_Internal`.

The error can be circumvented by adding the `-AsOutput` parameter to the function call and wrapping the output result in a plain call to `Write-Host`

```ps1
Write-TaskVerbose -Message "This is a test message" # fails
Write-Host (Write-TaskVerbose -Message "This is a test message" -AsOutput) # works
```

### Expected behaviour
The Command writes a properly formatted logging command to the host output.

### Actual behaviour
```
Write-Host: /home/vsts/work/1/s/LoggingCommandFunctions.ps1:607
Line |
 607 |      Write-Host -Object $command -ForegroundColor $foregroundColor -Ba …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot process the color because -1 is not a valid color.
     | (Parameter 'value') Actual value was -1.
```
https://github.com/microsoft/azure-pipelines-task-lib/blob/c532de60cd68ba382b17d574c669333beabe0b9f/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1#L579-L608

### Steps to reproduce

Execute the following pipeline template:

``` yml
pool:
  vmImage: ubuntu-latest
steps:
- pwsh: |
    [uri]$dlUri = "https://github.com/Microsoft/azure-pipelines-task-lib/raw/master/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1"
    [string]$fileName = $dlUri.Segments | Select-Object -Last 1
    [System.Net.ServicePointManager]::SecurityProtocol = `
        [System.Net.ServicePointManager]::SecurityProtocol -bor `
        [System.Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $dlUri -OutFile $fileName
    $filePath = Join-Path . $fileName
    . $filePath
    Write-TaskVerbose -Message "LoggingCommandFunctions stored to $filePath"
  displayName: Download PowerShell LoggingCommandFunctions from azure-pipelines-task-lib
```

**Comment by damccorm** [comment]
Hi @fredrikhr this library is designed specifically for writing PowerShell tasks themselves, which are guaranteed to only run on PowerShell. The library is not meant for PowerShell Core
