### ISSUE TITLE
Detect if task is running on a Microsoft-hosted agent

### ISSUE THREAD

**Issue by mcafaro** [microsoft/azure-pipelines-task-lib#644]
### Environment
azure-pipelines-task-lib version: 
^2.9.3

### Issue Description
Is there any reliable way for a task to detect if it is running on a Microsoft-hosted agent? If not, can you please consider adding one? I have a task that has certain capabilities depending on whether it is run on a self-hosted or Microsoft-hosted agent.

I see a number of tasks in the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks) repo check `System.ServerType` for the `Hosted` value. Unfortunately this approach only seems to be able to distinguish if the task is running on VSTS or TFS.

**Comment by jessehouwing** [comment]
Sounds like you're not interested in hosted or self hosted agents, but the type of server the agent is connected to.

**Comment by mcafaro** [comment]
For my particular use-case, I don't actually care what type of server the agent is connected to (which is why `System.ServerType` isn't interesting to me). I'm more concerned with whether the agent is Microsoft-hosted or self-hosted.

**Comment by mcafaro** [comment]
I am still in need of a feature to detect if my task is running on a Microsoft-hosted agent. The best I have been able to come up with is a brittle heuristic-style approach of checking different environment variables depending on the host OS.

**Comment by jessehouwing** [comment]
I don't see what difference it makes or what exactly you're after? Are you
trying to detect whether the agent will stick around after the job is done?
What is so special about the hosted agent or your local agent that a custom
capability can't fix?

**Comment by mcafaro** [comment]
Two reasons:
1) I need to know if the agent is running on Azure
2) I need to know if the agent will stick around after the job is done

For 1, I have decent means of detecting this already through the Azure Instance Metadata service. For 2, I have no good way to distinguish between a private agent running on Azure and a Microsoft-hosted agent. In the case of a private agent, it may stick around and I need to treat it differently.

**Comment by jessehouwing** [comment]
There is no guarantee a private agent will stick around. The new scaleset
agents clearly won't and I know of quite a few companies who have created
their own single job private agent.

The most reliable solution would be to add a variable to the stage/job or
ai input to the task and prepare for the worst by default.

**Comment by mcafaro** [comment]
> There is no guarantee a private agent will stick around.

Right. That's why I have to assume the worst case (being they stick around) and treat them differently. A Microsoft-hosted agent I'm guaranteed will go away. A private agent I must assume will not, even if it may.

> The most reliable solution would be to add a variable to the stage/job or ai input to the task and prepare for the worst by default.

This doesn't make for a great user experience. But I understand if no one else is asking for this capability you have to prioritize your efforts. Feel free to close this issue if it just doesn't seem broadly applicable enough.

Thanks for your response.
