### ISSUE TITLE
Calls to updateReleaseName in Node results in error "Invalid Version: 2.132"

### ISSUE THREAD

**Issue by james-h-stephens** [microsoft/azure-pipelines-task-lib#646]
### Environment
azure-pipelines-task-lib version: 2.9.6

### Issue Description
Calls to the [_updateReleaseName_](url) function result in the error message "Invalid Version: 2.132". 
The function is making a call to [`assertAgent`](https://github.com/microsoft/azure-pipelines-task-lib/blob/c532de60cd68ba382b17d574c669333beabe0b9f/node/task.ts#L2088).

![image](https://user-images.githubusercontent.com/23285467/85316558-f230ea80-b48a-11ea-8bb7-29f6b7cec500.png)

It looks like this error is coming from the `semver` library. _2.132_ is not a valid version under that specification.

### Expected behaviour
Calling the _updateReleaseName_ will rename the release.

### Actual behaviour
Calls to the _updateReleaseName_ function result in the error message "Invalid Version: 2.132"

### Steps to reproduce
1. Create task that uses _azure-pipelines-task-lib/task_ node tasks.
2. Call the [`updateReleaseName`](https://github.com/microsoft/azure-pipelines-task-lib/blob/c532de60cd68ba382b17d574c669333beabe0b9f/node/task.ts#L2087) function.
3. Run the task in either a unit test or a release.

### Logs
2020-06-16T15:33:33.2286631Z ##[debug]Updating release name
2020-06-16T15:33:33.2291026Z ##[debug]task result: Failed
2020-06-16T15:33:33.2292607Z ##[error]Invalid Version: 2.132
2020-06-16T15:33:33.2294211Z ##[debug]Processed: ##vso[task.issue type=error;]Invalid Version: 2.132
2020-06-16T15:33:33.2296809Z ##[debug]Processed: ##vso[task.complete result=Failed;]Invalid Version: 2.132

**Comment by damccorm** [comment]
Added a pr to fix this

**Comment by james-h-stephens** [comment]
While the PR has been open, it was never completed, and seems that bug still exists.
