### ISSUE TITLE
Visible rule and underscore values

### ISSUE THREAD

**Issue by gcacars** [microsoft/azure-pipelines-task-lib#658]
I'm facing some problems with expressions in visibility rule that contains underscore in the values, like `STANDARD_HA`.

### Environment
azure-pipelines-task-lib version: 2.9.6

### Issue Description
Values with underscore not pass in the extension validation.

### Expected behaviour
Expression should be validated without errors.

### Actual behaviour
Error: Extension validation failed.

### Steps to reproduce
1. Create a radio field:
```
    {
      "name": "tier",
      "type": "radio",
      "defaultValue": "BASIC",
      "options": {
        "BASIC": "standalone instance",
        "STANDARD_HA": "highly available primary/replica instances"
      }
    }
```
2. And other field with this visibleRule:
`"visibleRule": "tier = STANDARD_HA"`
3. Package and publish the extension

### Logs
`Task definition visible rule \'tier = STANDARD_HA\' is invalid. It should be of format "A <validconditionhere> B" for Task with ID ...`

**Comment by jessehouwing** [comment]
I also reported this to the product team and the rule on the marketplace is too strict. But I haven't seen a plan to resolve yet.

**Comment by gcacars** [comment]
Ok, but not makes sense for me to have a marketplace rule in the value of a field. It differs from a task name or extension id...

**Comment by jessehouwing** [comment]
I think it's some kind of security thing, haven't asked for the reason the
rule exists, bu t I did ask for it to be removed.

**Comment by robwillup** [comment]
I experienced the same problem when the value being tested has a `#`. None of the options below work:

`"visibleRule":"lang=C#"`
`"visibleRule":"lang = C#"`
`"visibleRule":"lang=\"C#\""`
`"visibleRule":"lang = \"C#\""`

**Comment by jessehouwing** [comment]
Got confirmation its a bud in the marketplace, but it's taking awfully long for the Azure Devops team to get the fix out.

If you manually push the task directly using `tfx build tasks upload`, the task will work just fine.

**Comment by mindlessroman** [comment]
not stale

**Comment by mindlessroman** [comment]
not stale

**Comment by jessehouwing** [comment]
This is fixed now. Can be closed.
