### ISSUE TITLE
Unable to fetch specific set of variables

### ISSUE THREAD

**Issue by pavan2004it** [microsoft/azure-pipelines-task-lib#659]
### Environment
azure-pipelines-task-lib version: 2.10.0

### Issue Description
I am trying to fetch specific set of variables based on the scope from tl.getVariables() , for example if i want to get only the variables defined at the release scope or at the scope of various stages like  dev, val or prod .... etc.. , i couldn't find a way to filter the output of the method call , want to know if there is a way to accomplish this .

My use case is in my custom task i will be pulling all the variables from release scope and stage scope . I have attached the below image to reference to scope.

![variable_scope](https://user-images.githubusercontent.com/13082762/92439170-f2a66b00-f1c7-11ea-9cec-6098c2fa5b9a.png)

**Comment by jessehouwing** [comment]
You get only the variables available to that step, merged to a single list. If you want to access to the sources of variables and filter those, you'll need to access the rest api against the release/build/pipeline endpoint.

**Comment by pavan2004it** [comment]
Thanks for the quick response @jessehouwing i ended up doing just that
