### ISSUE TITLE
TFX extension create fails with the new version of the library

### ISSUE THREAD

**Issue by marcosloic** [microsoft/azure-pipelines-task-lib#664]
- [x] Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.11.0
node/v10.22.0

### Issue Description
When trying to create an azure devops extension which has azure-pipelines-task-lib as a dependency, the extension creation fails

### Expected behaviour
The extension is created

### Actual behaviour
The extension cannot be created

### Steps to reproduce
1. Have an azure devops extension
2. Have version 2.11.0 of azure-pipelines-task-lib installed as a dependency of your extension
3. Run `tfx extension create --manifest-globs vss-extension.json`

Alternatively, for step 3: Run the PackageAzureDevOpsExtension@1 task in an azure devops pipeline

### Logs
Error: Part Name '*my project name*/node_modules/azure-pipelines-task-lib/test/scripts/print args cmd with spaces.cmd' is invalid. Please check the following:
1. No whitespace or any of these characters: #^[]<>?
2. Cannot end with a period.
3. No percent-encoded / or \ characters. Additionally, % must be followed by two hex characters.

### Workaround
Reverting to version 2.10.1 of the library fixes the issue

**Comment by kaveaa** [comment]
ran into the same problem, working with 2.10.1 for now
