### ISSUE TITLE
Updated version of VstsTaskSdk in powershellgallery

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-task-lib#674]
Is there a version of VstsTaskSdk newer than 0.11.0 published on may 21, 2018? It appears there have been changes/fixes since then that are possibly not in 0.11.0.

![image](https://user-images.githubusercontent.com/5810165/96149426-4eef5f80-0ed7-11eb-880b-0551e74c3cd5.png)

**Comment by jessehouwing** [comment]
Indeed looks like that didn't ship. I just updated a task to the latest published and my latest commit wasn't in there.

@vtbassmatt 

As a workaround, have pasted the ps1 files from the repo into my tasks `ps_modules` folder and overwrote whatever was there.

**Comment by vtbassmatt** [comment]
Ack, we're looking into it. In the meantime, copying files in should be fine.
