### ISSUE TITLE
Warning when using the find and replace function on azure devops

### ISSUE THREAD

**Issue by mlecallet** [microsoft/azure-pipelines-task-lib#675]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 

### Issue Description
Hello i noticed this warning message when building on a windows azure pipeline:
##[warning]Task 'ReplaceInFilesTextByText' (1.2.0) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

### Expected behaviour
shall i be concerned

### Steps to reproduce
1. added the command vis the azure desvops interface
2. 
3. 
4. 
5. 

### Logs
<see error log above

**Comment by jessehouwing** [comment]
That is something the task author must fix.

You can contact the author of the task to see if they want to release an update targeting the new PowerShell handler.

https://marketplace.visualstudio.com/items?itemName=Samayas.azuredevops-samayas-replaceinfiles

**Comment by mairaw** [comment]
The author mentioned on the Q&A section of the extension that he has this on his to-do list. This issue should probably be closed here.
