### ISSUE TITLE
Correct way to detect the need to use `tl.updateReleaseName`

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-task-lib#679]
Azure DevOps Server 2020 introduced the requirement to use the special logging command to set the release name, prior to that a simple setvariable would do the trick.

In preparation of releasing:
https://github.com/jessehouwing/azure-pipelines-variable-tasks/commit/c003a638af6e2793a9818a9c9eaa2583a06cf720

**How can my task know when to use the old method and when to rely on the new one?**

I see that the `updateReleaseName` asserts the agent version, so it will throw if I call it without prior verification. Since my tasks are used in TFS 2015 all the way up to 2018 still, which won't be shipping with that agent, how can my task detect which method to use?

I could bump the major version of the task and call it quits, but that would saw confusion among my existing customers.

**Comment by vtbassmatt** [comment]
I'd recommend checking the agent version yourself.

```javascript
let useReleaseCommand = false;
try {
  tl.assertAgent("2.165.0"); // I don't recall which agent version we shipped with 2020, this is an example
  useReleaseCommand = true;
} catch (e) { }
```

**Comment by jessehouwing** [comment]
I think the agent supported the command before the server did, so that won't be foolproof... The service already required the command.

**Comment by jessehouwing** [comment]
It looks like UpdateReleaseName was introduced here: 
2.132

That's way before Azure DevOps Server shipped. Meaning that function won't work on Azure DevOps Server 2019 and below, but is required on Azure DevOps Server 2020. And it's now always needed with Azure Pipelines in the service.

Looking at the agent, there are no provisions in the agent's handling of the command to detect the server's capabilities for the command.

I could always try the command in a try/catch, and if it fails try setting the variable in by issuing a setVariable instead. But then again, so could the task lib on my behalf. I think, even if people update their agents to >2.132, this issue won't go away on Azure DevOps Server 2019 and below.

**Comment by vtbassmatt** [comment]
😞

**Comment by shashban** [comment]
@jessehouwing The set variable approach should still work to update the local job scoped variable.

**Comment by jessehouwing** [comment]
I know, but my extension is available on the marketplace and can be installed on 2015 to 2020. The extension doesn't know what server it's installed on and who it talks to.

If it were a private extension, that would be no issue, I'd know the server I'd be running against, since it's mine. But the public extensions don't have that luxury.

The task lib nor the agent keep this in mind. The task lib could decode to issue the old command for backwards compact if the agent or server version is below the threshold.

**Comment by jessehouwing** [comment]
Still open.

**Comment by jessehouwing** [comment]
Still open
