### ISSUE TITLE
task.exec doesn't return exit code for process as expected but goes to catch block for non-zero exit codes

### ISSUE THREAD

**Issue by armanik11** [microsoft/azure-pipelines-task-lib#685]
I have below code in sample.ts where the exe always returns an exit code of 0 (success), 1 (failure) or 2 (unknown errors). I would expect the validateFunc call to return an exit code properly and land in the next line but instead it goes to the catch block for non-zero exit codes. Any idea what causes that behavior?

try

{

...{some code}

 let exitCode = await validateFunc("sample1", "sample2");

if(exitcode!=0)
{
  // expecting toland here when tool returns non-zero exit code (EXPECTED)
}

..{some code here}

}
catch (error)

{

 // Above call to validateFunc lands here for non-zero exit codes (UNEXPECTED)

}

export async function validateFunc(param1: string, param2: string) {

   
      {some code here}

    return await tl.exec(`${validationToolRoot}\\<Exename>`, validationArgs);
}

**Comment by AmrutaKawade** [comment]
we have similar requirement. It is causing this issue https://github.com/microsoft/azure-pipelines-tasks/issues/13819

**Comment by jessehouwing** [comment]
You can pass a iexecoptions instance to ignore the exit code and output to
stderr.

See
https://github.com/microsoft/azure-devops-extension-tasks/blob/main/BuildTasks/InstallExtension/InstallExtension.ts

**Comment by armanik11** [comment]
Thanks @jessehouwing . I'm slightly confused. What I'm expecting is when the tool is done running and returns an exit code, it should respect that and doesn't go to catch block. why does it go to catch block? What's the default behavior in iexecoptions and which setting should i use in iexecoptions to change that behavior?

**Comment by jessehouwing** [comment]
The default is to fail in a non-zero exit code.

See the online docs:
https://www.github.com/microsoft/azure-pipelines-task-lib/tree/master/node%2Ftoolrunner.ts

If you don't want it to fail, override that behavior by passing an instance of iexecoptions.

**Comment by armanik11** [comment]
Thanks. So by fail, the behavior as i understand it that it make it goes to the catch block correct? If I use ignoreReturnCode = true, then it would behave as expected that it will return the exit code and I handle that.

**Comment by jessehouwing** [comment]
Yes.

**Comment by armanik11** [comment]
Hi @jessehouwing ,

If you don't mind, could you please help me with the right syntax for using IExecoptions in my exec call? As I am still learning typescript, I tried below but it fails to build.

  const execoptions: IExecOptions = {
        ignoreReturnCode: true
    };

    return await tl.exec(`${validationToolRoot}\\sample.exe`, validationArgs, execoptions);

Error: error TS2739: Type '{ ignoreReturnCode: true; }' is missing the following properties from type 'IExecOptions': outStream, errStream

How do I pass the iexecoptions with this bool flag as the third parameter?

**Comment by armanik11** [comment]
Never mind, I tried below and it passed build. Thanks!

return await tl.exec(`${validationToolRoot}\\sample.exe`, validationArgs, <any> {ignoreReturnCode: true});

**Comment by armanik11** [comment]
Hi @jessehouwing , I tried my change above but it still goes to the catch block as seen in my original code block snapshot? any idea what i am missing?

**Comment by jessehouwing** [comment]
Are you sure the new code got executed?

**Comment by armanik11** [comment]
yes, i double checked the version of extension/task that's being used

**Comment by jessehouwing** [comment]
Step through it in a debugger in that case. This trick should work.

**Comment by AmrutaKawade** [comment]
ignoreReturnCode : true is not working for me as well.
