### ISSUE TITLE
How to determine if parameter is given by pipeline?

### ISSUE THREAD

**Issue by LockTar** [microsoft/azure-pipelines-task-lib#689]
### Environment
azure-pipelines-task-lib version: 
latest

### Issue Description
How to determine if parameter is given by pipeline?

### Expected behaviour
A new command or overload on `Get-VstsInput` that returns `true` or `false` when a parameter is given in the pipeline or not.

### Actual behaviour
Not possible??? Or describe how...

### Steps to reproduce
1. I have created multiple PowerShell tasks but sometimes you want to know if a parameter is given or not.
In example: I have an update task. This can optionally have a 'Name' parameter. This parameter is to update a name to the value of the parameter. So when given, I update the name in the system, if not given, it should skip the update. Because I can't determine if the parameter is given, it looks like I need to update the name to empty because the value is empty (when the parameter is not given).

Advice on how to do this...

**Comment by jessehouwing** [comment]
My recommendation would be explicitly add a boolean flag to the task to explicitly clear it or to signal that the passed in value should be used. The invoker can use [the expression syntax](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?WT.mc_id=DOP-MVP-5001511&view=azure-devops) `${{ ... }}` or `$[ ... ]` to set that boolean based on some other context data available on the workflow.

You may be able to play with using the default value option in the `task.json`. Setting the default value to `<<UNSET>>` or so and check for that.

Even if this were added later, the server is passing in the values in the workflow would likely need changes to know whether a value was intentionally left empty.

One thing I haven't tried is to check for the presence of the `INPUT_FIELDNAME` environment variable when the value is unset vs left empty. I wonder whether there is something you can see in the agent context.

**Comment by LockTar** [comment]
Hmmm I understand that the agent's don't really support this feature (yet).

This new feature is needed because I've created a new "Update" task that lives besides my already existing "Set" task. This "Update" task came from questions from the community.
I think that creating Booleans for each field is the only way.

So in example:
When my task has the properties:
- Name
- Email

I have to create for input fields. Something like this:

1. UpdateName (bool)
2. Name (string for the value)
3. UpdateEmail (bool)
4. UpdateEmail (string for the value)

Not fun but the only way. Default values won't help because I don't know what to update. For a filepath this is ok. But for fields like name and email this won't work. 
I've created all kind of tests which is checking which parameters are given to my PowerShell cmdlet. That is easy to test with Pester. See for more information the [call from the task](https://github.com/LockTar/AzureAdApplicationManagement/blob/cef0717809bb3a0489c6cfdf764c3bfbc88e1ac4/Vsts-Extension/Update-AzureAdApplication/Update-AzureAdApplicationV3/Main.ps1#L38) or [checking if the parameter is given](https://github.com/LockTar/AzureAdApplicationManagement/blob/cef0717809bb3a0489c6cfdf764c3bfbc88e1ac4/scripts/ManageAadApplications/v3/ManageAadApplications.psm1#L168).

**Comment by jessehouwing** [comment]
I'd probably pick: 

- [ ] ClearName
- Name [............................]

That way you only need to set the boolean when you want to explicitly clear it. And can ignore empty values.

**Comment by jessehouwing** [comment]
And in YAML users could use `clearName = $[ eq(variables.Name, "") ]` if they wanted.

**Comment by LockTar** [comment]
Hi Jesse,
Good idea! I will implement it that way.
