### ISSUE TITLE
Add helper to vsts-task-lib to access the WebApi from vsts-agent in a build task

### ISSUE THREAD

**Issue by gravufo** [microsoft/azure-pipelines-task-lib#71]
As the title says, it would be very helpful to have helper functions in the vsts-task-lib or vsts-agent to call WebApi functions without having to authenticate (since the agent is already authenticated).

This would prevent us from hard coding credentials in the code or in the build definitions.
It also would fix the issue with typescript build tasks requiring to have basic auth in order to authenticate with the web API (which I currently circumvent by using [httpntlm](https://github.com/SamDecrock/node-http-ntlm)).

This issue is a copy of [that issue](https://github.com/Microsoft/vso-agent/issues/89).

Thanks!

**Comment by bryanmacfarlane** [comment]
Great.  Working on this next week. I'll hand back an object with the auth token already set.

**Comment by fredgate** [comment]
Yes great idea. Is the auth token now available ?

**Comment by bryanmacfarlane** [comment]
The auth token is available.  I need to add a convenience method to hand back the web api object.

**Comment by fredgate** [comment]
What is actually the convenient way to call TFS API from a typescript task using the uath token of the agent ?
How to get the auth token ? How to call TFS API ?
I want to trigger a release from a build.

**Comment by fredgate** [comment]
I am writing a powershell task. I want trigger a release from a build. I have a on premise TFS 2015 Update 3 server.
I can get the projects of my collection with the following code : 


```
Add-Type -LiteralPath "$agentDir\Microsoft.TeamFoundation.Core.WebApi.dll"

$uri = New-Object System.Uri($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)
$credentials = Get-VstsVssCredentials

$projectHttpClient = New-Object Microsoft.TeamFoundation.Core.WebApi.ProjectHttpClient($uri, $credentials)
$projects = $projectHttpClient.GetProjects().Result
```

And it works great !
But now how to trigger a release ? There is no client for release part in Microsoft.TeamFoundation.Core.WebApi.dll. I do not find in others DLLs, but may be I miss it.

Else I could directly call the REST API in powershell, but I do not know how to pass the credentials that are encapsulated in the object retruned by Get-VstsVssCredentials.

**Comment by ericsciple** [comment]
@GitHubSriramB can you speak to the DLL question?

@fredgate See [this example](https://www.visualstudio.com/en-us/docs/build/scripts/index#use-the-oauth-token-to-access-the-rest-api) how to authenticate to the REST API. The example is targeted at folks writing ad-hoc scripts, not custom tasks. But the same idea applies. Rather than using `$env:SYSTEM_ACCESSTOKEN`, use `(Get-Endpoint -Name SystemVssConnection -Require)..auth.parameters.AccessToken`.

**Comment by shashban** [comment]
@fredgate - Can you see if https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Release.Client helps you with triggering of the release.

**Comment by whitesource-yossi** [comment]
Hi, 
Does vso-task-lib has a method to hand over the webapi with the token? Is this issue still open? 
Thanks

**Comment by jtpetty** [comment]
@whitesource-yossi - Sorry we lost track of this question but since this is quite old, if this is still an issue,  can you open up a new issue with more details?
