### ISSUE TITLE
Move 3.x version out of preview

### ISSUE THREAD

**Issue by damccorm** [microsoft/azure-pipelines-task-lib#711]
The 3.x version of the task-lib has been in preview for a while, and we've been concurrently maintaining both it and the 2.x version. This was necessary for a while since we weren't ready to recommend everyone upgrade their tasks to Node 10, but at this point we should be recommending that to everyone. Therefore, it is probably time to move the library out of preview. I think we need to take the following steps:

- [x] Branch off current master with a releases/2.x branch
- [x] Merge the releases/3.x branch back into master. This will probably be messy and we need to be careful and review the diff closely.
- [x] Bump the newly constructed master version to 3.1.0 and publish, taking it out of preview

**Comment by egor-bryzgalov** [comment]
Opened a restore branch (copy of the master branch). [Releases/2.x](https://github.com/microsoft/azure-pipelines-task-lib/tree/releases/2.x)

**Comment by egor-bryzgalov** [comment]
Closed as done. The 3.1.0 version of the package has been released and backup branch has been created.

**Comment by johnnyreilly** [comment]
Is there a CHANGELOG anywhere that details the breaking changes with 3.x?  Is it just node support?
