### ISSUE TITLE
How can I mock a pipeline variable in my tests?

### ISSUE THREAD

**Issue by bartier** [microsoft/azure-pipelines-task-lib#716]
### Environment
azure-pipelines-task-lib version: 2.9.3

### Issue Description
Hello,

I'd like to mock pipeline variables in my tests, as the way I can configure in the UI below:
![image](https://user-images.githubusercontent.com/18057391/108379542-cfef9800-71e4-11eb-8ac6-45fcde44ece2.png)

I'm currently writing my test as the following code (I removed the import and other stuff to focus on the problem): 

**test.ts**:
```

let tmr: tmrm.TaskMockRunner = new tmrm.TaskMockRunner(taskPath);

tmr.setVariableName('MYPREFIX_FOO', 'value_here', false);
tmr.run();

```

**index.ts** (Task code):

```
import tl = require("azure-pipelines-task-lib/task")

async function run() {
  let vars = tl.getVariables()

  console.log(tl.getVariables().length) // it shows 0 instead of 1 regarding the MYPREFIX_FOO variable set in the test.ts when I ran the tests. So I can't access MYPREFIX_FOO at all in the test
}

run()

```

### Expected behaviour

Pipeline variable be available to `tl.getVariables()` 

### Actual behaviour

Variable is not available to the `tl.getVariables()`

I'm not sure if I'm missing something. Am I using the correct command to achieve the mock variable?

Thanks

**Comment by bartier** [comment]
I think this relates to a bug where the public variables are not correctly handled when loading the data to run a test. I'll propose a PR to try to fix this.

**Comment by DaniilShmelev** [comment]
Hi @bartier! Thank your for your PR, we'll take a look at it.

**Comment by AnnaOpareva** [comment]
Hi, @bartier you can mock pipeline variables in your tests with use function like in this test  - https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/DotNetCoreCLIV2/Tests/TestCommandTests/publishtestsWithSpaceDir.ts#L61

**Comment by anatolybolshakov** [comment]
@AnnaOpareva this is some kind of a workaround, we need to take a look at [extending](https://github.com/microsoft/azure-pipelines-task-lib/blob/21dac986b4c7478eb2ed8ffbd60e4fad62904438/node/mock-task.ts#L57) of mock-task for this.
