### ISSUE TITLE
Allow NodeJS binaries to be downloaded from a Mirror URL

### ISSUE THREAD

**Issue by ricksbrown** [microsoft/azure-pipelines-task-lib#718]
### Environment

azure-pipelines-task-lib version: All

### Issue Description

When attempting to use `azure-pipelines-task-lib/mock-test` behind a corporate proxy tests fail because of [this line](https://github.com/microsoft/azure-pipelines-task-lib/blob/578d7074e317355d638bea693b562bce8744731a/node/mock-test.ts#L232) which hard codes the nodejs download url:

```js
const nodeUrl: string = 'https://nodejs.org/dist';
```

In highly secure environments these cloud URLs are effectively inaccessible, but on-prem mirrors are available instead.

### Expected behaviour

The SDK should allow developers to configure a mirror URL to use instead of `https://nodejs.org/dist`.

### Actual behaviour

The nodejs download URL is hard-coded.

**Comment by DaniilShmelev** [comment]
Hi @ricksbrown! Thanks for your PR, we'll take a look at it!

**Comment by DaniilShmelev** [comment]
@ricksbrown thanks for your contribution! I've merged your PR, these changes will be released in the next couple of days
