### ISSUE TITLE
Packaging this lib causes tfx-cli to fail when running `extension create`

### ISSUE THREAD

**Issue by cicorias** [Microsoft/azure-pipelines-task-lib#72]
Since `vsts-task-lib` contains some files that aren't acceptable to the `file --mime-type` command, packaging fails.

In order to bypass this error, it requires 2 environment variables to be set:

```
export LC_CTYPE=C 
export LANG=C
```

This allows the `tfx extension create --manifest-globs vss-extension.json` command to run w/ out error.
- the error is shown below:

![image](https://cloud.githubusercontent.com/assets/1080406/14764841/f934bb5e-0994-11e6-8956-06679d180f18.png)

The "root" of the error is in the `file --mime-type` - which when run emits the following:

```
resources.resjson: ERROR: line 22: regexec error 17, (illegal byte sequence)
```

Setting the 2 env variables on OS X (latest) 10.11.4 and prior versions - packages the file OK.

**Comment by damccorm** [comment]
Just tried this and it looks like this is no longer the case so I'm going to close. Feel free to reopen if I'm mistaken.
