### ISSUE TITLE
Custom format error details to avoid leaking secrets

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/azure-pipelines-task-lib#74]

**Comment by damccorm** [comment]
I believe this was fixed as of https://github.com/Microsoft/azure-pipelines-task-lib/commit/597bf395ba4d690cb89b1681a5c0c641b2838cff by using the [env variable](https://github.com/Microsoft/azure-pipelines-tasks/issues/1571), so I'm going to close. Please reopen if I'm incorrect.
