### ISSUE TITLE
Azure Pipeline defined with YAML vs. Azure Pipeline using Classic Interface

### ISSUE THREAD

**Issue by gattjoe** [microsoft/azure-pipelines-task-lib#784]
### Environment
azure-pipelines-task-lib version: Any

### Issue Description

Is there a programmatic way for a custom build/release task to identify whether the pipeline executing the task is an Azure Pipeline defined with YAML vs. an Azure Pipeline using the classic interface? I've studied this [link](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) extensively and I do not see a way to do it completely. 

I think if I query the System.HostType predefined variable and receive anything but "build" as the value, then it would be a classic pipeline.  However, that leaves me with the "build" value that could be the result of a YAML or a classic pipeline.

I thought about querying the sources directory to see if azure-pipelines.yml is there, but just because the file is there, it doesn't mean its being used to execute the pipeline.

**Comment by anatolybolshakov** [comment]
Hi @gattjoe as I see there is no ability to distinguish YAML and classic pipelines.
Could you please elaborate what is the purpose of this? In general creating of such dependency on pipeline type is not a good  practice - since it could lead to unexpected breaking changes in future.

**Comment by gattjoe** [comment]
I wrote a plugin that supports SLSA, which is a framework intended to codify and promote secure software supply-chain practices. SLSA helps trace software artifacts (e.g. binaries) back to the build and source control systems that produced them using in-toto's Attestation metadata format. You can read more at [slsa.dev](https://slsa.dev) if you are interested.

I don't want to create a dependency on one pipeline type vs. the other; however, I think that if the build steps were in an azure-pipelines.yml file (which is tracked by source), it can give someone better assurance on how a binary was produced.  In a classic pipeline, even if the project is public, it would be manual to go inspect someone's pipeline and the history of changes to that pipeline.

So if I were to write the user story here, it would perhaps be the addition of an environmental variable like "buildPipelineType" and its values would be either "classic" or "yaml".

**Comment by anatolybolshakov** [comment]
@gattjoe could you please create ticket on https://developercommunity.visualstudio.com/search?space=21 to get it triaged properly? This sounds like a reasonable feature for Azure Pipelines, although this repo is mostly for task-lib related issues 😃 
Let me close this ticket here since it's not related to the task-lib itself.

**Comment by gattjoe** [comment]
Will do, thanks for the guidance.
