### ISSUE TITLE
attachment limitations

### ISSUE THREAD

**Issue by eRez-ws** [microsoft/azure-pipelines-task-lib#803]
### Environment
azure-pipelines-task-lib version: 3.1.2

more question than an issue:
i'm using the `task.addAttachment(type, fileName, filePath);` functionality successfully so far. 
however,  i couldn't find any documentation regarding attachments limitation - in size or number. 
are there any limitations on that? 
if if so - what are they?

cheers, eRez

**Comment by tatyana-kostromskaya** [comment]
There are no official limitations for this functionality.

**Comment by tatyana-kostromskaya** [comment]
I'm closing this ticket as it was answered.
If you have any other questions here, please reopen it.
