### ISSUE TITLE
3.2.0 version not published yet

### ISSUE THREAD

**Issue by kriti218** [microsoft/azure-pipelines-task-lib#818]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 3.1.10

### Issue Description
We noticed that #815 had version upgrade of task-lib to 3.2 with shelljs vulnerability fix of upgrading from 0.8.4 to 0.8.5.

Can you please suggest when are we going to have 3.2 as latest version?

**Comment by AndreyIvanov42** [comment]
@kriti218 
Hi,
New version is available on npm
