### ISSUE TITLE
No release notes for versions post 2.8.0??

### ISSUE THREAD

**Issue by kriti218** [microsoft/azure-pipelines-task-lib#819]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 3.1.10

### Issue Description
I was trying to find out the changes done to this library since 2.9.x version till 3.1.10 to evaluate if any breaking changes are there in azure-pipelines-task-lib or not. At this link https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/releases.md i could only find release notes till 2.8.0...are the changes between versions still maintained? Can you point me to the link as i did not find on site.

**Comment by DaniilShmelev** [comment]
Hi @kriti218! We don't maintain the changelog at the moment, but I think it makes sense to do that.
Another option would be to add changelogs to each release, and to recreate the missing github releases.
I've added this item to the backlog, we'll take a look at it once we have enough capacity.

**Comment by DaniilShmelev** [comment]
AFAIK there are not supposed to be any breaking changes in tasklib since version 2.8.0.
3.x is focused on allowing us to use tasklib with node 10 and typescript 4.
Also, we faced issues if our tasks had both 3.x and 2.x present in node_modules. So make sure to check your package-lock and ensure that either only 2.x or only 3.x is used in the task.

**Comment by kriti218** [comment]
@DaniilShmelev Thanks for quick response. Good to know that you have added the ask in your backlog. It is always good to maintain change logs per release i feel.

**Comment by kriti218** [comment]
@DaniilShmelev When you say 3.x is to support node 10 and TS 4, i hope it is backward compatible and doesn't make it a mandate to upgrade to node 10 and TS 4? Can you confirm that? This is what your documentation on npm site states:
**Upgrading to Node 10
Upgrading your tasks from Node 6 should be relatively painless, however there are some things to note:

Typescript has been upgraded to TS 4. Older versions of TS may or may not work with Node 14 or the 3.x branch. We recommend upgrading to TS 4 when upgrading to task-lib 3.x.
Node has made some changes to fs between Node 6 and Node 10. It is worth reviewing and testing your tasks thoroughly before publishing updates to Node 10.**

**Comment by jessehouwing** [comment]
Node 6 is currently a deprecated and optional part for the Azure Pipelines
Agent. Consider migrating to Node 10 as an important step to stay
compatible with Azure DevOps Server 2022 and up and Azure DevOps (Service).

Node 6 is past it's support date, no longer maintained and a security
problem waiting to happen.

**Comment by DaniilShmelev** [comment]
Usually we update node, typescript and tasklib version all at the same time when we migrate a task, e.g.: https://github.com/microsoft/azure-pipelines-tasks/pull/14064. We don't have any guarantees that it will work on previous typescript or node versions. So in this sense, there is indeed a breaking change.
