### ISSUE TITLE
Read out PAT from GitHub Enterprise service connection

### ISSUE THREAD

**Issue by glaenzesch** [microsoft/azure-pipelines-task-lib#828]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 3.1.2
Azure DevOps Server 2020

### Issue Description
I want to write a task to connect our Azure DevOps Server with GitHub Enterprise. Therefore, I want to use the created service connection to GitHub Enterprise (PAT). I can select this service connection inside the task, but I cannot retrieve the stored PAT of it.
I tried several approaches but nothing leaded to the expected behavior. Can someone guide me into the right direction?

### Expected behaviour
Access the PAT of the GitHub Enterprise service connection for API calls against GHE 

### Actual behaviour
PAT cannot be read out. 

### Steps to reproduce
None of this worked out:
```
var githubEndpointObject = tl.getEndpointAuthorization(githubEndpoint, false);
let githubEndpointToken = githubEndpointObject.parameters.ApiToken;
githubEndpointToken = githubEndpointObject.parameters['apiToken'];
githubEndpointToken = tl.getEndpointAuthorizationParameter(githubEndpoint, 'Token', false)!;
```

**Comment by KonstantinTyukalov** [comment]
Hi @glaenzesch!
We have higher priority tickets at the moment, and we and can't pay enough attention to your question right now.

I can suggest looking at how this is implemented in the `AzureCLI` task - https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureCLIV2/azureclitask.ts#L106

As a workaround, I might suggest setting up a GitHub PAT token as a secret in pipeline. This doc can help - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

We'll look at possible solutions once we've dealt with the higher-priority tickets.

**Comment by jessehouwing** [comment]
Try writing the retrieved endpoint object to the log as a json string. That way you'll have an idea how the data is actually stored.

The actual secret will be redacted, but that's ok ;)

**Comment by glaenzesch** [comment]
Hi  @KonstantinTyukalov. Thx for your response. I did already this workaround to get my process working.

> As a workaround, I might suggest setting up a GitHub PAT token as a secret in pipeline. This doc can help - https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables


Looking forward to a solution when there is time 👍 
> We'll look at possible solutions once we've dealt with the higher-priority tickets.

**Comment by glaenzesch** [comment]
> Try writing the retrieved endpoint object to the log as a json string. That way you'll have an idea how the data is actually stored.
> 
> The actual secret will be redacted, but that's ok ;)

Hey @jessehouwing. You are right. I did this but it could not be read out so that I can store it an variable to take it as an parameter for other functions.
