### ISSUE TITLE
outdated dependency - minimatch:3.0.4

### ISSUE THREAD

**Issue by txk0705** [microsoft/azure-pipelines-task-lib#832]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues.

### Environment
azure-pipelines-task-lib version: 3.2.0

### Issue Description
minimatch:3.0.4  is out dated and has vulnerabilities requires to update to  latest version. it is no more supported. Outdated library blocks azure task lib installation due to security policies now.

### Logs

Audit log:
  High            minimatch minimatch.js braceExpand() Function Improper
                  Regular Expression DoS
  Package         minimatch
  Patched in      3.0.5
  Dependency of   azure-pipelines-task-lib
  Path            azure-pipelines-task-lib > minimatch
  More info       https://nodesecurity.io/advisories/198521

**Comment by SvetlanaMaliugina** [comment]
Hi @txk0705. We will take a look at this issue in near time.

**Comment by kirill-ivlev** [comment]
Changes were merged.

@mmrazik could you please publish a new version of task-lib?
