### ISSUE TITLE
TaskMockRunner provides no way to assert the results of the task, and cannot find a way to mock modules using MockTestRunner

### ISSUE THREAD

**Issue by chayanikaa** [microsoft/azure-pipelines-task-lib#843]
### Environment
azure-pipelines-task-lib version: 3.3.1

### Issue Description
I cannot find a way to simultaneously mock a module and also assert the result of a task in my unit test. I would like to mock an external package, and assert the result of the task.

I can assert the result of task using MockTestRunner.stdout/MockTestRunner.succeeded etc, but I cannot mock packages using MockTestRunner.

I can mock packages using TaskMockRunner.registerMock, but cannot assert the results as it does not have an API like MockTestRunner.

### Expected behaviour
Is there a way to do both mock external packages and assert results at the same time?

**Comment by max-zaytsev** [comment]
@chayanikaa Thanks for your question! We are working on more prioritized issues now but will get back to this one soon.

**Comment by marcopelegrini** [comment]
Can we please take a look at this again? Relates to this issue: https://github.com/microsoft/azure-pipelines-task-lib/issues/1091
