### ISSUE TITLE
getEndpointAuthorizationScheme is throwing exception

### ISSUE THREAD

**Issue by lordozb** [microsoft/azure-pipelines-task-lib#854]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 3.1.6

### Issue Description
I am owner of Azure Synapse workspace deployment ADO extension. We are using azure-pipelines-task-lib version 3.1.6 from over last 1 year. Suddenly, the method "_getEndpointAuthorizationScheme_" has started throwing exception - 
"_clientId must be a non empty string_". This is only happening when the service connection is of type managed identity. 

This is affection multiple internal and external customers of Azure Synapse. 

### Expected behaviour
It should return if the service connection is of type managed identity or service principal.

### Actual behaviour
Throwing exception.

### Steps to reproduce
1. 
2. 
3. 
4. 
5.

**Comment by DenisRumyantsev** [comment]
Here is the `retrieveSecret` method implemented in `task-lib` — [link](https://github.com/microsoft/azure-pipelines-task-lib/blob/35bcc3f831a6a8b7281eff17ac9a290cb9626e74/node/vault.ts#L58).
This method is general for all secrets stored in a vault and is designed to get the value of a secret by the key (name) of a secret.
The `getEndpointAuthorizationScheme` method (implemented here — [link](https://github.com/microsoft/azure-pipelines-task-lib/blob/35bcc3f831a6a8b7281eff17ac9a290cb9626e74/node/task.ts#L412)) just uses the `retieveSecret` method to get value of the `ENDPOINT_AUTH_SCHEME_<id>` secret from a vault.
I have investigated and debugged the source code of these methods, and they both are working fine.
Pipelines tasks that use these methods (for example, the `AzureCLI` task — [link](https://github.com/microsoft/azure-pipelines-tasks/blob/21e1ac3a7479db74d9e200c4c88e9f020da1c0be/Tasks/AzureCLIV2/azureclitask.ts#L44)) are working fine as well.
I have also checked that recent changes in `task-lib` can not affect these methods.
So, this error is not related to `task-lib` itself.
By the way, here is a package where this error probably appears — [link](https://github.com/Azure/azure-sdk-for-node/blob/fa35b874c212ed71a56f8093ca8e1d959f661cfb/runtime/ms-rest-azure/lib/credentials/userTokenCredentials.js#L49).
It makes sense to contact the code owners of this package.

**Comment by lordozb** [comment]
@DenisRumyantsev The AzureCli task you mentioned, did it work with the MSI service connection?

**Comment by lordozb** [comment]
Looks the somehow the Case of the returned value is changed. Earlier it was in smallcase now it is in title case.
Anyways, I'll add this fix in my code.
Thanks.
