### ISSUE TITLE
Can't express basic logic in visibleRule

### ISSUE THREAD

**Issue by VeraBE** [microsoft/azure-pipelines-task-lib#871]
### Environment
azure-pipelines-task-lib version: 3.2.0

### Issue Description

Some options of our task should only be visible when the underlying tool version is above some value. And currently, we let users chose the version with a picklist that offers Latest, Latest Pre-Release or Exact, when they choose Exact, then another gets visible, where they can write the specific version number. So, for those options that should only show in newer versions, we need to write a visibleRule property like: `ToolVersion = Latest || ToolVersion = LatestPreRelease || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)`, but it doesn't let me use parenthesis, and if I remove them, trusting that operator precedence will work properly, it complains about having both || and && in the same expression... Even though the example in the schema uses both && and || operators: https://github.com/microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json#L224

We also tried to define the property as `ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)`, in that case the extension passed the validations but it didn't show the options when ExactToolVersion was not specified

### Expected behaviour

We should be able to define these types of properties for visibleRule

### Actual behaviour

The extension validation fails with the errors copied below

### Steps to reproduce
Try to create build-task with these types of inputs:
```
{
    [...]
    "inputs": [
        {
            "name": "ToolVersion",
            "label": "Tool Version",
            "type": "pickList",
            "helpMarkDown": "The version of the tool to run",
            "defaultValue": "Latest",
            "options": {
                "Latest": "Latest",
                "LatestPreRelease": "Latest Pre-Release",
                "Exact": "Exact Version"
            },
            "required": false
        },
        {
            "name": "ExactToolVersion",
            "type": "string",
            "label": "Exact Tool Version",
            "helpMarkDown": "The exact version of the tool to use",
            "required": false,
            "visibleRule": "ToolVersion = Exact"
        }
        {
            "name": "Verbose",
            "label": "Verbose",
            "type": "boolean",
            "helpMarkDown": "Shows details about the analysis",
            "required": false,
            "visibleRule": "ToolVersion = Latest || ToolVersion = LatestPreRelease || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)" // It was introduced in version 0.2.0
        },
        [...]
}
```
### Logs

Here are both error messages:

```
Task definition visible rule 'ToolVersion = Latest || ToolVersion = LatestPreRelease || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2)' is invalid. It should be of format "A <validconditionhere> B" for Task with ID '6ce6917b-8489-4f2c-844a-55d401e62efb'.
```

```
Task definition visible rule 'ToolVersion = Latest || ToolVersion = LatestPreRelease || ToolVersion = Exact && exactToolVersion != 0.1.1 && exactToolVersion != 0.1.2' is invalid. Rule cannot contain both '&&' and '||' operators.
```

**Comment by ismayilov-ismayil** [comment]
Hi @VeraBE, thanks for reporting. 
Did you try to group first part of conditions with parentheses?

**Comment by VeraBE** [comment]
Hi @ismayilov-ismayil, thank you for the reply. I think I don't understand your suggestion, what do you mean by group with parenthesis? I mentioned I tried parenthesis like these: `ToolVersion = Latest || ToolVersion = LatestPreRelease || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)` without any luck

**Comment by ismayilov-ismayil** [comment]
Hi @VeraBE 
I meant: ```(ToolVersion = Latest) || (ToolVersion = LatestPreRelease) || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)```
or 
```(ToolVersion = Latest || ToolVersion = LatestPreRelease) || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2 && ExactToolVersion != 0.2.0)```

**Comment by VeraBE** [comment]
@ismayilov-ismayil I tried one of the options, and even pairing each operator with parenthesis and neither worked :/

```
Task definition visible rule '(ToolVersion = Latest) || (ToolVersion = LatestPreRelease) || (ToolVersion = Exact && ExactToolVersion != 0.1.1 && ExactToolVersion != 0.1.2)' is invalid. It should be of format "A <validconditionhere> B" for Task with ID '6ce6917b-8489-4f2c-844a-55d401e62efb'.
```
```
Task definition visible rule '((ToolVersion = Latest) || (ToolVersion = LatestPreRelease)) || ((ToolVersion = Exact) && ((ExactToolVersion != 0.1.1) && (ExactToolVersion != 0.1.2)))' is invalid. It should be of format "A <validconditionhere> B" for Task with ID '6ce6917b-8489-4f2c-844a-55d401e62efb'.
```

**Comment by VeraBE** [comment]
This is still an issue
