### ISSUE TITLE
This script contains malicious content and has been blocked by your antivirus software.

### ISSUE THREAD

**Issue by kaburkett** [microsoft/azure-pipelines-task-lib#872]
https://github.com/microsoft/azure-pipelines-task-lib/blob/5adadaedd70e68a4130f339e0faf8b8a9a72d273/powershell/VstsTaskSdk/ServerOMFunctions.ps1#L1

```
At ServerOMFunctions.ps1:1 char:1
+ <#
+ ~~
This script contains malicious content and has been blocked by your antivirus software.
```

I have no current working theory behind the cause. The agent returns this message during Windows Machine File Copy task. I put in a request for an exemption on this specific script but knowing a theory as to why it became an issue could be helpful.

Thanks.

**Comment by LiliaSabitova** [comment]
Hi @kaburkett could you please advise what antivirus software you have and the version of agent?

**Comment by kaburkett** [comment]
Carbon Black Cloud : Version 3.8.0.398

**Comment by LiliaSabitova** [comment]
Hi @kaburkett, we have checked the script with www.virustotal.com and nothing suspicious was found. We cannot say why your anti-virus considers it as malicious, maybe you could contact the vendor.

**Comment by kaburkett** [comment]
Thanks for your reply.

I followed a Microsoft article on antivirus agent directory exemptions after my initial post.

I will see if the error is still occurring and report back if I uncover any helpful information for future users of windows file copy task.
