### ISSUE TITLE
Is there any way to see what's coming with version 4? Changelog

### ISSUE THREAD

**Issue by johnnyreilly** [microsoft/azure-pipelines-task-lib#891]
Hi!

I spend a fair amount building Azure Pipelines tasks and I noticed that there was a new 4 version on npm.  Is there any kind of changelog or similar I could look at?

**Comment by jessehouwing** [comment]
Mostly: Node 16.

**Comment by johnnyreilly** [comment]
Ah so node 16 doesn't work with 3.x?

**Comment by jessehouwing** [comment]
No clue. 4.x is made for node 16.
3.x was made for Node 10

But I've ran my 3.x tasks on node 6 without any issues.

But in order to make use of the new Node 16 features, use 4.x.

I'm still waiting for extension documentation that properly documents the backwards compat story.

**Comment by johnnyreilly** [comment]
Interesting - a colleague is publishing a task tomorrow targeting node 16, but using 3.x. will see how that goes

**Comment by KonstantinTyukalov** [comment]
Hey!
In version 4.x we wanted to drop support for node 10, but plans changed and now in version 4.x we support both node 10 and 16.

In this case there's no breaking changes between 3.x and 4.x, but we will continue with ver. 4.x

**Comment by johnnyreilly** [comment]
We've migrated - all is good! https://johnnyreilly.com/azure-pipelines-custom-pipelines-task-extension-node-16

**Comment by jessehouwing** [comment]
> We've migrated - all is good! https://johnnyreilly.com/azure-pipelines-custom-pipelines-task-extension-node-16

The reason to have Node10 and Node 16 is for backwards compat with Azure DevOps Server. For the moment there is no version of Azure DevOps server that will auto-upgrade to an agent with built-in Node 16 support. But if your task is on the marketplace, the server will install the new version of the task automatically. If you're shipping the new task with the same major version as before, it will break all in-prem customers.

But it basically also means your tasks must use only Node 10 features, even if they're running on Node 16 or they need to rely on core-js or another library to provide polyfills.

If you're targeting only Azure DevOps cloud, then most of your users should have auto-upgraded to a Node 16 compatible agent.

**Comment by johnnyreilly** [comment]
Yeah - we're targeting only Azure DevOps cloud, so we're happily dropping node 10
