### ISSUE TITLE
NPM page docs links are broken

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/azure-pipelines-task-lib#899]
When I try to click any of the docslinks on the NPM page for this library, I get 404's:

![image](https://user-images.githubusercontent.com/4173387/204310324-21584fc8-2a25-489f-8229-f5d8c12c4641.png)

![image](https://user-images.githubusercontent.com/4173387/204310472-9d013732-7c3e-4614-9c6a-0cc7a3802da2.png)

**Comment by max-zaytsev** [comment]
@jessehouwing thanks for reporting this! We'll take a look

**Comment by max-zaytsev** [comment]
This should be fixed with the next package update
