### ISSUE TITLE
Version 4.1.0 Causes Type Error on Centos7

### ISSUE THREAD

**Issue by embetten** [microsoft/azure-pipelines-task-lib#908]
### Environment
azure-pipelines-task-lib version: 4.1.0 OS: centos

### Issue Description
IF a task takes version 4.1.0 as a dependency AND a user runs the task on a pipeline agent running centos, then the task fails to start and throws a type error.

This is affecting multiple internal pipeline tasks. All other OS have no type error.

### Expected behaviour
Task should start and run as before bumping version to 4.1.0

### Actual behaviour
task fails to start with type error. Example logs:
##[error]Unhandled: errmap.get is not a function or its return value is not iterable
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: errmap.get is not a function or its return value is not iterable
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: errmap.get is not a function or its return value is not iterable
##[error]TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:112:24)
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)

### Steps to reproduce
1. Create a task with 4.1.0 as a dependency
2. Run the task in a pipeline that uses agents running on centos7

### Logs

##[error]Unhandled: errmap.get is not a function or its return value is not iterable
##[debug]Processed: ##vso[task.issue type=error;]Unhandled: errmap.get is not a function or its return value is not iterable
##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: errmap.get is not a function or its return value is not iterable
##[error]TypeError: errmap.get is not a function or its return value is not iterable
    at Object.uvException (internal/errors.js:251:34)
    at handleErrorFromBinding (fs.js:112:24)
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)

**Comment by sergey-koryshev** [comment]
@embetten, version `4.1.0` requires `Node16`, can you confirm that it's installed on your agent?

**Comment by embetten** [comment]
User confirmed this was a quota issue with their agents. We originally thought it was the task versioning because this was the only change done to the task. 

I think you can close this issue.

**Comment by sergey-koryshev** [comment]
@embetten, okay, thank you for letting me know. I close the issue.
