### ISSUE TITLE
Shared location for VSTSSDK

### ISSUE THREAD

**Issue by jeffpatton1971** [microsoft/azure-pipelines-task-lib#914]
### Environment
azure-pipelines-task-lib version:  current

### Issue Description
I'm writing an extension with multiple tasks, it feels very hackish to include a ps_modules folder in every single task. I'm unable to find an example where the SDK is shared for several tasks. I have attempted to define it in the files section of the vss-extension file, but that appears to not do anything, or I'm defining it incorrectly.

### Expected behaviour
I would love to be able to add this into my files section in vss-extension.json so that all my shared powershell modules would have access to it.  
```json
  {
   "path": "mytask/ps_modules"
  }
```

### Actual behaviour
It expects to have the module file locally in each task.

```powershell
##[error]File not found: 'D:\a\_tasks\MyTask_00f968f6-fb8b-475a-903b-7b492eb7d48f\1.0.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
```

**Comment by jessehouwing** [comment]
You unfortunately can't do that. To better understand, when installing the extension, each task is installed separately by zipping up the contents of the contribution into a taskzip. It's that taskzip that's installed into the ProjectCollection/Organization and it's that taskzip that's sent to the agent.

**Comment by Roman-Shchukin** [comment]
Hi @jeffpatton1971, do you have any other question?

**Comment by jeffpatton1971** [comment]
Thanks for this, I do have a follow up, that is slightly related. Is there a way to have the task run PowerShell core? The code I'm using has .net 7.27 and it does not run properly on the regular PowerShell.

**Comment by jessehouwing** [comment]
Not directly, but you can call `& pwsh ./your.other.ps1` from the script that is called by PowerShell 5.

**Comment by jeffpatton1971** [comment]
> Not directly, but you can call `& pwsh ./your.other.ps1` from the script that is called by PowerShell 5.

OOOO i didn't think of that! good call, thanks!
