### ISSUE TITLE
Missing documentation for `mock-*` interfaces

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/azure-pipelines-task-lib#930]
### Environment
azure-pipelines-task-lib version: 4.3.1

### Issue Description

There is no API reference documentation for the testing/mocking interfaces.

### Expected behaviour

Docs please 😄

**Comment by vmapetr** [comment]
Hi, @Ethan-Arrowood thanks for reporting! 
We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by Ethan-Arrowood** [comment]
Are there any examples of how to use the interfaces like Mock Answers and what not at least? I'm having a very hard time understanding usage from the source code alone, and the singular custom task guide only uses `mock-test` (https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?toc=%2Fazure%2Fdevops%2Fpipelines%2Ftoc.json&view=azure-devops#2-unit-test-your-task-scripts)

**Comment by SamJ07** [comment]
Are there any updates on this? Tests have become a blocker and documentation would be very helpful. The example in the link above is very rudimentary.

**Comment by Ethan-Arrowood** [comment]
pleas re-open this. documentation is still missing.
