### ISSUE TITLE
What is the purpose of setting a `message` for `setResult(TaskResult.Succeeded, "Success");` calls?

### ISSUE THREAD

**Issue by Ethan-Arrowood** [microsoft/azure-pipelines-task-lib#940]
Trying to better understand the `setResult` api. Based on the docs, I'm wondering what is the purpose of the second argument, `message`, when `TaskResult.Succeeded` is used? Should it be optional for that enum?

**Comment by ivanduplenskikh** [comment]
Hi @Ethan-Arrowood, it's a good remark.
I made a new PR with proper overloads for function.

**Comment by Ethan-Arrowood** [comment]
Could you take a look at https://github.com/microsoft/azure-pipelines-task-lib/pull/929 too? I opened this one for a similar thing

**Comment by ivanduplenskikh** [comment]
@Ethan-Arrowood, I'm closing this issue for now so #941 has been merged.
I left a review comment in #929.

**Comment by Ethan-Arrowood** [comment]
I don't see the review comment on #929
