### ISSUE TITLE
Add ability to read TimeoutInMinutes in a task

### ISSUE THREAD

**Issue by petrochuk** [microsoft/azure-pipelines-task-lib#949]
### Environment
azure-pipelines-task-lib version: Latest

### Issue Description
We own [Power Platform Build tools tasks](https://github.com/microsoft/powerplatform-build-tools). Each of our tasks calls Power Platform Dataverse via WebAPI. Ideally we would like to synchronize timeouts so user only sets on TimeoutInMinutes and we adjust WebAPI timeout accordingly. When seeing WebAPI errors users are increasing TimeoutInMinutes thinking our tasks will run for longer but it is not affecting us because our task is unable to read TimeoutInMinutes.

### Expected behaviour
Task should be able to read TimeoutInMinutes 

Here is an example: https://github.com/microsoft/powerplatform-build-tools/issues/328

Past asks here: #792 #796

**Comment by vmapetr** [comment]
Hi @petrochuk  thanks for reporting! 
We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by petrochuk** [comment]
@vmapetr move to backlog means this is unlikely to be done right? Just based on backlog size of 600 items

**Comment by markus-codechefs** [comment]
When will collaboration be made possible? @vmapetr any idea?

**Comment by DenisRumyantsev** [comment]
Hi @petrochuk @markus-codechefs.
Let us check if we can prioritize this issue and investigate how we can implement this ability in the task-lib.

**Comment by markus-codechefs** [comment]
I believe we may close this. There have been some improvements with our pipelines but we still experiece issues when a CRM solution takes too long to be deleted.

**Comment by markus-codechefs** [comment]
As you may see in the image below the timeout now happens at 5 min as before it was 4 min. :) 

![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/62404942/015799c2-346a-4dd9-b38e-bceff416362d)
