### ISSUE TITLE
What dictates the order of post jobs and can this be changed?

### ISSUE THREAD

**Issue by tomaustin700** [microsoft/azure-pipelines-task-lib#952]
### Environment
azure-pipelines-task-lib version: 3.1.0

### Issue Description
Hi,
I have a task which has postjobexecution set to run a script, this script cleans down the sources directory on the agent. We are trying to use the caching task with this and the caching post job fails as my post job is cleaning the files up first. This can be seen in the below screenshot:
![image](https://github.com/microsoft/azure-pipelines-task-lib/assets/6324102/776623f5-a2dd-4439-a131-1071f69e7ded)

Is it possible to set the order of post jobs?

### Expected behaviour
Ideally I'd like to be able to specify what order post jobs run in.

### Actual behaviour
Unable to dictate post job order

### Steps to reproduce
Have two post job tasks which run, unable to dictate the order they run.

**Comment by jessehouwing** [comment]
From what I remember, the order is the reverse of how the actual tasks were inserted in the pipeline. First inserted task will run its post-task last.

**Comment by tomaustin700** [comment]
@jessehouwing You're absolutely right! Thanks so much!
