### ISSUE TITLE
Version of VstsTaskSdk packages in PSGallery module stop at 0.11.0 and does not contain fixes from 0.12.0 thru 0.14.0. Please publish newer versions referenced in release notes.

### ISSUE THREAD

**Issue by tristanbarcelon** [microsoft/azure-pipelines-task-lib#956]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 0.11.0

### Issue Description
I would like to take advantage of fixes documented in [newer versions of VstsTaskSdk](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/ReleaseNotes.md) but these fixes are not published in powershellgallery.com. 

### Expected behaviour
Attempting to [consume latest version 0.14.0 of VstsTaskSdk](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md) triggers an error.

### Actual behaviour
Should be able to to consume latest version of VstsTaskSdk.

### Steps to reproduce
1. Proceed to local git repo containing new powershell-based task using powershell
2. Create a new ps_modules subfolder if it does not exist and switch current working directory to that subfolder
3. Invoke `Save-Module -Name VstsTasksdk -Repository PSGallery -RequiredVersion '0.14.0' -Path .\` as shown by [SDK consumption guide](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/powershell/Docs/Consuming.md) and you will encounter error
```text
PackageManagement\Save-Package : No match was found for the specified search criteria and module name 'VstsTaskSdk'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowershell\Modules\PowershellGet\1.0.0.1\PSModule.psml:1598 char:21
+                   $null = PackageManagement\Save-Package @PSBoundParameters
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            + CategoryInfo           : ObjectNotFound: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package] Exception
```

**Comment by aleksandrlevochkin** [comment]
Hi @tristanbarcelon thank you for reporting this issue! This is currently being worked on.
