### ISSUE TITLE
azure-pipelines-task-lib/node/docs /proxy.md contains a minor mistake on one of the samples

### ISSUE THREAD

**Issue by ycamargo** [microsoft/azure-pipelines-task-lib#958]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 4.4.0

### Issue Description
The 2nd example on the [(proxy.md document)](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/proxy.md) is using the wrong name of the function to get Proxy configuration.
It is using `let proxy = tl.getProxyConfiguration()` instead of `let proxy = tl.getHttpProxyConfiguration()`.

### Expected behaviour
The example should be using `let proxy = tl.getHttpProxyConfiguration()` on the 3rd line:
```typescript
import tl = require('azure-pipelines-task-lib/task');

async function run() {
    let proxy = tl.getHttpProxyConfiguration()
    
    process.env['http_proxy'] = proxy.proxyFormattedUrl;
    process.env['https_proxy'] = proxy.proxyFormattedUrl;
    const gitPath: string = tl.which('git');
    const gitPull = tl.tool(gitPath);
    await gitPull.exec()
}

run();
```

### Actual behaviour
But, it uses `let proxy = tl.getProxyConfiguration()` instead, and this function doesn't exist:
```typescript
import tl = require('azure-pipelines-task-lib/task');

async function run() {
    let proxy = tl.getProxyConfiguration()
    
    process.env['http_proxy'] = proxy.proxyFormattedUrl;
    process.env['https_proxy'] = proxy.proxyFormattedUrl;
    const gitPath: string = tl.which('git');
    const gitPull = tl.tool(gitPath);
    await gitPull.exec()
}

run();
```

### Steps to reproduce
Just consult the Proxy module documentation.

### Logs
N/A

**Comment by ycamargo** [comment]
I've created the [PR #959](https://github.com/microsoft/azure-pipelines-task-lib/pull/959) to fix this

**Comment by LiliaSabitova** [comment]
Hi @ycamargo, thanks for reporting and creating a PR.
We are currently working on higher-priority issues, but we will take a look at this PR later.

**Comment by ycamargo** [comment]
It isn't completed yet. The PR is still pending one reviewer approval.
