### ISSUE TITLE
Build issues with deasync

### ISSUE THREAD

**Issue by azchohfi** [microsoft/azure-pipelines-task-lib#972]
### Environment
azure-pipelines-task-lib version: 4.6.0

### Issue Description
Fails to npm install. Seems to be related to deasync being a dependency now, and they are not working well on node 20.

### Expected behaviour
Works just like 4.5.0, and builds fine on node 20.

### Actual behaviour
Fails to restore packages on node 20.

### Steps to reproduce
1. clone https://github.com/microsoft/setup-msstore-cli
2. Update azure-pipelines-task-lib to 4.6.0
3. npm i
4. Fail

**Comment by sverdlov93** [comment]
Hi, the addition on "deasync": "^0.1.28", to the package-json made our ndoe_modules 3 times bigger and our 30MB extension to 80MB extension.
Can you look into it?
@DenisRumyantsev

**Comment by ivanduplenskikh** [comment]
@azchohfi, that is the problem related to [missing binaries](https://github.com/abbr/deasync/issues/106#issuecomment-553826731) as I see.
There are no node20 binaries [deasync-bin repository](https://github.com/abbr/deasync-bin).

**Comment by ivanduplenskikh** [comment]
@azchohfi I noticed binaries (node v19-21) that were uploaded 3 days ago.
I'm closing this ticket for now.

@sverdlov93 upgrading `azure-pipelines-task-lib` from 4.5.0 to 4.6.0 makes `node_modules` bigger by 7MB. Could you please double-check that your problem depends on deasync module? If your problem persists, feel free to create another issue.

**Comment by azchohfi** [comment]
The specific issue was related to Jest itself. I had to add 'node' do the moduleFileExtensions in the jest.config.js.
Still, I'm facing a different issue now. deasyn doesn't seem to work with Jest:
https://github.com/abbr/deasync/issues/156

**Comment by azchohfi** [comment]
Ok, solution is to avoid the deasync code paths completely.
The problem is that whenever the deasync lib is called, the promises start to not work anymore. Solution? Don't go through the deasync code paths. How? Avoid the constructor that calls the sync methods.

Instead of doing:
``` typescript
let tr: ttm.MockTestRunner = new ttm.MockTestRunner(testPath, taskJsonPath)
await tr.runAsync()
```

Do:
``` typescript
let tr: ttm.MockTestRunner = new ttm.MockTestRunner()
await tr.LoadAsync(testPath, taskJsonPath);
await tr.runAsync()
```
It will completelly avoid calling deasync, as it won't call getNodePathSync
