### ISSUE TITLE
`azure-pipelines-task-lib/task`'s `execAsync` fails on `this.tool(...)` 

### ISSUE THREAD

**Issue by dnitsch** [microsoft/azure-pipelines-task-lib#974]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 4.6.0

_Using esbuild to bundle and compile into cjs_

### Issue Description

When using the convenience wrapper around the tool runner from the `azure-pipelines-task-lib/task` the execAsync method fails `Cannot read properties of undefined (reading 'tool')`, the error is coming from here https://github.com/microsoft/azure-pipelines-task-lib/blob/cea7412512a6980646350854731833f289553b5b/node/task.ts#L1451

I am not sure how this was meant to have worked as `this` has nothing in the lexical scope of that standalone exported function, maybe I am being a bit thick here and am missing something "¯\_(ツ)_/¯" . 

### Expected behaviour

When I run the below, I would expect it to work.

```
 await execAsync("az", ["account", "show"], {failOnStdErr: true, ignoreReturnCode: false })
 ```

### Actual behaviour

Return `TypeError: Cannot read properties of undefined (reading 'tool')` 

### Steps to reproduce

```
    test("sample error with wrapper", async () => {
        // import { execAsync } from "azure-pipelines-task-lib/task"
        let err = null
        await execAsync("az", ["account", "show"], {failOnStdErr: true, ignoreReturnCode: false }).catch((ex: any) => {
            err = ex
        })
        expect(err).toBe(null)
    })
    test("no error via toolrunner chaining from task", async () => {
        // import { tool } from "azure-pipelines-task-lib/task"
        let err = null
        await tool("az").arg(["account", "show"]).execAsync().catch((ex: any) => {
            err = ex
        })
        expect(err).toBe(null)
    })
```

Happy to submit a PR to fix that behaviour - IF I got the right end of the stick here

**Comment by aleksandrlevochkin** [comment]
Hi @dnitsch thank you for reporting this issue. I see the same code is used in `exec` and `execSync` methods. Do you have this error when calling those methods as well?
