### ISSUE TITLE
azure-pipelines-task-lib/task's _argStringToArray strips double quotes

### ISSUE THREAD

**Issue by huntantr** [microsoft/azure-pipelines-task-lib#980]
Please check our current Issues to see if someone already reported this https://github.com/Microsoft/azure-pipelines-task-lib/issues

### Environment
azure-pipelines-task-lib version: 2.8.0

### Issue Description
When passing text through the line function, if it contains a " this is being stripping out of the strip. Which in turn creates a bad string that won't work.

### Expected behaviour
Quotes remaining in the string.

### Actual behaviour
Quotes are stripped from the string.

### Additional Information
Maybe I have just not passed the quotes through correctly. I have tried \\", \", "", none of these combinations seem to work.

**Comment by kirill-ivlev** [comment]
Hi @huntantr , thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.
