### ISSUE TITLE
It is not clear which version of the node is supported by the version of the azure-pipelines-task-lib

### ISSUE THREAD

**Issue by gusega** [microsoft/azure-pipelines-task-lib#982]
Dear maintainers,

It's not clear which version of the node is supported by the azure-pipelines-task-lib

From reading this [microsoft documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=yaml%2Cbrowser#node-runner-versions) I understand that only task node 10 runner is guaranteed to be present on the agent. Which means that in order for the task and task tests to run successfully, the `task.json` execution must be set to `Node10` and so the task and it's tests must only use functionality provided in node version 10. Also other dependencies of the task, such as typescript `@types/node` should be of version 10 and the `tsconfig.json` should be for node version 10.

On the other hand, the `task.json` [schema](https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json) allows to use execution `Node16`, although task node 16 runner is not available on the agents. 

So my question is what version of node corresponds to which version of the azure-pipelines-task-lib library? How do I install or request task node 16 runner on an agent?

Thanks.

**Comment by DmitriiBobreshev** [comment]
Hi @gusega, thank you for the question and sorry for the inconvenience. We'll try to improve the docs for better understanding.

Answering your questions, the Node16 runner was introduced in the agent in version [2.206.1](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.206.1) and new node20 runner was introduced in [3.225.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.225.0) so all agent with higher version supports the runners.

For the task-lib, node16 support was introduced with the major version 4 so all task-lib 4.x versions are compatible with it, for node 20 runner we're preparing [the node 20 ](https://github.com/microsoft/azure-pipelines-task-lib/pull/962) support and it will be task-lib version 5.x, but you can use task-lib 4.x with node 20 runners for now, as it uses in some[ in-the-box tasks](https://github.com/microsoft/azure-pipelines-tasks/blob/master/_generated/ANTV1_Node20/task.json#L261)

**Comment by gusega** [comment]
Hi @DmitriiBobreshev, thanks a lot for the clarification. 

What also might be helpful is to emphasize that node runner used to run tasks is bundled in the agent software and that in order to use tasks of certain node version you need to add the minimum agent version.

Thanks again for the reply.
